---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBag7DzIMJ/l/+Ww2I7dCAn9BplJ+CTjCZLmBsWF8pW1ns2PJhfmqun7yHmc25IrjsNvTlR9WqlUHGtyh4pTUgIaQEn7d5bh2Cy7o3MzDUtuvfGfBP1EQ9cw3iquP7twWeOiYziLZxn328/vsrRB2Z00TKwlXs6+utSoBRxffQf4afA3GxefeS7CtvmcMRldSLjIE9tul3y043q5op/ISRBXgYTV0481sKi3a3Y72iXYKcfpewRDa+neliecVrnHkMMxz1+KzJgMpkbRjh0ZnduzpJ9tB99t5cTf5ErwxMm7M8SYPm5Kyrkeqp4HG6LaXX+4OoPsuscyQQU5jPCz3VwKpx9x5M4mHrnnwt/CoO6/KCPYVC951a/8C6PaMm4ViEs4wwtR9jcz1R19OSsoxlJ3zOCAasJParQutcaXfFzY0V0KMeOT6N6mVYkhWZkJnDJHGZSsHzzzZdud6YWDKwjXYXLb4whd8X7uJD0UrbyKXo9XzrUAtp3InQ7PpDDd25GCxYs8babmGwaHgeLh/K4OpEGNQMgbrs/LqzKBtpmvIMMPSQyhrxNvPjv7MB9T+LTgICaW5rS6+IbLPK9N4w+eyNELausE8tGJj49EWbpK/c31oHZepBri3qQCuzX/H0Eo5BN1pdbQODq22kA2iHf+c6xp+LQrVh6CajROd/iMfmck9xj+3g3FGXTboAnBu4qzMSSG3X/x9zWsrccqPzVIZGx+1JUSZFgRfNIlBqMKKFP77l0dRg8
    email: AgAi/h+5Kr69ae8OLe1Mg0fX4ehR8pUq+nHPAMFlUYp4zeQNqeP/IWNd7+4PyOeSZBwGY6caJL2/2d0vmXeTZsV5TDtkji6rroqaxVOlVOKMaN3WPWdiVfw77omXlpvqGnh/OM3Ig43yKBA+X9ftabf2x3z3vrSPVbHFtVVYAoRm1frJnKRtKN9H3s/CBITIRVto84Ux6N274Zc/rZ0tcQut1HNjbv4sWT+IHMCb8p5273lNw30Y0eBEDUYWeWQ5rTNuUMNh+sT8vttSqBukeynz7PjO1Lumcs51aTbbYMsJ9G22GJ/zH5eSj03hoXgMOTe0HVfO1nou02lczFqpYN48Y9TgSjK6fwgfqso+LANCeJkLKvAk8CxkeQgcpA1caTEFNyOzl0+2qsTgoMCrtPEJokNpCfqxsEDtHEUYbnkpP6kHSjYOG5d4jnYxBWtXkiIzYe/fxyqXfPFBitAvCvOjURALm+fADdPrgTOUoaTCCgW7lxQJBQetk3hznF9ARFjKt33cS1SpKutc7n4Hnbhi8Axt+crHa+A4h0xsdCmNzT8zaenhiXgKPq0CZw9c3pcWlBcFyvGlRUhQaa1GTk+5SgsR28lmHGW668bVWM0yHsNSaz1/aLJXxS1pfQj65efQdNuIbcQvA/VSD6bVr83zjN0TPApsrVg2epMCbfeFReAm52dIrbbXRG+DnN6EDwjwWsvCQBQ/SFsvsiTRjE9fWDfKmAgB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
