---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    token: AgCzPM36qipcWK8Tar1VHoWmcmOU8jaQ+XNkOQ/uM3qYTSwOwY6NX/7zwmPI9cmLbRkKzIBrHwZoXj4eyZYuEKctaV5GJflQ9N2oLaM5MvDNCulpOjFYj1TnsAaxyvx8/VTmGIBUz+t3gnJduM9GJMVsEuAGVF3dsvcg8dHnrXR30no1A3HSXBt7yw3aA/6uqbhObGD+eWkXIE9P6pu7ahIr/G9RIWTXrL1E3a1peDPlCrfFrDurCDQiwSXVjC4HfDK8rP7V0L2k8ylU3ASgcwTda6Tw2HJeVzjIvQ2JpZ+rIX5Gdqe+y0AEYZCennsPBmA7DxH5lZCu6Ru/j1F+VoZcsJrv3in9SFR1IiecWxWXGk1ucyRmsK70rBS72ma6NKrpSMBb/LKpLW9Rl4vavvizSz414eMLXOPtY0YiPfM/sO4vIRun7Ig3VhZ9oSSybdEN4SNk1SW19dSt7vEFn2O5zHTZUNtxGFBiQhvRS2D8V2XzIAAadaa46alX4U/NhGrNtCNs83cz21y77Hxg/nEWiS4AkGkuXjgEwP/aCz7t0tpMFNA+vnOXz9k81HCavtMxgqUVALZVv3sJmeeWy7fXXSfMdop6OCwfALRG6CQdFVS/h4Unpp2nqaczcrBqJ9ObcsSGQryzjOzEV6nVDFHlG1wUsLYQEoNPava8gVqQPOLv8zIQKbt/t1VbPBvyPG6i3cdOj8excuQqvBur0gqJL6XJgraSgWgHN4SvGrdO+ZoYckJculfS
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
