---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAc9D8mw98kDUXRTqKNW4BqZjLirqiuaft3GlWlGKl7Hf0S/fVNUaH4c3EPlpyU8oAiFI64vikBX/8//Ct6Hdynbsg4lpXgAorabUbD3Vv+c7cqmankyuUDe5EnTa27gBRuP2L3uvh/LZNVyV0aXZuvbU1sJbLxwpCEOrlyqydtCP15W7DgtbSdYht/InDqpdWS36N/GvD6lJRtgnFXjwPUpQnO1Wwks/44HAOSiSOCvJ11YQLDXfe+SJGZnJeIpm+arv0DdRmjm4SPXzj8JfA8lzTMZg7oqF6MQuGqJlXuBaOmbL5pdAqhiyi6+6+quFgCoOX6RH1LsV1/GtiOVOaMvXiObs3f42AqUwtIbHyPPQUbARr8Kl5e66fV0hTnJxZVB6ENHmbRl2Q6dcqIQnxcFzZMzpqVv+ozld0n5Ek9WGT3JxkswEBteWcPcafOwlgYXFOO3oCY3t1WVT+acXLFrrFFyNta83lzBtwbEpTxkGOooZ/3x57mMV9OB1Ot+YkOlpQC7vdOJQCqA1HJFoBsgbsqzW7AutcmhnliyDINATcFGxYuyXXWX2WFCRyQxrbQN0mgf41EmKrXyoe7XshvXDTJyoXgV0Y7V9ZSPRLGznBte1K+pHA4SGEKCVnKE7rle5IhV0fTiUyRR9bDd7Kr/vSG7ybnxdIIVz7sSQf5jCzHlDAm+jUvSqY6uxdoqY10sdS/64mCJEA7Ri2zdM4MENX/RbbUH9E=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
