---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    token: AgBgk+fc49bnSe7rkh8wMB2H3KfFKS/o7bITN0HmU9X714cb9Xxas62CPU9jonYlcZjz1lN1f4kvzXj3V6FS/uJ6vxqEpSAkr4hGIkv60zxiwBrt+VelFQScK85w+dHJIqx2ywAnhP7rcDRycmas1d5z4rkca3Llg0GuqjGir0KOzikpZKpK8+cOGBde4O+YIpltZbsMEZ52mcbzERUTfV2QmsH2fq7YgwFG9icjzDS4srW3bXnn7BNGxrM7UGCnO4ycTCpkeNxqbKXOVS03FwG3gGnSJ1ahkz4k6paiJ+Sfz92PpYg5ToNRozLVK+ucDjpLjCdJkUBnRQXbu4Ugw0zOIJtqa4ARwFu2yZlK5Dyb7RAYpOQOGeMLqZHr9WKJfbwlfzG3RjBwZEpYtPpUsvV44CdhUcq6LGteBzVbZXrfR6ig7i1xaerwoAs4bNYaFaH60wvpZjL5e82coxFdEYdZ0ofMSjT33iZ/Cjay50wUKBXXjG41bzxd4fQXL6/4ExabMUuvJz0igOOAV7FBEiZb/VMTA8Df82aOBdrQxGoNxvsQ8vWHujN3LtscQiO66YvAJLQHYnPhaWg2E/4TDN5AU3766lCtRDag3Cgl0B0bJWnkzei+J8c9zT8YuVzyQmy4T0A/P3/5YtF23y7bWIMLgE3QaOzmDuedWqu4CM56Ji3aFuEP03cQjTJ2kt5yBwAXyOb9gXvVD3r6m7QxokAltk2qP2omXspAwNP2NwJLlfg9dnFa7190
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
