---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    token: AgC4UXPddtrDM+139jp62QwXpt/+dBM3iBXffFpYEWqbFIbHglMLVI493DG5SUMElyfUgT7jWC+ZEN9Au3sXNP+EeXa2uxaMS4IVu+8FE15a/bVGXLdcGD2cwTM5egUbHJHTAJG5+aDkm5Hnu2kFZOrGuAhCMOVQ8bZQD6yD0BkaGY4nbBYjsHadMb+IYJON7LOBO15a8WgCcBu2dEzL70EbNSdMHFDcOiSoVekYktqxdYfKlctLlXvDh7NuVaipm5ULAKGSk+IgNT0M/6lyZhwHu3UZ9LGRnEMnOEY6fDLnilCP1XRL+GGW8VX0ASMbpiOdI2nrgQdsPSQsFAvPkjF8ylh7rONUDCT+yDutVyUvofdmcvXfaZ4RMf6QJWtUIJqtZXIhGHeMrMZ9SUt0Xi0GrZ3yK1KeU7gVylU06qdc8lT1/fBm1JdYZ9BA8EnVgXlJ3d+2GdIwLG0qoBECA0SsiKW6OKjVU/EdhGn2rP4rJi8aLhTmbrvR+lU/bq123wW1xkslB3NG6YLvftA23B5Op9Q/oCel4Nk2WfedSFyuliW1lOYS9jJrQH824ppCn3l6sMvIjRDkj7o0wkW3JWGhfRwA7/soBDxP5kLBRNmmOEEKSkHF/RLhnbqc6q7xWlIrTw2M2c+cOWi+sVzjAfALZNdxsO0WfbLPzcB3WTXqpqku1zv36iFJXwxO0QtfHoNmW3QrjEBMaMOlIpYTBSO731eOfjV5mGnSsiIlZF1qYJYU0ECX5l7y
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
