---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAk3YCz5vE+TXFRdLUVFlfjeVAbfAwMqIfpiZXkDRP52KvKuG3bCNZeBD+GuPGTBbV6x8G/WlEZ/rE6/JTGyFmFdPOzV7JKJoQsCRG6nhs7XYanA7avjh0j6kqYT602f3eW32T1x7SNi4ZeOKQCIbdTtGXQoZCY8mqPcYWJHdfY1CmdGGkKIT0ndkbtSZZYnLcMsX6bdp8EQqavNDHvBVIVqBaYkf6Mo21JUSKGiBN4/sSfU9QtMNNUm1gKjtU1cKpqatR89WzA6zgiC3hMXK8YEXAbxiPy2JH9sCoZ9DY8U872JYw7IVUhtaaNLLWWdArz6eDPCd05BUyVBmUD0z5c6EXLXSPU24V2wYMhT5MWn71H26jdy1amh8VviLi2pzNo7G1cP+inl0ebZndpj1l7DMw5QsRK6Xm13KMxmwjmql6sxVPRfymmQhXJ9+iE9DkXRwv4areCJBZm/b2R659SY3WxVWRHNn1+qSHW+JNxueApQTXtgDqsCd5sOG/PQ7sxTGqvooMdAp6+UgYz33hG9EYKQDjq/cHYk1nF0uSrq3wyfIaMqqX3Ka6Q0YkCr5cPfCpR40AwfK630gsZxN2jYPZYMizOS3dvUnFdIE1URWse83KmnSZc1Pf9Adv1y93eTP/MAp0an8vkd9mqf8+PpDc2iLISsIusRHGbjNcUT6ipiVQMd8sKeeLEVYrlrpjHf0xCIancGWCP9ukI686u/lrtfYh3Brw=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
