---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAYhNyQBM2UTay1lq/CKrR76IdEe8qULHxRnxhxYCi8Uy3DjhjX3WeI5C7BhV/RQ1L+pPVPgmDct+DzQsSoneofmgU9S5i374X2ATi0xcXvoDkWQMQ+A2y/gxI5d41Dn9uz69mLxZ7h3pmbwqxk9+5B91Fqmc/NfEbeWjYHI+a7v7SZM23v9zw5W6vjifdv9XnMu/Ziuzsxj3q0RUOJZ6/AK+XiA3GDO/NQ3WkOqGu10mZOyHyWAA3UhSHG6wzmwbXQVBvcb8oxzjqsyXPuJlRJp8Uj0IClFeDaEtAS+YjRVX0eU1L/wLDhVkNi9cF1NfaDwetkjTFLW60g3j51hmb9PTVHOrO8HrE9WDQ474g7b+5JjS6/JeCGpbctyQaWYB+KKhs0+4jzSwsDOgAb9qTRgGvrIE7WiuCM9rOytSwTgoEF2e+SkZ7cCjGZqRvh4A8hUQC4lhF5nQx+n0kaFOp8ECwtHdZCzg+QDqLk2FkK/ngGrVlEfbB6cuJ66NCY9Hmhl3K9HSfT4Y0ZSXCWaQw5NH3q9YGCNl5RlSnEe21j6oD7CcXngHObBSI0sroWOXocoOlk700D4FkTyTx6R7Ga/bC34w4FGeJ5ZiPDTEzemFK2LnXBBgUa74OWLB7gz/IKCB7FaCCR0GcdoDnIEdDwVRtaR7gNmIgtSB8VQH/Lr9cmMJOl242wvsyaA/PgnPKKPZFdMCjFKZpYAV255I+e+EIpALFHXM8=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
