---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgA0zgp85Fw/vqhir1t/+FynK1mCyvZg7KXozQxyqRlz/Yp7lQS4MewBc2W97Z21/IQ/ryDwM2ac8vf7kaOGCrw/yLLQ5gqiOU/0KuUjzEN2NtuH2XAOGe62EGmKz5e3fB7RjKNq062eY8kCs5sZfriju0OCgZVMk4O9cjL/fiZQaVU41VGEu1x5BdLWVraQezkHonRWheMKjZdNfGm0U2yvs61gGHuzGDDuThfOjICXa5hdww+4q1XT1RNYYHtzHUAGR5UCRDJ0Gv91OHxSr8jNP6aQj4msw56CfB8cESqHG3pbq/9afHfIx8ZUYjRfgLlyhJvmtXUGK5BDx2cM+Wuo/sXQP6Gf6TeoXjWFyFbiPetRsujkTp/n5PZR+F/qv3kqbD3jfd4nz0SOuAr9J/P78efAue5cWwWT8oVUIep+yQJDT9KfynuXoXUGsyMZKLLt7OibfPJp1jTHaxhNJDW3rM5btxxEJoPlYLLzilnKGIsoKoXbbO1ZdxK+d//eVsbVQBd5eih2Mmw6MoZ6MgTLBCAz0A2Bi+uRwdl67nrz40fgz50/ausL6ewDztLOF3eMLPaM2esrhSsRqEm6E3rxTnz0kSeKcKnLb5+4Qnub+21pxpOkDXmOlHSLSaK3RXA6/1RJgDKdmK6ILh4ZTHTKuxHDHdqBH9vHx3FLCT9zuJLikRxJzow1iJce/YSyQaDHP9HkifQSDsAh
    root-user: AgAehV6ct7dsvenI8UBPRLNCXgd2gTjyh+qMKeWQhHiTsmPSn4osQwkkPFv2ed52wXIFQsBQ7Z6gR/7F2o9eCzatLJR7uSqCjGkcOSyeIiWoi9CTdZgsq9yijzM05ZEUICNmwZuUkNhyCKZUqcCnIP1cM5mZBBazX040m+fy8/rbxjJBGJmwyhpJbt1qE8P6jupma06jXjLydIyPJjIHdJlHPtpGxLKRB67pLev27lmA0IHSKNt31oRrI5zSasCmkQ/rEBVa9f+A0SQob2PaF/wZeaTv1Je41Rez5glCELaDhfcskPhtqnSBSlaxlWAhWy1hjJRCyguPIZ5d5vQfgN3pG+1Qzo9Ztr7GEeo8tibhhANTsEAXJxiOTd7VEubsr8fj1Qvj9NsXcci0wBDniEjPSjrgq2zpmAlhTL265jhZ6tTXEhZgqfhkqVFs62p/PUSaQ93o6giyWUb2LzFmvK2pJLncp4lhDnwUzvUXnaJI2ZqeDuqWs+x5swew5nAYSc9Bp7yWuXaaYNrPRsnxCfMi7pyu/lpWEG22cMkxIRAGNGKsyzYT7KcU2lwPnYooo/oTByRZaEJm0aFaz7wwtgvWKqR9fuw2TBmuQGzxEj/hAtQCwJ0nmjWXRWJxoUgjagrqn4x1KxUk8+TOaCiZulFOiMQ51vfYUuG+s20eLw4QTFvw4jhAPtpSs8sED4Ot8J+HDBKIBzbSBkw4
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
