---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBbfigt3K6F0qKMhBEsavlwOAptGNQxZb+Dr5U1wAjPrDHoofmEG7ZKLY1rSRtiJQaWvYtsdW8HxHDqckSiEFoIZ086oClJ1K6AG88FAWk1DYzB9xhBeQ5F9lbzuA9s6IUv6U08i355RB4qKNXQ7DUTs/765/Sw3CQY0+t/DoUTcGIIG1QYZV9QM2dRUl2xNsgStnv7awGLIwsSSl10uT532hlMBu6+wXrbis/CtN064wBjUsTv3wCPLwZReKPfXWhOt44XHdmRcnR53AFHSSofKbL+hBpidkuKiQnn8qLVeuwk4RuqDEVzabw5ZErxjE8t0YhPz2d/F9aHOc4+stuh9yH3aSBkGyTvwWX9iPjhC587sya4ZeKzMgdxfZJBUPhr+LkN6bqOJcxReruY9a+1Z/YmND2R6Hv7JH7rZUsKUNEZeuMZ96mXY+z41JGHGWbfgynGYSEK7AvRxMUf8NTe55cNzQXjxcMSMuZ9pbfTVjjuXZe99rPUHucMHRwrYq6WUgbWIPUpHp8q79ZKwqv27GHRjtgQP30Z/NYRYVADz8fE0P8bw8ColODzcIl3WuhLoIVV/ATbAjTCPIrihGzpjT6eErp4XZOnF1VwJgh+mPCr7XT1t+E44rSUFBkatNIH/DPvnxWFcXmPS+hLsyufgTVsPn/6mAgt/jWCGSRjTr+/J5v4jLZtyhP8EoGJNFHEyTjqbrT58BGG
    root-user: AgB2qFjbQwjVTAWT7cxLaEaOE8DGbdsNExIpmpRUMxJ/dsTcD2VGVYq8eC9GdbuqiaR1wJGmYeTAl5/QPIyXEaKr6bW9kazPuTHMabwIe8h9hED20nf87E3He1w5hJDTw8BT88vOEt+HeLYMZ4ftQxLCXjyrOnWV2dNd6Q/osTrEoSr02wRYb+LouXUmOKUh04qq1KZIS0r07V+pUS/Aget0YLm0fdvmRVfMWaE96oFqTcy8EZQlOvTYNLpRomAwTW6vORf0rPWhrdR8DMlX19hthKywl42NOyOkBA/Udb1HfIr9byIi+seNbsak43j6eTTRRs0gfPDoaY2P1Pd0CVHqiQ2RXiWokhMNoFOdJsvkjYXbfawNgmysnAz7GLIRY38RH6ESB/5Mm/KV8+RkRvKIDfMcFQRv4tCYNJ9vQ6kDcM7z+BFD26d044rrHnbCNBCUYbvXWtOGNCCtFXmTdGCRbyww8CIB0h2vBgoH9DPfJPXzkOqcqjfHHSAmtcSFFmpbg7BF0p9n5ZmGj5a2H+ZJEODVvxUp9fgPGCChbXwNdcaA+qKSOjIjylAcsUOt32u5vleYtWeLQ2jsXpK7pUgTvGYAXsbKc6mcgYaEdJvaUaDUcbIKsxDLz9KVH8NJv46PT8FpjKqcxHc4TWnC8RoDaDWHpJkw8YkEPoyCqSCSnyDnwemzMbWiFYCx55VWSqor8/g+ByCwplk9
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
