---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgBi9ZzaYaTKCeKJm4GHbkedin2aj4GjZL03SpLm2FEvi8rXdOzva/Ua6BjDyA4L0+eyQmM7tUXN51uPQmkN6wAIDgkUwF03WqWz7b0/WImciaP2rb4/5/kCHhJKeeAaToNvr0eK53CXSC27UujEdyiZ/N4UMLbnk6yXYxYuEFxFW4XLnN9upJwvFkXlyaTTIkI4zCP640WdO70yJJBXJsCdkA/P9uh7EL6TH0sckB6fTG1vaAsZqvplvc1pBRFgsRZ3scL4Q25HeqNHCbiC8Fu5ueWjU0+mZSPjlh9nEMuMxi7EIUIKz5Oj7z16Jjs+IHr2YgDRjxIq4UWPgIHIgHTH2hLgREFtOdB9V7Q43ECC05QJVv5ehjuxZaAvthfjUKw4o8/coU2VMwvLPNDnwQE2zt9bbKAz4T6e8JiyX7Ox776wB28yAI8BA6UNg4WsSD5bOTzBlVD5Bg9ag9tWKrugBVMq2cYk5+vQJFgzpjI+9sDVI+gYVM3YXrQLi4m0V9yTDo2A3ghIofZVOzmXfZhwkaYWsBGG4gw5OZF+tl84lkNRK5NT4O1IgA7X31yQVWEl9rU7soHcSJnSs2WzxbVfZ8q7I5LiGBVKmziHy6sh8t51B5iuqy1I25ARpSDDmP1SyQQravGnzyBdHuYCKlDoOFVS9k6c2X5toPmiDnTbNmp7JnnvQ8z+/MXdbsILSr6tSiLuXB1YNmFyP+2tpBvWimpUCQDATXjC21NHjjNrIr+aiOOk0qxshR547iU5nqlpGtI4S6AMeWaGFryn/ov6C4CeD3LZgWwRrIb8kOz0LTmKyWPQb2qjV05Hw2m6D9GYK8QaIvU1QQ1/5Cz7Sr+VE/Ec
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
