---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgAThLO5kr0eJ935HzRHjxCkRNs5K2f7/89r+T8wsy26QHqXCc97uK/sC1GWqmkXArQpH9qjwoL30vAw6TB3AcwbQwulTXwRQvJvyhTgZ4cuWbvBSraJCrxyaU5fDRZio4v+VgztB6SsIrv0qqRl9A4y30glTUGnQmhp1dOhOZ7bnV8U7L8ZyVyBUKA6ir6v2QGipedevYKgr8pkRzAlxlhrXnGP9NzxV+u5BQsRayc20t8KR6HlDxfC+zphghh/sqmBKQOhQ5XEtdln5pizq0YbuhFPMjnuWcRfVHcBkdidy3a7LQO4ppCf0niuBUB8p41yhV9YiIivihR+fkMacpsiLPCgE9zzLVDxqTqyrOKlj8fTJk+aVOTXFqxTcHFumWcS+gQc9IQkE5MDUqzVtsy1NPT7oWkYx3F4KUHPMONCQl4fUt+1B5wpfbXQG+xdX5hPclAmNVBbk4Z1scTahzfdhlGxUrfjCnbBhM1AHID2H2q0nlTEFt5hFm1vl85P4MhMhYi+CytOPaBdtE1zNBnRQkjlHdZRYsnNB+XBpQn+c3Q1fKLo839G3kRY25MklZ1YH6skfK9tGkOS6LmD4NwqBdBbusa6gRMZ+8BCO8UvXvzJw5LE6HVkOk0DcFvcMFzqxWk98P2xzlqZ3bO9S9MvoHenMqJiEU/myIjhEOrMr/3Wlxuy7o1uet4AU2r0gPnX4yD23FA4hlMW
    root-user: AgCE9CddgDK8y2mMEWsDJKtzKuL2rJv7CkQoGXsUVf5M9QTpvZtBSzrPhuThdN27oHc6TJCHFKEZI5TiuKheLUh0GXkbdl22IEQfGJHqZRKfgBrqL1ne7MKIiUwTrM/MoCAHOlqk9csehpkBhGb406x8+AftNHqOQBvJsRxoEBGr6YhYS9gjimaEOFlIFcB01cbEa026xu72O7RDTBiOWxFP5OWqBZQoqMyucv3TjqgV24dyKu8HquYaxTtP5pzavEKssHlWC/qGRSzsoh/odZNOLpMTh/h+pIsDP3GMr8L4SAyl4OMtlfW6dsPwhotr5OtrUHQJyQKMDuqhOE89U9eS6UvjCcJQo6haQ67yNVcs4lDyRYTeF/aRrl9ERemnoki4odWCbFnxEzpRztoAgvmJJtkSmFB4ca1UFRcXQQ5Esc2YwigP7YAWlaHGEKxKw0v0D8C1P7ohvc9nusfwC2ntPPXCC1qf+gbQj+mx3z43OjaYCIBnl9k4HePk2kgFu6sUJFOktiQ2JfpOb87G/vz8+HXfSn12Ept30g6W8Pc5CJivqfAeb17CHAfhfpikjZskXmGiGxQRrNv0wvB1R5Evaf9U4NGbfvxS8GA3pQE3dJ2f5tecgGgAVCTH5Mof8nGWJD9Bd0UL8Mbu9Wxyu6rcMraGtfY2LmciH/bbNuYO9yrePbDN9Sehq9JHzC5WERnmmHysSIfLfJVt
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
