---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgAkvG/3go6A+A085TLfIACmwrfJG5acSOFC9weuZiF1GvQhAcdm6itwgQPBuI6ntDbrZjBSvujIpwywOWGYGfCqjkJRU9ipNxssDkC8oDS8kUzpFDOk94GQBOtc9SEq/PjjBqkTvcFN/aI4Ac+BR2hH3RiSpJQvP5KEttn4qT3EYxfdRsZxUxuz6dg2SGG9CCeYprXROgNHyju3OFH6xNxVxd5oZCTEHmai1Lgj01JrfzTZqy4AvZJa7sWeKCw9YfzVqIHf2JuH/XejhrW7tFVpkFSfo3m8WVsrxkQjf2BTSZspw/Skde52aONheCR+6qFQhMULxpeyDQ/BS0IJB2E0LSqnobJOYrF6fj0OlEeGyXcBZgxNIhhLEcDV8pMVuc/mdDErMRXmvKFcxtIeDHGRJSzI9jtVeRQhg2E6lcfAVQe7ICKet++eATgzypsrSfhPRVKYC/rNlwEznKTdW8CXpa0922gCgYPgivbK/NHtWDOZ7RsKkISI19xAn1KQ7sYOvBLa56/fh1ISE1I1x4vxoX5hvYaLh63BmE+PIUmFvB3mQp/fqE3yd8Acit7SteiRwWAa+N5ZB4B0SHaoBkxSxf5PttW3Ik/WogNeVqeR6TV0sFQNSnpahuX6GF6E9mgyTPzsT8NoiZXTvpTggRhY6Vy6uUFTKYZNa2NshGIkwcC63mDm0Bnnh+05yweFLNRlLwAToVFnj8lOhCG+CNjTUJfQcUNprQfT4a4OdtlUtv9uQSU910MlYC8KNkt5Y9f/WQAqVQnNEhdxGcQzUtHJsfavgbgesTDgEAqO03XpUnwKm9r2F7WWXCtoQi+bRYG7g8lrk36vmuQMosSDA9roeRzt
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
