---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBCwznPDqwm5TC5I7MEGblwf3l52pTHq9ZDckFCT5nVJKkVGmSDYUvCyAlCCwxiVbj2Tt50OYJqUKEBmELJtGHKxUL9CtTQIUlLjNnem0TCLv+rLOoo1IsseVBORXgwxjOT+bqx0emEqnFlhohWhHXgam+gznlUdBL+LeXK8c8vMzuDa0yv67PADcbFPc3Ekh57aVOYgjs/7vBwd/vAwPJlMRu4BjEx/bZ62YDuPSB8X9irU6kO81VYPEvAFV4n2AmSYx14FUO5e4g3SEAHSQiMssZQEq8uGp4srvA60Bvy3U6j3Mt47oogrGrCZCMf6KEglxFQM30rsk4HKkFwMiV4qO0lYu5AdD4yfElw1fDw8PLnZk7hpRaOcF4WMricdDrAnuMkgTfAXwVI5kR/g0f6OT7sG2mBtYV2RToogUZL+byFILDz5UtAIcDHJesyjRS/vPnD2F73JG842DvvlhPx+iW70/JRkwKGFBREpzfatGH68L37chFdogvQLDH/fa333q2rbtH6Vjo+nlk3PS8kDRBReA5+rG4kvZ8bu9p0LsZipn1WT2fQbbK8i7/1x7OasSLkiz+2ipH9SYReJg8ZnF6k85dkesgVgH1IzzJ4g/ZIwbfXg4x1SN8bXURnrLoeq+JVAhd7DEsNPzKHoEgbJg5MtId51h9eb0EvB2rshBxrCUdiTNYu6JM9s5ePHT/fCKIkFCIgWuil
    root-user: AgCCDmcnMBjP6omDWOS12H9riqPW1IFTofMNUus58N40+uaDNZJEuJDTDVwNoktUqT2+KNdCzGPU0a0QFUkLWfWDD+UuZplwrYSMj+X9Gr512mOzMzgwjlqiX622vDbfW66SII+8hYakaSm9CHN8r6b99UUIAnpdLYN1olWn1OhR2IMskhQvmaPYmgdL19h2/258MOeo7pxBthdR5CZUhwYzzST7GX91Nrt5iBbZiUWh1AdqhnAQXO9IY24U/g4K7NXbsY0xg5v/SZvPxTSksB2n0uwafDYXD7XtZ5fqsL9Bs2KiBPpWD6V/8jV+tDDP6/ASj0rqIskCSUsC6xDKbxORlzzvRBKfoz2UuSuWNBCVBVOqIISu2lVlyuoeoYd/2zltIW3xfkOZ65kY83OQGLp4LNfB8uExrHnoi3tDSEmaNZx9VexDCKfluU/b9Fw4heS/L9uJHzGfcBiyOFvYbrFlJS+S0bJ3AUWvGkzGo2VzK3o9IW4++Ma7J90PWCz2Ru7CgzeEDuk1Ggtx4tEcq/Eib5cZZvgb6vj0sZcoccOcZKh+I9rRfSJGaO7jJZMeV/y1WiCzV5SazejyvS8DLSbYzEDC9tOtk7fRreusTw3U+mXpbF4NqPTsDbjv5Syrx57aoYHxAw5LezlC0qxNJ9GQ3UktjUVg9k8hsTc1A20s/qSr28wzQmBXhsxrRm/2m4MLc/QJ0v3zeyyw
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
