---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBA+M/QxJCKtcziEnz+ww7ExLDXfn06hNtfO0fCjFTY0PyOZ0cNQYiTu+dNQF+6Ak3nH7Wf1vvhjHVA8bXfQaQUeK+nYIHK5jBZgWChnj6u+DsfmF3ITpEy78tLF5P17ft/jcmO14dZkVSajQnobIbYXQmvqsMm5c0Wa1iVgrHd+oXAlnf6RytuDq+tbVTcQX0QSrpMosmL0zgqWzFakEJMvyW5r4zsFjCl3CBIzfKtYzFP1B8DorrTjaxZlF/bkt+Xtpmjf+1h8Qha0A0EGm8NAE1XZhynnKhRlADtcqxcI7OoPOTMCy9qE/8DgXZSeEu2Es/+3kPyZQkvssxf+V01BnJHheWfYnKuXN34TaLCmSYul2/hSyCX7Q32hkG63DDhwRLsMPb6v7lYnDU+G1ySZFJNcnnHr9H2hX0/mX07Rrt0ESGAK9V2ONcKqjC3j69sgOAvOjD6hTOFhKM+uvmMW9f7CXmxc/NU6suNtFAs9kacdzeJAPoeU/1T7qwVil57iqhnVrJy2I0IvlTlmnMnjC/dwcELAJgQc2uD8ShrgTpGHujB3Jx6clRlquvkdXgahkAF3+3kuoNFZQ3NlM9obZUOZNQWH2XVeL+vuKFf4VWX/PkChcnZB3DTOogID7wgelGX5QRg2q4vViU2QBzIlUYOPKOwvtibvuslqyoU2cT/bsSDMz2zoRDpo2+k8CpUhlmLwpyyZbwP
    root-user: AgCM25ZdqSqbz7wh6XlBE8J5NW1fO9wBgaxY6dQ14OY827+c6VpK7EMwahKbQ5LnNxANAOL7cARF5q9kfbzkrDESpuM0Mw+n0qCAPKwlBKen/vMhPEX43j6xYcMpQcwIBvfO/h+mfj1A1GYcphBZrhufxyXa5e8aHEP9R8MEO3bfr694Cf0WVhyPOKwtFy+sa0nmUz8ohXQIUlLxdzexOJksSt266fXpPhdRp1Pgu2J0IFQel8ooV9B+YB9WLxohXZx7hgLax/KMuSS9b9hxOhDKMyORAYZWiKWYhk40VhKPeLJkdX4JJSnZZk8jwtlOfNyfbvqLi1AZfYu7R/l/Sd5l7XNk1qjRiI5313pK0VywlR33hxpYGCFqBBOOXZtFSy1a63JNCyqJTuKTeGxJ1pKc9zrClTfNnVrShCft1eQ1pMJog1dKBWmPqFQbBIi3YSJszig7vno4feK/AACQjBRxO/o63P4GTxVPQYplo3Xi2EslwpEPYMkJkWIH8gAQBdWifWvzKE4lRG7JMQxD4OEip1ZcCnCGFys0X2rAzzSd6SUvj44Qo7IGFjtrfnDrLkaEY94F9zV/kEclI9PlVQJpVlHNiA0qmQvqNrR4Qvm4FdjWvyk6r9ef5/RJAhbZS2BVaIh6RJsWA0kDGLzUFHiHPhOWrCjJnDkxNFLyyNdOjWXMoogDPxIr+wOvRne2+AFMzs4fSPYz25YZ
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
