---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgDQmtATh/oaGvQW7IwGd8cfnzlz4IFWQNAEAgAe8YLGzdpVU/rMXCqA5EQudcV/nmWmxJgNIT7WYkbEfcRbpzNRLTqJ0FqzOeW9zwDG4oQY/L3eMxNpFnSUtyQN8WYbQriLtV+zAapeL/Mcr7e8ZirqGr2K2BnGd0Runp5DcmIZWEEDkKMghpalV4mN3jgPW96oJBDTryvMDKpfskgBS61Dp8dKyApz2tndeFmAfEEIl+gxJgKBx8A98byuCRSb1aXzTnglgAZjD/84TrEwbEcx18ii1+t2JmanFh0BPWTj8pKzrU6ZzKMYFtvi51iAJ6RWt+2mRu0XKzL4is7M8Mftckemx0OoJVXi5x0uW6TTQbZ09NyVnIv3eZDykIjBsE9iZJwUBpKsfkszhMkwWCT4Yp7h1Abf1l8PDX5/kAl4ZP9zSJRBwdPxYrihXMj1TgpCU0ZtbzbrrbuRl3a9WITU6IKYX8Nf53763HxZMOF5FcHbteOyS/MtmIDIodl+JQNOKxGeKMZtRYBA++uotVXD1uQJLg7toMPm1MMM050ugYdFTDaGtOWGwVuS3AYBgLWRqwuOUJqbgbt6VPrCKXmMlxeYcA5A3iVbF4G1JgAqdnFdxTLjh4ppRASq995rUFKVddj5kZlClLAbZxyrMhpgFZP2lwFabFDbAnhEpnnb0tzaOcZSqkYOaDlEpDc3QHjcVqCH36jxLY02
    root-user: AgAaqQk/Q5G9/xK3xRvjGNhJPiN6KjOQuCONXFUOMpuSyhAr5nsyNiihUN2FQavMz0rrXo6gf0NsBl2EZn5hqjC53RnLZZpW4XqLNqj+jUCRsqu4ESHagJcnzN7EYFuFmYnrPSAKacMU0pDpBlNG3tvaTiNXfbnTVlPsKvQzk/MBitUyhEJRlzkTsIIu1+dhZxsxJ7MDqFbejW/+1K5LtTCN6y2kToyTi9cV8dvDtgL8qvieYFiyfIxLcw+ol09C8tsP5jEFU4KsrOHiE5cLjaoZVvAs/7ZLq+C9AXYdHAJiVPqyc6OjZcBDc54G5x162lKEw7sMk0Jv3DPqc+9Nn7uptN1neVD1a7bOB38zmqEP5X4/x/nU9w1pU1UxbVAt17F6kQsFYKmOBucMVv7cFwTtO3pupiBs6t3W6dt+5zsoD/0Ewry//sulK4b8G4AYGxP3GlNoiPFi6qGlBtPlLqno9smXHwNlqEd+aJiMxVE7oU0X9mamuDT0EOXiDx6DLJKNdSj72+FvuzWq+dNZFU2oaCJE3/gDQbFyY6RUJLGinsDgOXxG1RT3yUq7QfK3LJvpfH8nVITadHlh1G+VgkZO7iCGsMo7cqo/AlufLAgR8+q/LOHR0sUcMYRCHXYVLnxwjx2oHn6wbRkRWAVYXdBvYc2iPpjn5vQ+0rjdroJa//+69FA57I4fSCt1T8eww/btle8cxdcVnIK7
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
