---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgBIcaaL+ritrZvmjzVVc5MYIMuYeZUQvEeW+WieCbNCaXuVflWWxpeg+7uDnAM7LEsObr6Kg3PgHRCVwB+LSBc/6hMs9uhkbp6Alx7twqnKZA6LYXm7EynN4b05/hQxk66WwnjNf1647D7eP3JpKjnLcu0SSbIApFeZcw1bhkOS7r8HegY6Gde3n+Q0OOHcVCS51G5stLTBhvaiO4Qh7rcso4zov6AGHSS7Tv5Sr+RhCPTkgdytTADS6Ee6DODdUKS08G9eFk63r5shI317gz/MU3wQVv2qvUMWEYL9ubImuzev1FOhhJMjl8V4bBQC+nWFQrKJtdjhpfnlojkkWT4PpnjEG5yBdrRiZFIYpfKg7h1lHCQUv+vYHk4sM9s4IYNVGmsSXMdKgmoPEdoAln1sYzQNbeF47zkOTf1PCMbIOFJ7gmNNC/4wmtj0wpy0QaXZB7GsBezUp5LxwVv/IcCYCuNfMrkEuMIJRUmyJ32X6IC4mM3PGu0vA6+QHcJoFsoat6ROaClKq7H1ROjlKQBpfa24WyQ6tqlHf6f5I4i3pL1ogUgAltgZUi7hjj4cNaI/eEl4vm7NEvlk8GUIiqO9Y16c3faiHGm140h0gIQ6iOxtEJcg8hxG9QKLsW9zbh6qGSM0mYoRxJ33e9+ydKX2HyhZCUfpX2tBT3vPDrAasJTLRAL70EGRyc1n7C+aXIcg2E6O+F6KYmL7InZgxn/we0dULN1qR4ew4INz6Ib/hiJYEmuPMYQfNhIWXmOiAYe6vhTSzeSM/YSlYDzhnCdVsTLuB4SVh39Qy9oANetqqNOTggO74CuqMfj/VVSDqqy4grJi5lEtp798t4+mhaTlQ/yM
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
