---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCHUBvGFwrjlmlst75h40wcQG0W0XxYLgAG7yuAGxLH6c1uqAA1IaVTqvuNPmnW3lz+6LaslPo4GqGAa47/bN2XQhsUkTj7KceGFBiUSaHar2y5Qnc2Xa/ByvDYL/ELzdEIrD7TbXsgkmrMGK6sH07Uicriw5O2ns4+JdvlyqBiZkx3/Fc4NxdSZzKGESF2k8uXznxe5krPpr6CLdmYVyJ390K2GEhkB7Q5djRE6LGZI821Rr0KobpKdtWwL0ohYmtDAb0We/VdVzdZGK7gOPZbZrzqTYjk7vUyjoWrBHlyKVrQZAEUUpME9f2xbftMnpQZ5VhZ10IWmRXAQBFseQlYNiVQqyGJ3f/rGpRWZDv3ttn92lA8JA8rRs5hGaasUkqsfWGTcHCJGqRf6y3/JZNOvOpekYLwTZ+FxJ80RBIZhnsetHot2Z0WlCB4CimfLGymEGiXDxhHelHS7AuZA8liMQQqJP6+RjfCiStCcWZq1LDtCY9iz4TNFRdBNb2+vvDdWe+2VP3tE7BHYgy/ryvvdknIbwMvhvpSRrA4CEFJNOuhg6vvxMKZ3OFa4I20uAR5QsB84H0V03fJ9JBp8NBsY7O2by0ShoxD3Q+g2WbsIqIMppHx17wu0GlS+21GGbAzU2QCXABMV7JfjkjCTWlEtiHgvEvz7G5Jd11//BrEId9km1/aAm/BOPXhaVzlT7naNVmy4J21IE77dwdNJcQ6WqP0KdLzJ57t070GcCR/MAj45MyhFfKAT5Rr1v7lJnTxG5eHYoa59HyJPj4R/n5E8eioKpWAnFmBl2y2cJyv1WCEsErJNWjxJROyAheDevnNSzPiLYTOW6NFWyUuAFqI3xY+
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
