---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBvLG9hnuiEbgjstlZ9cESCVkp+tx3mQICXiSe2hLVGSMfsffTRtrZbaxgkr6rCSdPXbrurc6CDiBb0XuwpcbiKdhFM+iyViFKnv0JmtCU5Fm1LMA4OkdySrj1ilkMjeQhCIhYix03ZIQUCmn9rY97NzuZfVPBEdFUvzkS50uHoVllFlXc0Nh7E4bBJx6S+bM8JMIoXXVF1O/eBwUiVgEXMvdOMAglucu6UgtmhgvpzamHBTzaLv46jHgSjTCO9LnNG4stc5eo/5hI/G34IsQxjdA4D42lhqiIv+XuEzeKuRcS15Ws4wCUEJSdVseTwHepL8s+fG5pe9Q01tNzHArJfnE9bmYNbmYfrKezff4fSibIeOdtLiOBXSa+Xfhqru9FKcuqbkbTuHAiQStVuOIF4KVNn0fRRyky9lgyIGnY4Ty/RRmx6EWoOXBncGaYejeX406XVK3qNIOhSnhu3XrdrMIw5f8W6rNQhuKEKGd77l7+QnQIpgSHpPB2EmTWWsvrIXNqkzWraTBu1JM451TJb75G6dX/RsvpNVPiAJE/fHpHHLjwksikoJ2qIJZj4O/kB6N7DRM1/Nx5YbsekxRbK72QrWcaTSyw7QcvmeAxZP94FecgtJaTlkmLM+tjv7Yy7WCnSp/pp5FfIcR4y+oqlDTx6Gj06jOWLWGCbevTH+AdHwIhDoYySkKokeFKuTDi140zOU+a83y6Q
    root-user: AgA+K+MhvQNggVMhjyP+KbYYI0zI6Nzfbsvj7IRIdEcFt10QbLG2qnG2++yPc7Egyaw8nA4gnDqy9NH5r/zCcA/mBeTE4Tzf+lIy9ADNiNq4Obuok0n5hOfcOd0+a9LrhJZUUW8pMT9pOEw7gQFDWLTZLXEiIr1xK8Joo3YDH7cp/jju9eTRytjNUIlZBrWW/URtAeTqePp888VudK/b6c4OXboAS6XJnuZqBLp4pv6GJqCNNlqV2Q4RgoB7YU0lo7y3asQRs2vTusqCVg1DB+hNlnzyatPSeGOregcg+WIjd0FfR1kQ1UZQQr8IzY/H/1BGWoWER8A2MbV/eDd9LlH6oR7YblztaECJSriH7XAAphKos4OLqLMjy7rmJQV+453/ypCaaDmvi4VNXd2hEIJhbZP6scMErYSoV7HbTgOPW7tGBu5PS8U9iflbGX3SsVrEqJztYYr8Jb1HtMPGCtt9CKgx+SW4unwT6TKh8+S0+FFBHk5yQLn1NG2h7nckV+lP7WBUWRtHnrJ08iMfGgZ2OfZYH0x2CkayRg/j/0kT83+NMNm3OCK6aF5Pu0AM3M7Oc2qAeoJQ72LhZZA4zKn3yAUKB/FJ80UiG0UO6u0VDKkgtv/PEXDPSr98xUVbVcasrVvwTC672m1ZAzD3RnMaehTl+dX6lmQqaZDwEQ8PWJ4uGrlDfbYufwBE+YZ8psM4OTHOmpbTPNSP
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
