---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgA8capRuM3KnT1ALU8vWMezBzZZGzVfpDv1g43fuMWaEaHfmyysP/nOD4MemcJJNacQ274PtsnpO8ZurdN+GlBlAABkoA0ZMqA+tBIemU0TnQLnCFWj12RPpdwxnNsw3waBA1ezqyrEXYxYJYQbsKDthn2LajYwcDWr/dDvivkwjS14uX9ppq237vsk0sSRmzmfQDC+Wz/fxyms2XRoWpiV0iTfa3Cv433ldTp/Mr/Y1fGOEKn3Lct95kf9WUSYqXGjxyKmWKkzgMhIvcaPvzbPoOWjIEVkyAF9J+Q2H/0mCkUQeKjVmwWLpGvaZIzU3kDEvXU9scqdFgwBVBvS0d2WQfd04Nz5Y791jBanOGnGBigfq+8k2/zibJMGg/BSR7AjFqSoOFNR3G4kBEcpP1h8+sadsRbk/wVICMooFuqm/m/7iUZPEuIZb+bDKw17u7tHI2aiN3VG8x4CZbCTXkqBO0/H3Y0zL+MYrhMBu7sGyPZeIqK9U0F86oZSTB1efWtAY1KQYQlQwKeGXVJkVuz81FN/6Ts6B1ZnWy+rhcY2yUZMlQxo+nxT90PFGqMSrLPqv7sAljH1f53TUWmTPy32vac2Ad2ih+1WvKtMQIGdK5xY4/zuzFtH3cpS/HP5L5amLgC0NfxgWu86XILoS0MlQlW5jqrWBYn0BBg8Mo/aIiJ8USW3hE8I8PJ9hz8VpYWvC/EggHRaukAA2NczHYO6hrMPRDBpH47afDvK22eSBiZrQg5mFtMgH1GC8244ogpFnJ60UA6uSaDwOxdxnJZ16cp5GtfSzhQ9drKxx6080tytK7kTn17yhRteqIg6Mm4gyawj9nzuJ6WpXOu9Wnmnv59a
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
