---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCc+9q+goDvN8SsQCa8hhLIlJrEukvVaLzSKn0urh9QEvJWAT4uI+KG2cRz1r5okd9nKrFow7n8/7aulWWmlkH7No0AR6F9A+PyJaqqSVGkdJSNX7/+oYFzpicRfaiU7UVOv22l8LyN3/HlEunopBOeMKCHB8hI+X35/GcC/jogBH6J/il1GSkpFeASb4hWFzRQ85xTs1pwyRP5kAMEQxsNZ3SUs1B8BMxCo0TjdJsS3Clsv8VlaP4PQhl4AIsnJY+n5x1C3YBGkHlvgj80A6UwL632E+dJ1muMcZ2jWcb+L338UdvNflanXFTD/RPhrMSdeDgTBd2KcRD9pWb85XHyb54WD7GvjDZhCwdme6Vjgk0I4ywiNO7HLyjmZYEL/WHbw+vrxaNU9gCDhMyTI6BgsKUhYzpmsoC8zg6tQyYh5a9feRL5WVKqKBKX41QUdYI9Aj83rBTPeZrl60i64vUlOwwOMRDz5LJagAbulHNXL69jA0zaX+EaufOnmWDdg+i8H/87gxT50i0Aq2NBDFzGz67Hfrsh0BSTYD9Ihk4qYPcpsMd9g9O3Pdg6DiTIfPxwEpa1hdn/AYUXw8Dv7+4sLd9aOSeRcj8kvBuha4aRQ0rjPiIjXfXJM+ta7cCjPiUhda4Guv6z2l/+9fmqIvcVpDAeIWDpQhEPn+TafQox8fYU2kW8eDGtqy3xrnEAi1D8/2elxQO2/jRE7ol6n6PxbbUoP4oyIP8cEanWmyP1DYmUGvisFvymxunYiewJ0N+pmbjIV+n3jzNQaWg9YlkC2bV9GnIX0X4qL9kRa2R5ViuCT+OCyClbYbyFE2Kr8ECFOTOaiTbYtctI7OacEpTbwnNv
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
