---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgA9N3/Hii7VRZT59oriJQwD0F7BmYqOW80aR15Jcu/ruB3d4HdsoHOR1Z9KKd7FalSU1POyl1ifKo2YCoejLCmmUgG5oCYlZWKkyQKZs5sfY5GII955uNqLGjzpDTnx6TTxFxZWJjYLicH7BmuimibYKGI4VWJnQIj1hf1ZvbiaOkJmCo13j8YhR6B3lSouNeNtrdX6NCBbRhHeKA6VIYMt7GVwiJUcFnLaDIM1HoW0xBnSfZsaGFvX4PyACTyprIFAkKOv/ACGXC3oC0vdFVRJ+fJYUT+ojG78E9wlAo6VLkC0ZsxZoguhqChdeP1MfvkdSoW1rn/j/OyhjUgl9rDjWGfjDRqcla5l/E7JIMFlaqjlAlS1PWuzQfvC/7cMw5Jauf6xmtTwyBG+bnz61KkEUgiwaQ9Gg4AEKvgX7MBGDklc1VAvwr26OaqR7j8Xfu6Bu+fg1m+OP46QO8lt6/FbOehlnOrZQh/ZWYDqrH9gdsd4+bREoSG8peu0aaXDjikrWKsdPeidPEYlBkiz8QEYXiQUvonFT/c3Bk42bTx35X+P8BBdepvOCxf63wkGnj61WzQs0AkZUhYpLcBtYORmma6H19THUqpUKqvneB2YBjS5hD1211wo3NXAMKR7cxvRt7b28YBXT4josVVeVAdfbvbF+hWPK4cD57nCOXVAdeNBkvpL+kZQB8AUarXR5D4sIlm9BPeZKZsS+bI0azJXEBbusJsOTj+VkqEOHMwz5xNjunTLAcZZRRQbjZcwo/G7JSjt/2IoJ4F2+GJNChiZcZMOLRnESf3bHzTF15mwFxZ5tivM7E39qnLoJQ5g8lyqoxGz+vk7FJwIBWDWR62ZRCYB
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
