---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgDOPUiVBO7FD++6l6NeCgtlfmzqHmK/k40bY8GFD2pBQC/soKOQJ+8WiP5+LoM0RlsOaI1snWgmYWxj2p8xm1f+dKFJLYSRES72neGEtOUmoxYBOWzeERj1eckeRSgNKvz9XCXV+A5F9QESJdSjthptXi2SJuMGWgnF1wsUmXCtp1t3WT3Qw0PrNaTHo+g5xzukJzUawMOxkBCmSQtY8adWXmYjj1YuSe3g0Ti3Yjepu8GjELN3cuAK3bsShIUtaOxhVtnObE8Nr56/03NRriYKt08Py7SHSH9Fdfj2ucO1sJC+WSnM07hRxWRH1LR3HPPggjON8sW3eObeG1Q+28uiX5F0C1Zz56gOK4eNmU8pLYqYTrVVscGPmlS9vzmjuVq5Jjyvay307xwxw0tFNtfsMjHTtXejaj61hBaqbtrGK+pXnbJ3l8zNl9CZdjBtZyMWW7l1Rc4q5roS1uVG19TB8wISfDMxyCMj0EM7SXYInEJxckyfpWNdfwb2WA9gOzxNw8E3ZaHfn6YIu5yIyXmhaGT7GmwdzndxUsPCFwn5G9iezuclWGW/YyWUFvRzstY/Lw003x6jtV7L5o2Em1Qto2xQmYVz8xtzlBhm7nyqzeC5ePyoAc+mTK9gcds0JpJhcPQ+9NLlM85Try/9mLS6Vqnv9I9XyRKcupf2d+gcX+zW+GEegWe3DAu8Clse+RHgUw67kh2Hl6ZNSpFtAx5H5l1fZeEiPgjJrDVMeBfaYgISw+9l/zCt21An4i6ph6BZnWkVb6Gz9Qnhez2AMqEHf4H59rYW831Pj8HsVS2ndwVk2SxZM3GrQFkQHGYgtWHw7RAuUxIq+dYGIueTkaL5g9/E
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
