---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgChgeDZRkS16gVtSEegEoB08KbZXPo3pKYuxTpruR1Bres6vVeUSfEHH9dVJgT2eGWN1XnBjzGB63OwNwsmiTlbpoyDTHFHbEn4q9t8ZRvcT8Ht5wcsC0rzNCUFBWfmqVzvMHsSzKoAzf9yZr4uBoyhllc+xADZuTgjHwH+GiDEMS3Txmi1n9tAPbPE/dtIoVTRhID1ystoceW+kXIay8ZaBAZZXche7pwu9Ny4qAZP43NGcLzSxySIEgu8ttKxtkdtcBzcj+yUT1mDC6l9MNOyKPeXKYmaqQSs+doTuvAvWto5O1/oT6/4wJ/eutCAdsU8DDXFzko8NI/olelVWTGKNBiV0WeFGAu2fxkyQHQg4ouqUSxsbhvIGAaykfnjp/Hyy6H83aHj4qulP+OIp/Ev+CUpm7WTTYaZBJALJvIEN8tUAMfxDF219bi7PeF5P7WOnq++DM+Dpkz/er2LOwotYFJyveLdC8vWJyBKWYetSW7gG/NZiBI5ByAH9lVMXf/SFBb8RzqBB/Ds+/3B2Oiz7ffqwGb4BuybQ0sKXct1kaIQ7lqd0dmkuyPuKkfFA5hFbHguO4ML4YMyRzgISaQGHov0GZsMWrM/DDGoTt9kYVsb2ZufsFVdOEnSkyZ5UJMPAamfkAa2aYO6rKE1kva/aE2Ymg4/7LRUROOVvhurh59jaCDDl7PQLiLX8Dnm9muXZtebmnYQr8bKeIsCPUI396KNZ3Z9NzWC9AW1QK0EEjay572OnUCOAG1e8EULN3jvsBV5BFQ2+naR8+uyBK9LrS07jn2hmphDAVxqk7K+qd75lIPeNlVkGOPu1S1TBHz8Hw0QSrfi5vAf0GfkfjH2wF7m
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
