---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBP9h1oT+PnypBHgnr0pu0iBED8MpdNEJ+I29LaUvebwSY/+H9/bAwEuBxG3ZnNrssbWs57vbqVUJXzBgspBsghH670DKYPQWOcrpas6YmiMWbmIL1lg13dMZX8QZPUhY44CGo//R/JCLzm9Bs7brOyICcBO7e7UODF2i57zXaslVjnO3EuvoeOQhcRStn053yg4s+1h48ZDI8KdwiHfkGBQzQIb9244r1ANa92GKh/0DFzXHP18wvLJkOGYyG4tUBuftJx1H+n8FTzoH6f72QbtavZX/aGx45q9tmBwC7xGgnm0EmKFDJWvu4TMb4eTiuBjkufBdVNxvce9WRP9JytTbX0SFXF0O95m9d90hZxhC/4A39p9CBxzCd3RMKZcUwG1JOyaoezPBQ5SBQolpHDxsXXcR0mvAEQbptQm0yJKOtnG0tE757aSETAtuUfaa61VeF9mRRiWRxVt9PmCeVKtULL84yHs4IGKVOwCwUWSaDWpN7lLSuHMR0hN7ucYXrFh29q9C0onjgaQYXrPWHrSIeG9Ijg14tu6Tqctj/CabZMLyG21NQFPZRQmnP6+TLbrWf1R0VNpgTfs0YSitD8JEP2j6vfUgle5ecgYlDoBhRB1LDqNV9pcJAhA4zMMwVg3E2DalYcOeA96gvyi2DG/mcI2fC5BD2dtwaJkvk+10Pfl1M0Ewu2RbKITLwHhrkpMwUqREfQA34o
    root-user: AgCd9A3D2EIYzyMKxx4jGZxDtrXnbm0UCJ3O3BuprBwOI/grAQrVD/TnWvJbh1WIYc2k6DND4cgfGqX4m97u8iyoLTAnn6P8egU3QHKnNxWTqbwDxjy2OVGUBdwytGmOkVLFMpTv/i/fYQtBfD49+/dTjsPOWip83cTCI1fGFVtgNq5fwZnTOp9soTTNQsOYFZRCByGJeQznCJq0JKy8HSaxe/xdNqEcQpT6xTfUXMhcYiWL+FrZUyqzOConKw0QMepdh+SwhhuIPhcHvadeBfsdfil/QxNY+cxpgm9klwCTxvikVasYw2GMSZDPBsmMRwzUE4x3Nfk5g2y2UbR7aDs7vyc7SoOMyZIOqfj5qTsYlYDlIqyXlC5eHffCeQLwBylNlKVlW0yvbwMFuODGQawUZkY/pjy/k0WrtzIgQcQRZM0bmrodb1/KNwMsEmyPRGIlANMbveZ2wlKC1MJpIqiWGMtX0oZweLY2FT/mhgen1pb8AGfx5wnfXE3xfb62PmRDNBpXcorBa7aQ4AE9QsALsHYLbYrEH6rkav2ArssJFcb8IlUP9unSvA0OnG9/B4fLjDiMk29DKlE/UWmAsknh+WZjjgSlPylQxQ0ozFXMKxNAfnPgNmOuNO6Q1fmgt15OuY7fI41a+Wd+jbvgaF+8khDM3Gev6yq85gvkirZ6FLMNuHO2A2XypY3/eSdEMRGW0r0DSmKlytl9
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
