---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCm+95ZI0NyJ96bYNMMeZ7VWx8PZx2dgy8F5rcRwao6eCsWY5KXpAtKmzb6/0hsC7PbnQAcKMCKxetziRIyYQO/vMK1zfHeNH+x4u6yl+boLBz8kk9WMpz4Z5rSzbpOe3oW5eczAltUpmINWTkjojADkfSxtVqn8kvYxSiPaoZe5zeFjcxJ8g33x25RDyDTiqX8kMUfzmGJQE9iKdHZT5+zvSCKYMftvDYX+Oo9QsMxcIjQZpAP2huv6r1rUMSJ5oyGPRA/AbG4TiV/4Tfhz2VtF/qL8yrYX0oJQpr4s24YMu+7PVXSKgFH2IKE3fAe+8WdApEsAUybbFPs+YL2+h/euvOVcn+vxUH9+9brzG1wYDIKG0juGiBsi15BbrCcYphloEMLZEzl1ofVwzhw9PTMhSSCsZb/4vpfu/m/P21bj5M+9rNvdPxjK2xxWW2dVSiJ1x0CsE6msqvuHzQywciyvHx2uL+vD7NwYTrFr5qRuC74PzB/d0Y7u0jcYvo7GYE/FoOdsIpD1UH6avCOd3RqPtEKry47s/pyxkfdhzE7XX/KKv0T+IUG72s7p9d/gUa3XZShI9K0aItv6wTmptOzKOQqidNP4L+O5u1n1o0qUGWN7QUf87J9jFhh4Xc5+lLevu4qXBcsU404H6oaau3CY7NgVfPbNSadtFsksAp9USLbc52XC6GAEouHqY9U04dbwEIMJa47ccRi8rHHcGi14DjTjttr1iR/N5mCyvIpykJx5txu3yHmsKBoLgWQNnFSqCu4ZbWUC8afccX2g9Y/zPfUDaf1mqqY8C/VRXVLqXrdWr5cM+tb8PimWK3C+5gYJ3g5MblKRv8mM/dUnmBHL5ng
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
