---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgATV+z0JqKI5YZkvO7jqeE7IBNE7yuowwpHoXdn0VkFmJXDpFVXhOSsMm8SosZiYZT+rF9fs4kQtFOA/zuHhI36J+TelnSAGD/4qMBB2Dyc8ArWBHqBv/i8ZXFWF2bmEsSBqtCsGGA8bXdrMnAWVG7JC+DqJFp2HWX7zZddRNl33MFS8zisJ5uabs7AX/TbmNK6l83G16D6KaUJLBXTh6JC/HsxegI5pMeA3P6ULN7lhiBLlcfJWqfZtdT0mABdA8dm9LS5yQwwCDZRfmQk+gktx/5Q3WBDuhWPOEiHVS1LljFC1Rqi1U8Cqt8oz4nJsIfTvyoJ4Gzd2O01RmE+tMzIIalLxViyHSEO73U4VAWgYPdV2dAvGSM2k3SdFYIk/Y1J3TLp10yZwSKPAP9+QBU1lYbcBBSk8oPi0W7C0OlxJhs+7rEDXg38qnQD4ouowPT3RQuuhCmdN+8XkyDPcZS37EEHk6a4mSGQet91riDfPMs0hqOQTn/gx7Pw7gOlVucod5PMeAyxFKkWy4oSbmVSXXQyeqwE2mmhOzTd5ppYe3amiqzrVWEJq0aQXKZS1Fz3FipwokszJZ01in2Ebi200YaPk+ZlZ9Lh+TomypKnldCdirG1xmxyu8eR4bDdqmweQUP6Vcqo2uuUOKypiY01Wvr/z/5EWw3s0Ghx78DFDCjtndVz8k4yUopaCC/ZtPbKpnzKhLiuWX93
    root-user: AgDgZnyBSQ3KQxNIlrcs/jrwFqghe8cbOg9eNnKFN78f7OaIxkuao/2sFl0mZAgTOd1gwLo9rSyzheF1f7BkD1CKjCInZNKXm9WNvCtrd7K2WhNos1TUE5Qo1r6gXX7FQCacAm+MKBzp0Qkk8vfcnDPsN6QSQ9POOrSvB3LEmhBdYN0OYZZOQTiQg8hkjINJF6erYV/KpsPlkFyVbiwCt6Mjmz5kPmg25gVE6VtXIoGx7i05y3r+FpXWjdd7jyjSNe6SffBifb8SF6wXbMmXUAtsHWoWFidF1dYLoLzm+P8D8lBtESi4Bl7uP4nv8AphRd2BVQDR2O//xkICyQZDjvn0U+BGcjp8nwt81PRQHP1D81x88a04h0RmHrdxQbfKeMOwAIZxT1kHOQ3FFWRTkUS/Hjq1xUIhcQJCxd8nT//emOw5S6UGDnrvmYOt3HAmhnolbb5Z42TRTuQvQwFTkoJJtR2iMY9WK2+ky6L0uI6tunHS+YBbgtzTLn3nUmP9DIhRHLt4ScRGq/jqGV3DdzZQbsmsuXAKz3vxhLd25L+nKCszAbOMOsU06HxfT0/mZWeYJVvXWXjzo3iptcRMJK5oiUZpLCoJuwLOlytvVNV0qc2Cid5OYKUUaheFLLwkp2UUAXBid5SSNqqgl8hYwvKFofPlM3mQjJcnUPWMPybrbR3PDeKU9eAFvQu5OsVk7W0ks5OvVPnwaLGH
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
