---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBbPMsFvowTVf96zWSFg35bVqDyxBwtorldyKwoLhnu1ijI2FBrpk7Iv+Z9UOZbaLYhN4U0ftNmeNne+liM5mz1mHF8hKAhce56/jJJ8mVIdsnBMLqIOHZ8rk1oCaMFf+dIO4XHwYFmC73fEYhKgFQNu5zTaV0OUJaP3WOu/F/5iFJstKAdf3NWTuLNmwH2JYi353qgbaw7jUn9sy7iezdsqfdv+80CkYKh1/UHmHiYg4Z7F4FzI/J2S6EUpYqeQ3pT3MO3kb7f4KcVGiuSdKB3he/jRFokJdJRwTPjHnJM9Euc+8Wg954ZAeT7f1341puIRBqaOGxVrtQoO/pUUU3DhP7YZGhWHu2lHi24aRyCilqeGvTobSlXiTy4rMOavSr4/cIfrCTAUoKa5HzLzlEcvk/fX3mB6nX1Zf4RNTajhXMAIKx/B4iVbtcOxaxUnKRIxOSyLWEZ3/dwp+8NcRmD43fuQatbQcIw8U53+VEzK04og3Y+IEmLPATyt3WotbQPoPVAapzxucyhhh07pwMpKHYuSbjRF8zT2J53aYbPImtjlra7phH24m9Zw0FYRsy8hRwMHBjZH+WB5EzWiQtBcGGMyowgW09iwI748e6Gd8aP08y8nNjDVb0qIHn9qNPmghl2r0LITGhyWYpBOhS3rGWzLnuuc7oP0nNtSJMWJqtoQzmMYzz6vqeP+Z+Nf3TzdWbw+QIMPoju
    root-user: AgBZ7MSNug/amzTHOf72v0K3UxeIvIfPMtCmr0U2RjnmmNY4vPfYCDkxiIPcvEJlNnFskpKhAgpWxgktRQQsLtcEzodhFawy3Sbnz/JIgLXQY3m3g9PmDAycJRHbyGRtjEEz5YnqvHDdqbWJRp6T6raZ8YkH8o2Wyp9Y+HlwNsbi/AN48THBx9r33bL9JNGRSTMXarQzLNZUZPZ357SWS4qU5+mBzV6vXrAYxX+fYbtBCcp6Og4ykFNV+GWwHl+BtQSJ6EGu6VilE/+s9EDQc8ukglyOH5Zosd7aj/hRiiqBIm6CV+M3GVook6/Nim5Qy4fNxsIK8r6dsq+drLUSzpLYLV+MXs86bsX/TEyAoq7pBcniJ+GXW3ZfU1/2Zbdn/AhIIx99X5eLV+33RGVqH1nWjo4aDdfclGgHg6/0HUmkZqUJczYAVV+WzJIc1cSCO4DLgzpK1FnkSkBBqOcvkbLDmalAkk52/4NzgwsrlhGRqPpYFAnxzS1x9L1E+kGpNInBVISbwHhoZWACksI7VbZjhzxBNBPwGz0ZiZbB/A3tA7IywH3MfXxXmFlsam9Dl8wYN+S7xWIQDjD/9mOC0mLWlTn5LS1KUe8HgehG/PouvBoanPTWf3rG1OK8+pMYgzrhvHRtsjPDlODOWO0UOcPhB8PDZwNzqAP7q5Rila+84zd2EkHHkknugKXcZr65p6kmhZUoL2AGcEsA
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
