---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgAmrVkCOJooUeFuhOU4mV6qvS7i0tG2V4NUCpt+LHb/YhkJCMFjt8XkUeExTXedjd+gSR8RGcnvbua4exE8sop+FnUZeQy1PQ3iQNoHX0ehgzcnUZF9oVDDvqdutBXCGxMsh5kL076AeUoqIu0hRyHRIX+e+JTYH630QCK/j/op4NdBbaFycTRPRlQI7b8bqjYYdyT0Q5os50p3srodIvsS5SrE68nck0wWL2A/e3O8cWiITgksgIdRGkLfyj/luV0c0uwzUlmuB1LY63Y/l3sb2hMFhwNJiJHbe92enfSQpqaxRRrv1FlhIzJKLe5I33hd+MPidZR9jhzGCWBQaNg+3GBD864JddiunVdjq+FQD76QHCom0KOqFDsam6ItXNzfCHZQWx5wveKlD31mStkOJOrenV2PQeb5ubFrUS6POhOWFNF/s8hygne62+5LEUqu/Fp9x3gsCiz9Db6B1Km2TRD0ewrNApAmzjkWy5L3T4CB0XxDFRVETZvEx+gRtbcg9OGRcNKJ7jhi1y6lgkxgSwaCscRHJVvDYSeY8xzZrnOjfKecANJItkeIoEEkFYij0uB/2RdW5Lw1lfdjqEXgr7T8FEDpLF9Pl/PnZ7CftXFd4JpdkccDuRh5opSrdR82GY/YVxUJzPb317rlo+KfQgcday9c8hpQShsKtuSG7AcGxpe35tHuG8jB9QErOjAsEKPjVep5V3g7
    root-user: AgCoLrMMXcw8Gt9DEnjQwFyow/sbRoQt9hpmVOV7G05npySml6CLFwtVpzsWTn8GQaHSePfxJpYakmF4ycKTLVFdc+lnSTt+76NMq/+bA3dZfeDyW8CEjpjWfjGJ7P55cMzci/Z6BnlChpsX5aLnt7DwhRHtBu51zCYzwwOQWbnY543MthycO/CnKDH8tZOU5WDu76iPKYugOXKbSAGcJEDgnvb9fPchrR9Hi5gctrYxa7J6Vye9tIGfYgiPvYnmbhMKn9S5+yYzave2YBStf0D7vJlbK3FqikUtXQ4zLIIzF1HOkaknHdS5j8XXLIhJJXAx/DvqK84igpAoa1pCzvquj8DooShaLHzOoiWFsvgv/XZQkSK1POpSqIEQrQoe0HIPxoBlGG1aOlMJftr9Qa4hXrWmbfxTwmtDyTG25TVD4GiN/2gBxsS4pmaQpEp3e823mo4iqC8c8ec6oqLCcNaN/tv+doLdvO8YdwLyshWo5MqSTTqHqxGKvVoYpp/NpWfmbfBpFllWUxOeVc/g1N8JXRLifh5Ayn/Azl9ko57VKZg/pNAr9hWUPZTKTRQaAMIJLrn7deFmp8gV0Gy8HixV/4WtdHNDSl2WhneNB2Uod1JeZrbOdwzDgndR2sL8yNnn56/OSDOBdz9WMJnNNKuJKONOvtbaiVsF66Sq8q6Kz0/As1qBJnlItN5vLXaEMcX/pqh5SbmUF+eE
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
