---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCR592m0JJ2TbazMbXfQjdIu+58QWwzjQoyaGd/gd2QiD/vjdAw4TxvON0sPNhZQw1KTn+p3d1pflqtNDyFMaXY0dIv494UiOLC7ABwPIdlcd7UdCfyi6ENAmz9dy5oHPyi8wzLnxd8QhyQoQZ/02oEQ6XIGeKo9Nz2TLPFToRd5ryjwMyLb9x0JOmlJtu/AKWb3m2U6l2k9q9RsombLV6T/vl9cxZrYknCplZ7ueikkiU44m+VJJXmll/4Z4IkXQf4Jj+kM3qThzMRgBNruf1PsTZ7Q+eIk6Zbiz4QKYgjXJyF+RgamcndkfAv6NnXqumUZAoqJ7LKjtgybPH5WVo0/XJL6tgKNqoj2a2v5HpJ0JsizQo9Ow02DGjT+hxnF3Cj1aG+YqT78a9FUvGHi16A6IYI86GTA8dlJhwsGrY/K/3Y7TU4CU3IHghcPDf4HguNFFfDNgZGDE+7ZIbXq+2eElX4iNGWF58FavXybRQhm1XQ6mz3LP6pvJE5m8bEJXibi1byCjS9G+eNixGXS44QXsHtmP0ON36uDNlGWP6WchLCQAf1LJM/536idsEoPRV1KBncZJsXJlOjGbbO/dsqnFkk+oixdOnhFaGvZm0DHqx+prqn9ffBOT20WzH5pmIV/kG9KVh4P4U+2NUSsAjVFiy8p8ikHCIgbDF3v1l5eXHpKq7KIUya/E0zph82vmvkQ7sEpQO+uLj6
    root-user: AgB6IEFm2ASHYk7LT5MQ1YD9XtYIDtFe2CAIFKS2DvHY2cCfFSAtKq2nrylgMuoIxeiAIMGETffVAXcBaJUtWd75JFVcYGmUWBINqoQMiHl+Xpfi7i64QJgQEA861ek+omSoJaB5zwTA7gIi3w5xqXeRbLmdQuKmpuRJ8n5t00XL/lLWH/2AAgesQsXE1x28IX627SJyS4z7tfsv8FwEqNBVdk7N7cHBFRyXQijiiEVIC4g6UAeFsR+FhNuhpavKzyh8/pPdWzHFKnqr4rTYQ15Qlqssi3MMaRtrhN0x+LyG6LUi9mrj+WX+63837AmxhuyrSc2z9txb3rGrifZYEmpqGB+dHYw5qX4r8jyhU6HuplUlLB3VvXSTdl9pggkFihpz5JgajSLEAAO8/j5THelYZR3xEPTv3XfIaH0dOkxylvvFTASxiU0EUw2QmT87xmBwbnIXgFXLf5gQXxYhqbm+pWWptltolRfIQsFxF50dvDOFta7Rgw1CUpCHriwBs5WF/6Mj3eYIBSaG+mpRGqM/GCdw7VfLH1+p29v9znF/Vq/qoRL7bM32zDcMi88XuYpJ5vmSlDB2BFvddU8zRKaJALTNkx8GVo80ThhIhhX8oBRYWku/JsPZPybEiiDcO/bhE/8467o34QyF8GPn5qdGV6lqVm2ElwYTsNiDkqclKEl8kpbkHuw5sS0a7XQzXM1OM4WLjrwH5jFO
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
