---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgB+4kDwrC5KHps9OI386TAi3UJ8vvk3GNdA/Uz59rkpPGaKJqs47cx+fKoMXQnEoAObounEqBr2kNn1EHLpG8EgIu5Ehy8UPZqIdzPN7quWsPLdDeXynzHnhjrgcdfuW9w7CZ4EktW/oc3856Tfj83oJmpBDprvH5Q4YQYysx1nnYIsYpeTCge2NCc0KERLOLRAUURXD2lyuhSeGvppuGjB0mWeM9z/yrcORQPZQweas37WUsryjoLgLeR049Ajc3ORmlh5q5EtgGKhXNpkCn/st0Cml22lVsNz0vZdZY7CTijagmcxaVFmgT63OK4/3PSJ8CdXYiNUSpMmqPlCzr/oa2VByPO9EQfWrD/OtCwwuNVxCFf/hBAmqazVPV7KVstK62DeJu2VFKEeWFoa28hPEOWInqU/HdovEWl9NEDWw3naPB3PwGkSKxg9xQ46gvHxyRHH5Z5ynP+PJ5yNUTXqJCGvLYmKf6gqpkjrIeAc8vCcFwKRAjP/qFkp8YYWNLUmJ9FkAb8N+DRaHaXBNKkHYrLBe13szKIVY+yC4eiD5ZmsQjuGCN7naYwas57cHibdT1+sXiJI/kgUpAyxJ1sMulc8ZHXYbHp6raxzlSglDVorhUXuyR/tcV171IAT8FfEnTdX+CSqBfdNY4Yicya5Qx8HajuhR1EfjWm53QE7a2/TFKbkr3MeXPx1h76ITcUMTF7GY3QC4cDBR+C3o1TsR0BkO+GLog47/ZQAGBmocBlnMzCYA6FP4Pns58a7TALFsCbmLQPJaZ+UjObiX2QSrR+Nzi2LxBrt0nLYwDWKUQAtHNnyaXsMy+QDbg9aJz7S7tbUS7+mHZPfIg8/peNIDWgx
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
