---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCd5MAbH04X7P89vV1u6l6iDEfoFUcPmavzM6Lum05bgzaYZ1/zqDcrcanUjh+siec86gCTj1dlAkqj2ur6Dc+mviaP8jNHTiwvC2eIN6pQY5NjrNOlz+3wNgi6T6Bn3AB92mZlppLimKkL4U9GJuXGLRWc6Ffxy2BAlwNWrijvv2muajqEpwkgv06n3sPyhFYuO9ew99XqUd96NVhkBC2fJR4vu7uEiZjgImC4WYVlqlrBLu6E7QtDUfm6tpSYNHglFOY8lc4UNShSVylM3a3/SWh99g0uxhcp9LNdmjyi0UB9e5CtU/W9OCup6Uzlmnm9s7RQk8iizLF4YZqkSmVPt3GBLeeUhSV/Oe1+0y5gBX2UDJ1gCwvM1XqFPEnwWOpiplF7hG7FqYiugd/6rsm+bs9EeAGvNeLq+pB6KWjOklggp2R6l6er+ct9iEDxNVDrRuc3fG3JNPHvyH9VK4QbmE8CuLM63tKA+v11HK/vLbm0YSrva1gyviG75/IZvKraKBKFjxkEtDmpYDx6d1GPMVXnzxtP78stOPcHGGH7k3RrzmQt8S31eMGRbwHDHEl3X4YIOObNKQeMuxSHAWiap59lIfXMZRkOfLmuBkiN0KkLWpEfdJTGXXbFZv0KrnKSja52Pb6GU16wtuo7v81Tvc92aYjyf15b1nRznTAepfbKFFZEmkh0WJjsow1enjP5hNfFU/LMpBSFH9z531ELM1TyaAR76lw8nZI4NRVBasekjAdv0HLUaFjtEsh9Xm0Fd2y+OhNAlCba/PVM0WIODvUWwaihi6n3vonI6TM6ZnhteLuSeqyEEG1sYu0i7oSFbkQnBJdLeHbn8QKK3huQ9W/g
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
