apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: dev
                  url: https://kubernetes.default.svc
          - list:
              elements:
                - appName: grafana-alloy
                  syncWave: "0"
                  namespace: grafana-alloy
  template:
    metadata:
      name: "{{cluster}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: core
      source:
        repoURL: https://github.com/devops-toys/devops-toys.git
        targetRevision: dev
        path: "charts/{{appName}}"
        helm:
          releaseName: "{{appName}}"
          valueFiles:
            - "values.yaml"
            - "../../values/{{cluster}}/{{appName}}/values.yaml"
      destination:
        server: "{{url}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true