[tool.semantic_release]
version_variables = [
  "app/devops-app.yaml:targetRevision: '{version}'",
  "applicationsets/argo-cd.yaml:revision: '{version}'",
  "applicationsets/argo-events.yaml:revision: '{version}'",
  "applicationsets/argo-workflows.yaml:revision: '{version}'",
  "applicationsets/cert-manager.yaml:revision: '{version}'",
  "applicationsets/cloudflare-tunnel.yaml:revision: '{version}'",
  "applicationsets/cloudnative-pg.yaml:revision: '{version}'",
  "applicationsets/external-dns.yaml:revision: '{version}'",
  "applicationsets/grafana-agent.yaml:revision: '{version}'",
  "applicationsets/grafana-alloy.yaml:revision: '{version}'",
  "applicationsets/ingress-nginx.yaml:revision: '{version}'",
  "applicationsets/minio.yaml:revision: '{version}'",
  "applicationsets/prometheus-operator-crds.yaml:revision: '{version}'",
  "applicationsets/sealed-secrets.yaml:revision: '{version}'"
]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false

[tool.semantic_release.branches."2.x.x"]
update_version_file = true
match = "dev"
prerelease = true
prerelease_token = "rc"