---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgAICVDDWYFsilUQD9QhCavFy0p6/wKDidH3iYITfHAiAy9bBEGgs1+eQlAajmYKz58gY80eIr1+uQvTKcwE06eplHoOmsvxluP756tZZumd0LoEVR4F/3jKZkYQmL1e5ZskPdlZBPyIzW7xB03Z1kPmzYsEO+ldhWtvW5oAwxxzSQPaReVKYnX+QhB49LaShdzMmJ8NsNbCLNC4e9XmffGj4KFkhBOqAoAgFa+ZT82ePSDlPShhizIh0PGtmhDpjZC33J5Pwqidy+RfFpQYnWt+pVBk3Nve+I1ykZSli9Q0ASIKT2BwCnzQrDyv0cWtasBZF/4Z2t+9J593AV8askYpGvch0BXaMATg8olU3if/Cx5b65EGZgz3rOzUkWNI0hLJm48zvwY3Y3x//jx4HkCQpHoXyAyxpGhVWku18x03I++iLWIJV5BHXVH6v3BopYaYc+afbJmVaWA+W8xbak6VHghShEsQfslKvkWRFAPY0gDhl7R6UE73P3GHKVZex78b6SSH6VB6FxBP/t5Mr1cFpMuvxFha94Nuz9DaSQGGwtnm/RU13qFyNFqEHV6QBdE9SB+N2Wh2pwYPZgxTO+GLGof207Fnm8R3LmqW8j3tGiN6hBHoCuuZ8Q6dGIf8hvsCSwL8M7bg5NCNDT9YXYeVf2niuCv7NlUfiu2q7qrNnXcwtsAAM/b9+sKVltV8O9xmR1LmF01ouU6sv7kXadYzkd4=
    client-secret: AgCzn7UU9OsE3aMKBnt5pSuKUsofZt//B7kZX4TD6NSuELnTgt1xKrRnurDhPoku8qNHmixcJPKnG1emW60nSFrnvnBtERb7T1VvieDieaw2ytBmM54rNXeFgZwnfi8m/GjfGI6CyPjghI8Z0wARd+iyrJ7mUn0WcmfoBTHhjZw7dTt3Wv2XknLb7dKsS9NNA/wouD7Wb3dmRs3g++AB7GK/68yMgRIMeEuFWDDKg8cRF2Oay90CG2/4T0NAtqJSp6hJlHPkNkRNLUv66WNMPr0wbIFv5bjunpLbxJHCSMG18PO95SBaHw0kuVmoI6Kpeuh1tMpj+QPr5fVEpiS+5cEYH2z1g4sI9t2oZUwOsXvVBjt+GCgjQ4mct1OeSb0lOqiwVxUwMhYugcfF8nvTCnYxDcRNaBE0Nd1KjiSLCiYLHcm00XkClmG7KAQic8t7MeapPMDDxA00SMzXgruz0x7wikscHxYDEuuqNmHLEDjyrdFEUyrjsjc7pkm9fcFqYENHgxzkTSdQ3iwM4INMfNK14GVA65E9LbHlSbx10GgAmoQZIME21YAziwR+tbC+Nk82pyarVkIdqHNBaqs4XoBXTqFdfu+px7MNbqyONEUdrW1l4elU1GzIieBnuVVOeZhr95cEaD3saLMVAO3xkZ73L3HEjq87OwMjgon2JM4E/4AWfREogcD+ZT7k7pynJJoLurdQdzqjaX7IujqOLqOQNBlL1r4zW54=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
