---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgAkdQtb1UqSP+oXHOUmFikUV34kOs/ON1MkfAEa5ZTojHOyHLIRPvQJ4xg325520qU4mn6bY45FNX3NEcEa8rp6dEIEy8AwbKHm2skQOwPwjvFB9v1nvzE3AhbR5xTXopKiHyR7scV6NX2Rc3ZqYG+0+jZcjXjbgtLQOni3TPkC87ypl20cH+kajjyVto6QEvSPmSPXS6hfXtK5KjAvc/YYKwUUg5N108cUURWBbAJFFYi49bFpAUe8749d+wlPIQe4booq1f/Kum8E9+sjJlWEZp+HtbUsAEQjpI5EncHRkHbIwX786NEcVJ6Vb7t8f4IBc2S6muDCqJT3U49bGSQIdnYj530cFHZJVJeosF/YBmBr2lkNFSADN7SxZy+nJg62VC9tFFpohW8J8cBzG+L6GiVec3jNKX/xqELfI16xSS0vPEqEQPhgd8RjIxH8Vd6n3AXlaEKQxA4m23XDssoO25hU6QXuvWsP15mFpgRmMDiP0TRAQ4m0OhRlxWaP63WX3/xv8dBh902f/pIJplRaaEG30HWwWzSwaV/B4bJl3heUqj2c9DyfMb5lYXALnKqy6o9hXyJpDQE+NJHMBaA883kwqz4HcfN1MPYSc9AGCQgQGw9EdLyXeMIbPXhYqZ/lka9Bz46EaBZPt9v3DCUYnyFW1TFOjR9OcuwmdRomYEygEQoOyLhh7bYDFbyCeYKoZVK5MM/1cCQ=
    secretkey: AgA50axz1qjm/FkHToywG1LRJvVyYC+wx4y55jM5irfW/y1JqT0FlFNtYFZVwK3ekFdpUCKpgJFD2NEZD/azenEz2qGiF/VrTaTa+WOs9KAaVNf/HkVrLytiMIRT6H18lhmN5MhwJ5whi06G5XRBFK7cJ2ZKNOVaNIYJ3wx13qAVGDt4E97BpmM3UTDEC1nh7lEtg4LAkxsxYRmwmXmN0OqbCnuI5+e0u1ki3I8fkhdvvikj02GyNSRVD698e7zOMBzu7xzSVqTE6uJsUI8IY5/w9Dj/5wdRmSgcahmBm8Zp3UjAV3s35IjQ4dWfZRvEI7Zs6X80xeoy3vNFZBiVyxrWjzTOPK3BcKEbwb9o+j6TABFKOZLjboGo1Wx8h7WmpIoQ7mg9fA29CWlJ0hW6OZMLjmkFlquPAEl6qz6KezrYZpMwQXfwhj8jONj0l5FGqzuG3UhmYVfMeRBjy0IHG+IyH5hpvZmcIKotgilUzJleJHqz03Yw/R0c7Y8dKR+RoOh9yj4TtFNLN0PJfnE8COdQh7GLO1ZSYRodUESqXfmtijxv+smfNDYLnTGBRTC/WchQemeA2MkuPlt6nQCH5fSGDK8Qh8q2u700ltdYRIoXPvjjjlKVYafT9GZjVRNuzuVfSCHEsEW9LBxtlKcm1Nr51Ytho/efo2SV+9vctb8UwvW07WCST+C65cjKPrvvOnO4KNMrUr+zNoE=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
