---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBSVVBgKcSiO6jLT5LUeBYd89akzUtyYyNHLbUb23vZNCS4ci5zppVW6GWQEVV8PIW9B2eKw4wr6RykOBEpmQsMJXF1f1KHO0yLL2fbX8rg6xC9qCqPSxEaekDHIjUzhNTGQI6FcGDsOsQC3f6ajAO+IF3gL6ZSrd/r04L0fPE5vHVOUiarNeapaDpXwrlg80EQKTqXh2jfSquRVGbd9jSFWT3ff7kmbuVegqTAkYJq476hnlYYpG21FmBkHNO3H5Zvw5YgZkWTCMpQsiPmyplRq1PwbO6vcxh4ysysR+ww+JFRUCmvnbBn67TdiTFw+UdQw+qP2vfn4dwzZUUsZD8BKBh3BFESyABHnap4lC5LFAjdCrA5sCYBgpELVWP5SpqHYfgqqOgMBiJqn7IG1lPBWfec6lt3bCQYh1xElBv7JaDoWVOKzC3TBVRw/oyxZxyhr+49EUEN+xnZNgDm6n4mLgIKBZLUtnuxjNT0876QAAywtWaTk2mQt2FbiqR0H2r3uR9/zVgx8U9YW6S37/tvtwU3E9WwdGvRwKTvNJ/xz8d2ukLtMQMG2pGZsNnmK6DS8uMWvIden3oUuu1IfR5IJwsdDHD4VcpDjMVW/e12kGBsGDpXEvwL+TUzWfcbT+VbSD/c7yxKqkOYrDDl+D2q4Qw6/1X/sNGu19kJCa9AEobUaGD+qExBuvOWIzul38KZUXjA30gN0+k=
    secretkey: AgBqrVaZyXJw5h+G+PwFHTAFbjI0blxotVodbVxwUZOwnMtDBnkpHS4JeL5r7eo+JnemQIqdHbxiic5fGAwLcLPmy0AptQxF6PGvbRa+VN1amrTN6GPQVBSVCgt3iqjQ9Z82+HUCvvwiWFb+IpeMjZ26tL+d1f7Ze8GGmsxdiSLtNIBk6V1EaWgXH2Q8VzoNB+b95Hom8ytBN1BK4/bz+c5eGyhsgFa6b3NewsKi0tF/h2j/2dOpYyh2+vrnrRe9W5ZTm/ZJHDjsDruClzfCHaXAlZmzhF41dY88F49RfPNHjkOeuHa4YdEqsB2KA1g7eHrCs4fZNGEQeoixec9FFS/B3mfuMpfVzoHnhuX6W3x6IfPUjppWoxiUidKRDdc9hRUzDCcbKlrCw5C5fBqEBucePGNXAPqDsKRgYr4L3kFtZdNFLyRgh/KiaDF/+BKvAFbXB2N6U/u6XJyeu1F2un3ENgn+k0eOiAoIcFpKPK+DCrhfyNmZ4+hRYtZGT+QqInVR0RJVaYW0ODCFxMCOhT43YDmLRvphT9TqDwmNIL7N580shkG4x4RdDVRIHpvLI68li4PL5eWLPhRPo66kX5VgS8mzVLA/gna03N9I+mcBB0abZAj97U6N5ffgWKdbQ8wv+mALIMZdzaFIu65UuzHKssvbhMeLksz/5Cd4uImW0PVB3z1pNhpS6Sa40/65/n8XV9ffc82KTFI=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
