---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBiCVbfkuE3n0I3dqnx+rL1cCXtkFb4KLUh5v6ygGa6zDQOCc80LtEaOuE9/GpuDRkjMDplz6nfSdIoyIQix8GSDSJQhL9ONpafZHm99K52isJNO2/tmRrbn8+PSo9/R5wzI8We1XPEkxmykfS/AogncZ8mgbo+HqwH1Le74nugTaE3HtfT+oD3IboS40NsJ5seRSs9P/iXDBdZ26nIzAyWqFWje2drCPootWxtCoW6v6HxWzv6RtgBMhn+S9CY47Ev2UY+W6iFo+0qAAQ5vWvLZxym5SENNgTukjmrbfLcHoql7/TDh4cekfheKnm8U3/k9IaAbhkUZpOmvyAdbd8cAnM55W12Yf5m8X9bXYjlWCapcZy6iNAAoSfU8bEpP2c7S+jCCGWcg6kNK1bHL+DdK2NaiU7MQ6IOJ6vwpSTqe52rCcpOqUsS0c8eQ2X9i8I5dZXBrVwtjmlvJPN/hoKRqQeclet59OZhrfE9r49mkWb5bLZpypnnse0gYjZ/KuVZpubqIgPe1hb8Rvhu0gOpYA+u3FABzBtx3KuPI03jyZq3l/z6CRzGuoj48CyqoZA/99uImWdwYpkN+FWoSfsTyD0v8pe0SDuwbrrJ36W4WLIdqw0yI9dL7OhvTZYS+pXq7kqyXR5VdI4bW4OoxyjbWwrzpIJojYLpzZe/elrhOKo929YtiSgOSRQPqv2SRl3gOrWarIvySpeIJTcjIJO35ccNpXXho5/1LR7NFHB/kd12LITN01aLB+6WxiPpo4U7RBsrkmArSRIGKXT8ukyTAdBpO6BKJ0ZqFplmUV7XsXc4H1FKL3UMFV93NM8beR9ffq+Xl4kLyq3LvR4DG1OXV4pDMOGYvJ77vGbSBPY0xXeZVIxvLH3T/3d27XFKchicXnQvcieXAnrnzWU73Qi33Q==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
