---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCT+gstbr4XWZa4mgUpY25m4tWAXa6R4XYn7aWJGejmLyZt+vPVuIfx8+qaZQGnY4pw3cX47bsZVmWUpBM+fm/WgqGEV0hS2C22Xvb1meD2IdFkDe0kkyVMWUe90uup9uKGUKUKPumm16dFdT/ZePQ76oCsbwmUk7FzYsrZav3VR7xL0RXKPfSFiswu6RE1evCb4NGI/F7vfSazKuiGl/KIpPppFHa63cWx9R6C8DJMDxlnIBr4GlHegg3OlTEEERnWfy7MKxIIa2ljem6HaDVEyavvM6VxR9zpzNpZhdSXEOzYN6yOJMoea0ZjwA7cRad7DMOcBo2I+hB86cxqazMWBf4pHNpYJWb1qanrV7Uq4OhdbsLISr2bJon1NqkAweDe6hXfikSUsa2xjPGg4H7KfoTfdXWkeJSVOgut1z+kJYo8XEZZ1FSy+Vvzwo/NsMvKGIzbeLDsw6xJ8yM61gII8CwtP/Fy9jeAwglNH0kv9lie+kAq1WT7ZIzfVtd6AtKKtuMtKgR5YOloh8uEVLroHsC/fIZuWRCTzB7EJLZXZK5P8cREDMHew+HKdiOOBLc03SBtAgEgFzs6iGbD2qaAtHScK4C5q8aE5MNXKV/YyPwTisPIS9JsofPXGFnOfzD1lSbiAbB2ybloZaFQGBl2V3CDtYwXSupYQoLrRyQEbudgRUjXWkNNGp3axAVb/RzNZNqC/icbrE3uF00yEMLZN4Pd79SL08imcBKFNfPLQBT574RZXlN6ObuzEhWVSWo3QVOayilo4Z79DAqT8Vdw60o9CLSBs3wVzZMfRP815+TJ/AaZVKO5OBS9bkBD29HYGEkeQDONKQOuaHrRj1b5MvFaNuJk0/8OpQINuk1bhL/y8AUPM8RdwPOBPrYKyZq+gC1fOTbtL7aS/hH5dzkPUg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
