---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDnY6tBdOHwuwhlQUHQc8E6SlZbySDFqWZBKMOzjQpIyCHfPNMVlzRkQzIjGE4ssOb9Y0n3UW3wiASI2i6kf7zJxUA9HHqu5S3kdjEkn6jV/UUrCFTvtbXiNZgTpZ6RgoWPwNl1TpIuCrUC2jfCSkslrcZw+ewwX8ZCFVT32IxUlg9mlcPxTvb9HHFvmrYIkMrsOzIyDM83h8w/SK0cQHxSw0qSLa5UjJ8twhPc0eZRQIPyl+KzJbemMkEK13RnDZxZnfihsQOJE4dAtOY48G6Lf3t+pi4XDGTnfv+/O4C1JF1s9gXgkqjycWHd1JGoTcNlv13HMEBWttx24aKWKfT6Law9zEyY2H0JqdqunYquzZ9jVwrJmUlOanY9Fe9//rHsyq0/8W2F4UBq2QF+zxqkqmQPm6jJZm4YSUswzrwWMY4xQ2SzC2JpW6X8pkeuvPEsWtMl9BUSkjFHzVbfJndKz2PXG83apE6STot36iGT21bqDlsPoTnZCbcpgSEDFMkCMwbCDa+Cb1DtUYdjFES2OySRdV7W0A/9Ene/VC36jNQXiLkspuPzFmlXSe55ELLA4ZmMfwZFeVoHiXVhciwSXPIHTBRsy3FCiHZwmNYQMT+r7vv1eeUK6IZZS5mP+veYoE5jn72WDbpBh3JfFQzCyq0IkM1WgDR9bbHUK7VxTdt/fjLREEIyL/gvgW9Gtd1owPR3p8jrWtdRAwoXwzl1jAE16fD386GWaPCLBQ0fIH5DuLSNk/dmyHHotCsnZwKCsMQt+G4n8zM+iC0RJxYNtK5wljQ+MmvEfA7rpkAXqwoANS96pLfzqGVLVa2X64VwZlXuuFy5+1CiOUG5wzmOptKzbKSr5+ltjhVQjkBJnGPzKUdORcLb56naDfJaEemUcTBosmD9kQvewN3pLw9qKQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
