---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBdLccyeU8WEQ5LJAGN4CwYqKGPBqpg2kRk+itngrHUS0WBXHSOEiZwWikq+p8KovOXxnZTHKFAUe120c1+XC21phBvaBIV3aBdtE98U6vkigCGitCMBFqPZgVZhVDcED6FbH58lvecaYCT7sjzwedbQiFAseUlU0/WNuJQNDKWDX3UQF2HjhPhyZsQpzLTIcBxj0AQblYX0idWc27m2Opf29d+9TNJRJuqlvhNWe/F0BS5E5v0BYk/7ykFP7OGmTi/v2S92RxeumKSAVjR27HGgxPlTz+61x2Hgzpt/9oiAprCvZ8KgBGAtsQhKscQsGtzafWPUhme9i6HB8XbFfDHxDxSfNoC/PY07NTn4+GxSHap9Xb1nIiLlU+15gCp5ody0YxQWduqf+JEJ25xktHMIoAlt53Tj1Oqqn2OY2Kp2UyCeVoa4TiMcNXSxj+Lcrs4RUqcE7mqyJ5X4Mir7aJMO2IJ62W0rCSVV2wHYgWhs6WS3shZVmt0+DtePJp9hz2rmI6nfLVpzUsCJF1L12kapT0oLm6IgGcjxiDTKJGe97d/C9buZ6xR9LKQ8ozHZqptz2uvFbqXvu17z/enu4Qpd3VwIRSSj0++khjWb9/FD4/DTBrzJU03Cucwh6XtY0gZvV1xhdieNIF7paXt2OWDPBvK8XCePyP7dNWSyEe1rNrWAHNdrYDlGyIGl9UK67LVSFF9jt7EmtLXsH+IUOU56TvXFVe6KOFtJpitQYOBEfaMd2qL4fFtgStey8y71OLHvjFY0PUuy95q2KzYJgDVWviYXZhG71MYwpLb8H1RvwlFwb7qU8p+c70t+QrXwnuKOthnOGIKoJaoQIaRdfTEWceeQds0N8kXkbCJiLAvGVp2k7xLna7YHgri3aKeNEdVV7Q7YPahwsSOPFEjrXLRYQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
