---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgAzEpKpt6gEvoFbNgh0OEj10E47jjUPsfQoj+BWVc+4muNWb4pSspxZpR8bWUQD4cmk29DjxpaX5XTgXw21AwX4lEf42c/1O56dG+hCh8FvEhgA54vhd+R6vK5bUDk6Ivz2ukus1TFPKgc9h3SL/Yi4ul5LTcAoXTUq/KDpGvchugE9FiO5bvbEO9yLDr+iK9k/1TiPX1sSKv/31pWyA/elhfdjTyp1De/OMabcquZTi9bTuZPJMKilBn6EL7xBaXgqNw08WVKTZMmC43rzct/xLO/i54j0y8PkK2mOBip+xWFAzHreNv0AIiNFyl445U+LCr772MzWS7ukXgLWUZOi9747mGqWBOZa/P8CVIRHtlF7PvVYcuC7Hb9IxX61lDtGKhaQxTc3i2Y9hv2tRrsW5oZLBgXMimaEaxCMIS+X7hvNvPTfwOYoaV1DVCp5M3mRRPAdEfYrkDlkusqgRA89dSeAKOt8Uzl3o6jxxHWyMue2A3UiU3gnG7iQBVNGqSA4lOaAPUaZwJKzu0Tp35mmVta08ZI6fOxsjRRFVwipcTaVSrA8FvivXZyI0s8Vvr97TYzUAe3l9hsPQKfFipBhL0E8Mxy1/JBw2YYsxyq21GUBtphwOkWBHDNMxMggJlKzohXNj79KbGDhMNHWqUgXfMZsjYL217dqvPbtV6I6LezuHKR4RwErI3Ed+qMQ+3cIQGjyBobQDcJ5Gg+B/DbO+cNSMaC8ZUxEx4hGSsLjKzEM9OWGeoIu
    email: AgB36xLu9MXIDX3uZT/t9n2FJs1/BYKsUT+tbzq7vdOPJU7QB5Dc/78kTm01YqI3tjwQGL6HejQsoZKL2edUgBq+g6HWQzJ7vB7MoBSPx2HDCJgn1zmMCFuauI/c+i0SQkm3OJkPjE8Ybn2MFBgxbQQ0VHXRZXkTV5T5SCwFyiS6+GvdK1DYGl9teONKTK+sD/dCWxM155LzmGalxIA7hwwQkWlxOleO5rAAAjTUU0RtRPf4QmBh7Mpshg8koZhyYxumyFjyLuveeHdEj28edzmjO4H+Zrf70Qxws2tKGaW5B89Z1lhZqmusyY4XPNIYGCbDc5P7NCQGsOiQ6aLAFsU608lvWBzSNfcp6r0ikInp1Gp3bnngVVBiCPI+f+YoKXCVfbFsUcueaaP2Gs97svfplmXtNQP9nu/Fu+kdjrBpvLtTCh9gkSUxnzioTqlFVVgOGbsT+1ZsS1i2pZutspn88S76sNXgMA5VmkYgyhET4Ww3oRs2+5oppfYpIoyBbkADfYQQXGsbfJna5UcqGtW5iIKShET0PQygRNIJFH7AyR20Rne1kNX6xAHa/6e4gwtJCnuG+yhAFUyZ2tuJV4gpJU4O8FAHTL+uQbvJGvjXxJLxEeM7rRLElqZqkJiF1NAQP1UdbDuOZqu1urY4kFYk53UN282PADlQSN7c9Cz2mUduzZSecGjSLR1StLl50OcUrhlQHIO638P2QckTY/eYWafAP7aJ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
