apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-external-dns'
    spec:
      project: core
      destination:
        namespace: external-dns
        server: '{{url}}'
      sources:
        - repoURL: 'registry-1.docker.io/bitnamicharts'
          path: 'external-dns'
          targetRevision: 8.*.*
          chart: external-dns
          helm:
            releaseName: external-dns
            valueFiles:
              - $values/configs/externa-dns/{{cluster}}/values.yaml
        - repoURL: https://github.com/tomasz-wostal-eu/devops-toys.git
          targetRevision: dev
          ref: values
        - repoURL: https://github.com/tomasz-wostal-eu/devops-toys.git
          path: configs/external-dns/{{cluster}}/extras
          targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true