apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-argo-events'
    spec:
      project: core
      destination:
        namespace: argo-events
        server: '{{url}}'
      sources:
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-events
          targetRevision: 2.*.*
          helm:
            releaseName: argo-events
            valueFiles:
              - $values/configs/argo-events/{{cluster}}/values.yaml
        - repoURL: https://github.com/tomasz-wostal-eu/devops-toys.git
          targetRevision: dev
          ref: values
        - repoURL: https://github.com/tomasz-wostal-eu/devops-toys.git
          path: configs/argo-events/{{cluster}}/extras
          targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true