apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-grafana-alloy'
    spec:
      project: monitoring
      destination:
        namespace: grafana-alloy
        server: '{{url}}'
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          path: grafana
          chart: alloy
          targetRevision: 0.*.*
          helm:
            releaseName: grafana-alloy
            valueFiles:
              - $values/{{cluster}}/grafana-alloy/values.yaml
        # - repoURL: https://prometheus-community.github.io/helm-charts
        #   chart: prometheus-operator-crds
        #   targetRevision: 7.*.*
        #   helm:
        #     releaseName: kube-prometheus-stack-crds
        #     valueFiles:
        #       - $values/configs/kube-prometheus-stack-crds/{{cluster}}/values.yaml
        - repoURL: https://github.com/devops-toys/devops-toys.git
          targetRevision: dev
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true