apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-google-oauth-client
  namespace: argocd
spec:
  encryptedData:
    client_id: AgDcMTm1Uqp4Dd+Z/ybsssmwhsZU0aiUYa895lb9dOamGz0V41cSpeI7mDzFJcqOSME3RqXCzurrRE6fP76gyZhwyHZWnezJozetdA+QpmuK4k7s94OvdVxGZseuVbJO7IT3GTO8FToUnnYNpUMR4ByD0MD+tx4Ve/mG32ZAtFk21vbmofnJup9jvr/JY1QsIdoTGIISDh0Jp4REIctcSWT8yzfp1V7jSzgY8pjtQYaDdSZ9GnIjv+ktdGL+6QnYfqU6/Ejgkx7VtRf+RY6LNyX0QInMXpgjuG4fWGE3I3SmXWtFE0ONcclIgMFyLm5RdLt2PMrObiXU0XRQyDlGXNE3I9rs84SLlPBJo4Uy1LBRTtc150m5a2/XgG7/lb4yf4kd8NWC+KP+rjvDV2LKISC9b0hvNWAytzNcCbx1Sav8be3ZwSvYcJhxMgn24p6Zb/++0Oe33sbqHiKIyGvo0EaeS5MoOFI9keODZM3Ps2T6yfkC4VQvn+g6b/iUR6udYq4z5zdrVATxKs66X4ikm8fmb4y88j+hJNrBmczQKs68inVet937FNhfhNDrRkG5JGrHRivIOihipLfftNUhTZ7j9TiHrvvRQEp28AU6aClfzwJGgHTYXjn/VttEMZ7FjcOzDhOW2ya+AISFcrIdFkVSk6MDfSRqkJGAqCMRRkv9hd3x0qmStQpLFQlkfuTMFFh8jw08KE1Xlr1/wmEdMJPAen+/pZCg5bJm5Rq6BrPWkOxYS+YCgeQcv89UtF3Yd7toBlvVELCI/H0zf31xNR/GACsVwAv3HOY=
    client_secret: AgBmGFBgMY3yQFjSVs9ouatiwwAPF/hEUtf87cAH8T9w9Yc8Iiz2P6Jk3QueeBVNNq143hBlbDKQ/ZMHh6cZ/QYSW98innAtBx3SZP2htKPon+p3fWRqM/xl4jXyVDRMG7V/WOwxaZ4cpo3+CRqq8m5IvDZPnV7K8UugdNt80prU7PM0od1OGxhpkqxpFlPRBGuxgbYxxbNGSKNePSGwS7WGl81mvruzwLMLCRxW5VathNIiAb1Bi3W/d4Ff41mPWE+fvWGN5WBlz5OJTXDKMiCVr0vdznPOjUWq0TLZPU/qvdsiJxHCRQi5VUjYL2kVZ+tbtfWX2wXblMs8Zf07teqtwnKCd91CiHUtyR5Eyp1/vhDqj9JopIYmhZTyzrfLsnCeGNwZQ3cH4diC3fdbgzG4vwxCfl9XiWRdCoQcORO5N8BiuHo4YLoLlz/fOSxjwXDedX5Rw4VEAMKQta29wuiGKFPb0Fci/RwdgpK9XCyxyMEe9iRDDAnjgo1foKxjzjkljFGtQN3BLZ54NLZJJaDPIJqer6PcDf1IPR38eM03S9gzy5dqS3tChUE+8wHJJdl9vxog7rc262SyvVx9JDhkBA65TjDYAjVRESgq5KFFpH2MV9WLLWHd+UZWulJm1gcjHreXBM1+7fQoaINYrbzJ7twveyBms+ed1AxLa4rhFP32A/X0Ls8O79u4PsDFoVqSO5Hvk6iPs+LPe8x29JbvHlkcA2HB5p2XMUyEzuFXJgIUyA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-google-oauth-client
      namespace: argocd
