apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
      # - cluster: ci
      #   url: https://c640dbea-09c9-41c7-b6cd-99d80f39cac8.k8s.ondigitalocean.com
  template:
    metadata:
      name: '{{cluster}}-grafana-alloy'
    spec:
      project: monitoring
      destination:
        namespace: grafana-alloy
        server: '{{url}}'
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          path: grafana
          chart: alloy
          targetRevision: 0.*.*
          helm:
            releaseName: grafana-alloy
            valueFiles:
              - $values/configs/grafana-alloy/{{cluster}}/values.yaml
        - repoURL: https://github.com/tomasz-wostal-eu/devops-toys.git
          targetRevision: dev
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true