---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgATt+tLIdUFnIA6+LBVCPmy+MkrwKU7Ppu17sFh+UXDdo/BTHl8cQ236nIaEaoKQ37PdpCwf0invnF/oebqj23zgTdyzJ2capi1mp5OoysxAniXntZtgy702abFx2kDLgqAK9DECb/eA/7zNL8wvYHaicZ/RxJeK5bx8NZ4WxP6wO4MNdFjJ7Xy9n+w+v/sFZjQSgwJq5BkWPOGf5veUJN3nbiC+2XPP1xBCuMAGvVNd045Yx5u7YFYpjSR1mVI8JYwpnc/zZqG61/Ss8jiBcZfCYxyxFftNob/fiToMgjRixvHTOdVlAHxlcIbZvyDZ+yJOVWXRqKPXRqiUG7XwHgZBiQcX97QTM55mx28QncfIqZWM8a3nGcODLvCMaFRYkUW/+Sd73EUUU0hfbtEFIuSV6MrR/agnV8SIUk1empz0y78eFlUMnyW/LJKVRigfXqJrAEKe5n30KBq48d4C/VVjhi3jY97aJtJGF7SKNU+nZX077tIwPS5RvC7it39DEpoj5f1VgfBwBEla9EX8MyauevuNNp42Dgrrb0+nxOLLTFihsdQDlolZlJF50liFWT4+cyO0I4BUmqMXLF1Kw6O4k0Vca8fDYNATos6XaH1yAIRxc1kHc6MA/Oo+Nx0wJnP+czyhw8wHd2ykvaf2kmHLmC7IrS01ob5GVJjTzuYKQGhl856RT0U7Hx2EbNKqH55hT0rMM/lb/H9GDrGpJIIjCxrXR1aewGql7ZR9vaunazuOr7G9PEp
    email: AgDPLdz/UvPnU+pVHW2uoJV+zz7iWNwnaFPa/YJO2S2cMmpqxZCCqyPfQzgUDS5iCVjVnDMQlBWoKAAwa34eDdqfUMiYKcSZQHL3TI27Y8iR86sIRe0IygzAPwpOMnDj4C8RpqHvo0h4oNF+qfmywXn3lxBsKU4xwiICbFfu8PUEEgyr4u94uosysK8U/4wsT8C6OgXlqPI630Q2IjJLf/7kJ8Z4IGG0/NOLM+zAXW843C8G+yaJJKTDK44UoXuJOuEM2Rix2vXtRN2TxD+l/lobfUAT14Z3hbKe0Nsh89SAh7QgxDrz7+IbLj/PIIs/J1ar+3hUctMyrjf1c2hfhvYq/ouaSXUWbpjbT9Ta9KdlhhOOiYvrXd1hpRfHSVqA/H6ifW9rqWf/pqHwFoc64aPEyi2dRNUzxyvl2Had2tL038m7KOMj6Zqun8S+ipsXOq/pu2HAA6/rkHEetu3Aw2ixHkpMpge1VZmWPoC8xR/Bk0Q3KpvgjlO2md239OESGnXk1oEv0PlGpIK+J73OUsBTSDK5/rL8FfCVJCY4f3wJKl0jvTNI6APZYRcQuIYS47qhAdABbRYWMcL5rh6nA2gkXmHDfgfJq+heKKcQ7Axp3iPd+Y9Ycs20xkwTuZiS1voisRG88PU2V7vRqkHJWZwnwh5PZiN8WWDaVX7nsPHmYisj6riXZioaMFPil7zsiXCWJedxWpOJazfEPLIChij4j+jc78Ge
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
