---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgDBYRHpncTkSZfcsrfP66MTAFkKGoJfcWxOlJEXxSU+H+b/49Epx3vHYsskE3OWiAGtF/vfmrcBuS+zCWVMjgdbFv5U68vieUUqzHHiVvpessoGuFVKSoiBX5e9RUnYMbCxWoxXfKqvQUHEyYSofBrez+MDv5CxN23abSkjO5GtMX7D6aj+md0oSoUWOW6Iuf4Wq9oUwQ9Duh9hltgGPxhvTm4dyiNcvJuO/S80LAWKSZ8Hl4baWZ4asKCYe9qd9WpCFR4o0s8mnWheoBXBZbq2J4wMRnEXazCxKPSbt0T5RNNUfc+NtUW8sU9X/SqHde5LjEJ4St2ED8JwowkW/rOyi3ujia1a9J+WYgbU4lv0tutIyWkIyDeuZUf1Zra8WOr/IbWLb/ZKb7xlRGom0h1wBtZ36FgN+G5lZoNClCXpM+kvSUB2qK4a3v7HT5IFjPqdgpkAHvU2be/cHFBH4P+rHjVo/tbKFgOzrwXhVf2U4u27CE08vtAMfZKyDRqfcf+VX6Tl981u8P4UhL3GoH0OPOQj6d34KjjLwgx0/y5ZpI9piZZ7N5x+CGmumc3nXW7GzPp3Wwyq6uprNo9oD4P/JlrvGl2MJJQCuRUH1xoZ33CqJk7GshH7jUBa+c6jrP/jW3FvnMTdBnbSbo0KgQ+ffJwBuIgwvxSsgnUQQrHnfoAWWL2eCoC3gXPiX1UB9sr3cS8n7Sc+FgHpFvhbvONPj6MT5ie4HPitrpmmQxnjbGD7iFY98JM+
    email: AgAg3dy75knFT04ss6hsVpZ6R7wR8L5GDvOPnF0My67XqjnrPRs4t1OLNji5MjY3+8qj9wsUGIh5wUsDMNP19OM/J2ZjUP4tSVdc2InMxQ9HYypZz7PW+gfmXJ+5pQAu/AlFVsy7/CkQ+nWOJAGl6q5Ob8aWtDaia1ATv1mCOfmOY5L0Wh46+rFZufbuRG4Q2YA6oA+bxN56STwUbJCeK8IcLEj2xZ+o3z04qLgF42NBYZxCQllOD1ALwlKD8RkhugeuyGXydIzjtw7yKyDPiJ8+914iuiuLOxmbktHKixqr5Qn/2L3JhkujIAm3dQeCWSIrB7eBRMqoWfJhUZi1UZVAgN+hqPV1c7clTekSjBbFiV7Dq1u1FIsMTc5df7THXBZAvi4yB5ETyjdCLUDlyionerSWjgwRYJIhvN1/lzLY19QvrPlpjUGEkcXLJw+r5bgyxkPa7aMpJcqGW84nofJq8EliQ/h0I5VTjDIurj01vrEbYgr9RdNkfj8nrDjaHAVnvrn2dUi6A8Ta2dl6qT48POwnloDzFTeDz7SsKKfLseaC8/J6Cs1o9OIAEykLRxmiSprBh6SP3+SkKImOUtsk0eQMpQWAezIKTNZ/AvbHPuDcWxdmKrjmMIZk2EyPO3Ac2mrsvLFQBzHtc/W/Blf+V2pT3vkhGJ3t60WVUKla11j+uV33nDKrK+Bf5+UjwqBQ2ZfynnfyHi1GDhDI+lA/96WABqiv
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
