---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBIcURHzpqgLubsClcfumLt2Lta2E+cgp2Yvo9/aDlZrtxP1FrZvtygLDDua9XqlRXcDZYs8XvaRE5uIrj8IQ54qWZgNc8eJrC3arsuWZnz1Dzb5wJzR0L05JoZ+tSvexe9SLgJGs7i3/cUTFPgwMMwZO9Azaj/f4DwzuMXCA4k75NC+0+KqUFLCd55GmB7NzT9R8prhDPL0I0cCHwhDwpqVZ4Iz/Y+rb3eU6Im/Fz2pIaLK1JZBgVWvSqEOfeopcL8uYXahHcWy4e9lllpHK3cd1HZW+QUfaRfdXKmnZOqnpyz63pWcyWNAbA3fDIrvBHGNnNlDPVGjcLKfw54B9oFjoH3on6sO/JF1dxPk0+s41PvOEnp3nEhBA0CtCRHuDvtD0fnW/ptHe4XeLOZMU2VaXkfuzr71A38uWk6Dl/RruHbR1FJuLrDuGZhI0qdZHkLI5CqzUwWrqJY1FgKfsS1ET044/TXxR0pBfQxU7sU5u1XGHYsJPQIoeoWwUgwhj5bnVHrFx0m9Ki4xMeeZcFdvulMp0XIUyZzwXOM3yyq9/jlS996WZte/nppeuCAeLUlZ4Jg8U1krk5oiU4eV1vGEMH0cU/GB/elGsDMIwGDTmbrpXetDFDTf9YE/DpJjnKAp/mlbEwT/1mB3w234FGOr79Kfe0TwlMTcatxTageqVHelZdofbifZBErq3QRQ0lsK6C1t7QXe18pn06C4eObZn21ywrIul4hopnutTIuV79/MFUYTZca
    email: AgBfQqMC7Z2NgL+0htzU/xAvodEZugVflGK5z8Q7xjT1jRTjnzVJEtYCCvA4g6bEO+75AkGKXH1h20x40h7VLmKlF1vuPWdER+Z/8WX57QZQet9souSdpN2GsfBC1XO3z1Omz4DK1k9fb313soyk3g8BIR9qwZ1ROyY7hJmuL62nEOuX69gvQ4b7Xb5+NDXmHXSeUeMyXjvAgeoIpDBbGC5jt+LP6m6I7RHKivHJLlTA9JCj1htXlLoUegJSXxoM5QJ6FVjF868OokVuW+tNRGR930UZNB+CsqnKMpCWxj0HjPlO1rTGKIoSe4YmzndsWfwWpW7V8HEIoDKgR3zp3neX/mb0KytUywEw65TU0wclo42Fpr1oC39kejIj2flW4HJcOGs8oCxfHDTU6BWKM/XzXzr8gSADxczDyQDVtDufDJAuzDVJfxxj7ZIQpFugD7jC+2dev3X0JH20KrTr0eFmE+nfAtcFXidI5PNWu34lgGqW5Oi+NF4cI9EjqM3qN0Mxsf584AEX7GlCwKHPQZfKwEYbLjYbujReZiBCn10kfh08bQEJLaPK+kDI0hecUADHMrYYQmNU+Pdjf0rhUsoqbxDPp0YBPUAlyqkXJE+HEDDZiw3Lg+nBLnuls+ZpChGEBCtcSb+zxvL/t3Y3r/g/jxThf9n6aosJrl+NsOkbp2v/bx15khGztSsziw8fDfzNXS8thS6xlxJQsyXGKZQvCYT4enE9
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
