---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgA9ITrG4n+u8UjM2W/RPhoiD8e0U/KBpJSH4y5U/vgYncM5xISH6GT5ld48Kiem0ScxD5k6m/pGQT6kgb725q9VjRjYlWmAk2bd4+XyREgEpnLXnF526hcPf5vgfgPnT8OrNO+hDjEmZNnygfNLmjMzH3ipzlAEu3U+v9y9o1OEDER9KY8D7cPOFN2ALppdeHPTo/cQVVdxw8hVkPDR4yCHWnMmlnNp95ean3iNXdpn0JvlBHPCvJjlGJWZ2rhf7TL2WhEcC19M6MhWzCKvwkrKed2oV0R7WwW/sxq4yVYgdC96VsQqcwjasE0kQUFBFC+qu3Rjk0jfu0UybU7hdcqcWnSjWjrJKcd8cRYiTI7QdP66psQ8H6mdpcQPbOu9ESBY8xnpTAzdkBTIxk52RIFkcaZr3iZ9B/exN65IohXSE4IFLdU91eCEEsTHjkoRG2Ts3xIUibEh+slpo4PkW/cHADbml2Ljs96a5uvAsUzbb1VOyGG8nFsyQ61Rf/Gb9q/0GvZ8Gs87PhzISXZL1zLryVNPCioDISEDJqHGCxIO1AK/pQqzlnTlZHeKpV+6U7Nk0aD8kvPOz72et/RTtZgLTRR85cHSXoY1PtC64DaZ5A8YYfwDcapQwF7BJtaaxyLhStIFhnxyD5TW1zeb+1ZS4DARnRHjFE/chyBuLUcO3ewqi+QcgMlpQG7gomVo6CJ50Euxx1wM50yXZ05FxnVO6N66tl/Vs3hxjowBtqwtTXtBUJWRJoDt
    email: AgBqB/xiMmTbEHZMMiOPb26pz33891Tjb1ULbvhM2z7S9lpNgNQRIO1C+B+7LyPhIvj9ec10HuORXHMaNNp2/prMO9NnyzPq/2GDYNtv547wsnNh/6PackdIRUHYkimv5cVOHFC/WcLLtpe68fC2/hwuTQg7HppbP2Z5KIWHCIdQjTj2+DoMiGKYsCE/Ft3CEALVG/6XivmtazXHzGJ6v7xyB9U7O8y12A37FhrQISMJXJDGzyP0k9iZbT+66u7mlEEFMpGgdfr7FAYzAYlCsb7AAtarqt1s4d36BqKQJIZ6uIyu6CUqxi7KdbuzN0jxleBZa4b1RCqx92X2NruwzYyQsIowk/mkfZ7wYDz3NyvP2PhRPUQfm0YsA02xsjgQxH0A1c0D7Y8XczYGPztspKqcm3aEjPou8iu4LBCNomwwYOeIEze+wlcMOUfqcjyMyIoVgxR3xjUu7cnwCrjn05+KWqOSZB8NdupQ0pe6deeaT+DpkQmMt1ngHEMXaOBNGnlK/X1SsWL24Jdzt+7rbr111YdBTzwBW0Gu7xBhJEPWFwtE+N1rLKVCXfsvvVrdkfdOV+5ksuFb+OLcaJzZjSMQKVg9juoBVT0zABt1Aawwx83wawg8J/wymy1Jxuj4owjOK8WioEBEyIBosbG765JMglXnGUD1pn8nz7O2jPrK6Gw9k7odUxWFH0mtjghLPbmz+Sw1mF/TRHlIjlXX4R2rlG9/gvY/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
