---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCaE9vBPjDfRbklvqnSFsHakJDYAZZHYvPtTeoNvg1wX1OGeYRJ+rMnETM0XVpWntpALE2l4AdpQujGU+GwlU8srVxvyAQLzxi4/amqeEnDmJ+wM5nN0udNBH/VKqfyTDRwoDybSrDDE1nlMMgBMlf0YAbjf/hUBzDaI/ALPER8AIxDYoD2T4shnrwP430GR7HpQWpgzOPdQ3TwXoO98bneGmxYK0vZs78nRWnT/wDAC9g9BPmMcg7crSxTAwjuYDZWnQnI+xvezFOrGc8mpE7PR3kbO0pA1dxKH72nepOyWx/mpWaTunPtY4jEq22xyWoQhjSaBNj5yBLcDGbb55AylLUL47LPIH7IO9VLQ/1+1rB5tQvWOKA3n/iRM8msRkjDopi55ptbVx4c1J3ENinAPtbnwk9CCE3fZGD7cgLG1Q1A7z05Cl2SrpgBAxyxfNA17DbDu/HkxyTK/4FIizEuLSFZ9lQPEjjFqOOR7XFwg2X11iWeMY0aN6Nri8NbqFWZ23L7D6P+xCvyBug2YrHu+X3HsH4AXP7HBhG8Qe5SUzGjg+tS/hOeDSKdnT7n9kSTpwzZYnwudyjj/3T9jYGAh4mSe9q6LK1FFHVfW+D9HT+Vz1rK6JijWIi0/vfm8n/6UPKWCjnOCqZvI5u4XSHl1kDGKXxGG+1bFoo8zmgmS++8gHFMvCI+YcGzY22vI8o=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
