---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgA+wEnEUUtVEhj6xS9/KhBsh7wwUf1qai8ZYCj7sWcYLpKvUon6D8nHhss/S11QzRtdPAKUaZj86a0njGNiMFhcGmSzyGO7tVqKLN5cL9gPEJu41P9pzdCxI3EUAd3NJF6/CzNQuChP8219AfUPi1YJMbJ41zbDvQTTOfZVZOgk4ju8/j93+H9DZAnnp4FW4aCeTBp3+27ocRgA+MxSIWy5H3SU5jNa89IdBNMGluLBreXAdntiasloPnkK32dktBsDS7kvztDKEqLKDHibAZT1i+szCLDNii8csvFDddRiijvFfrTIQxCHjVwDGqliP1ZWmWVFWuh4lvoN3bH//qPiMORRlYI36aBIjnkKJwf7QuIso7FIp89lamKXBNc2sonLjJykwnkmip+TyZyS5kPd1rfKU+zhUmpZG6gMxS31AgZLTfpHZ0JYYxGGc9o02dQGt27hWpHkGGlhuOpdGRIwjZVQ2xYhZDMReKeIHTeuEQHzXdVJYRaXMqnKHu/zmlBugHt+IPOj6ALvfrb2yOH0wC6aHP1vWpFsx8JyV67cB1vO8IgQbRHd4azc5b3W8dIYmF+smwwYqegpzDMKAeeEpOAlYRGrEl1O41dPntubJ0CTuIDfHur6MeID4MQkNs/T25qzv5LhGKVTr0uhQxo1I9l7RcGowjyQMrNRx+fFVOjLbXWJyXZ5QyBR1hrRlDQbgvpfxP8mILdJznA3srQDQCJHskBS8u0Q23isxC25PwtNz5/dK09w
    email: AgAy8naOniwEfs9NQvhYn8kKUGLvJeHA0gfouEXQOfqYRxFpzyD1aewTcfg5DLu9Krsv2jtxEWkhh5rDwIaCSKBfwExieasSMw/7cRDPrjyDQgKbMIYvqRN3JXkjfYKGkCUrDmokuL0ZbkE2MKKoJLRfir9VNtjdCBANxZCmE7EsOUojxoZLOP3jaX2gHpbEYvhXaq3k/7aGB81VRRdHVOTftIIjuPlPeOOoE21OtVfOA1+paQTnLqwUUkXZ81HxiSDE6YYa3cqSSOEnO2JoFe2Q7EFm068lF9GqOhkmXNQIF3XiDf7l0n70QpGGWI53W5pyt62f9fb8CetdDVxgEnock/GzHWqdG8X+oZgdCicZxmvffH+5NMCTkWhu3mjK3AOll7BgVH7jIrPXyVo4+Q1E31QwXLWB0JKzYtKEbfEvxMs51OhtYaQTLIZsgyAcxfrMweVeA09hxnYbAahtDn9oQ4kbBdUD2JWt2O5MbbyOR/eStNlpTkcvxNv+Hc72AytN/vdw471MnT+ZZ7y3hV7QjKbnz5VxpPsRyfobxcit+8ey40aGlDiW/TXYFDKFms2fN74Obe2UgvwxmyOJf/YVEq4Lhvo1NAVJhXTzhVnKZh435yIE9QUIfsvCyHNHu/P5+itb1H85rARccP1Ll/L9qUv4pVuR9fvU9KwlYwznRBCk430Es+ioDclusZV7pEYNBOIp4y8sgDbR+S4n2gCFQhRQ1lae
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
