---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCKE/tNRvaCF6qxahTet+z5eSCIdcmlqAVHICm1qdvWWspwy6z+qccURpLH0Ax4Bb5lcYQIOWlcfpnET5XjUcFNLePyVTyHPZihCAhq3IegaV9pf5XwPZuJwSZdMm8SW9eVh8i7pTcMg1T6cZ9K8rE0d50X8RIJoL2D7ypvBp4zgZyCKXHm0NutO72beliefNr7s3C+yuHbjjU48pNJeomq6Ockd7qO5beJmkLAUFvLBm+uw9+eN0GtPiRRk1PE9iW7Zt3EQ9Li5q2sNSsGO1+9sloZJEunlsyOje/DtMrucJ2/BKy1Fb5RydpZaYKfP298B25/TAK8rUU4g0+GFNEUtGRwV2Q6mSEE1Ci8f6dhT6jpEEr6vfEPLzn8tTGEv2KMWi6gubz/oeMnhNDk9oEPqAefSSLeEwM2/gNYh2IFBnBl4nXe2JSV2BMUMQhryRg0cE4kooB+MfKX/BtvAUBe7dgN52kGZJafFqj+s0zASxxy9BXS62MU3Xypc8USFwKaHLpaqcDUnD5iYmHZGr8ovEnChn+GPUj7TjUwOHyGmyPHAe+f7bLSMRpt2mJFCQJc3S+dWAaIIz1tRxxSmcZ9I26z0nwDCDIA2QNw7+1Q337z2be1xu+OBYJDP9eCQpeJRfRo3wQQHzcWAuudipoewQeUrMnmvvKulFjJwuaX6H8qn7smLIONSj3JHBT8k6O03rAnvmiPd0hD1PPP37m6tDu6TJS15QVKr0E5tqQvLO+RXM3H1/I1
    email: AgC/GocZx5F93p1pY3LC1sr8AxhdKAM8pVsxCAOriZmX1oZ3QRL9vvSOCAWc6Icot9JYuWicl39X4062trZOG1GVsmQLR8bmZpa4YsGB5Wo1YvWRQIFUTeHeprOuMk9AZkEiUuhS2MLvSDvZowFbm6sLul70mrLSuitaVsWACz/9NLa/Vh255VM+blmUPV0DUSoBR5O8OKTJyUvHDIDb4yRzPJ+zIhGgIBCqtQUWbVXaxgYqSiMGAjy1cFB8LwF+PCEUs8nZwC0TSjmE9B/8vF/1a8W3q2KCPnVF5d3vyO0bnmyVfgFJOnEPq06WY5f34I0uHw23ickCt6Jg2I1zMzGqcXTcGcyHrUzVI+CJtEsT32/s3iub64GxnEaDs6M4zf4JxrINYQ+1qvW4ly7mdihS/lVxL1ebFHY1RchT/+qZQjMQe/aKm5BZE+HyDlGImepsOXw7+7L9zPmua7tCzozrDYI5LN3iZA/tHvXoMw3nh0BfEP48MFTky9PSQvnf5F+kn2FJsbXFihjfoSaWO0j6PkAY1bL0qZ+T7PNapKiKZyMRZmPIGN6HU3Wr6UDp5u7V+lGAcKOA7CDInO3Ta8QykDLE6+SxQ16zPWOdqCGo2/D8Fjo6t6FxPbLWrjiaqBcemkydFuALUnpcs6/qRMNM7ksguQV2m01/cl8W5oQdW2+Xe4yxKoAvzrGi1XU2FD3Tqn0U35kiMyLV4LQVFr5Qkc5dtkD+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
