---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgAcFR0UZCe1u/uyG5Sejsir4sCP4C4QtoHfyJzxEuB95pnPtpR76fvtcZLh6T86ZiPoKpL2CqjSY9a/YhoGXO0nEvW+ESKDsFL+TrQIf3zFFOKJKcwqrrwZSXqC1YhTiK6/c/cY0FpinSIkMuaC01l5j2QA/ZyQKIhmsbmEjedZ3UALwiSlGzjLWHtGHvz/+A2YmiNKg3OU5TTEFkVOoPXkI5XB/PvshShrJ6uhur+fLUt0kYz6bKX1gcFD37Evf76Tt6GGx3bpH3Cbv303SK9hEH6QNX6VqKnJqiz12kD5ODFyV0rdSdc1MjHpMgOXanlIq+TZA97FwZeLSTRloveewuL9vblmHFa5twiUsdvDpeD/eWwEkV55VUW5l2AD7GBjuII6hfDu2rcFSNIOf2yJwAYhE9KZLra7ygKCdl06+gDGDG8SQO1I5FxAI8iKJhTX7bw5Ge1xBpRBpaHi4zGPKzv5a1AFJyGby1NTRONmpLREfVb1lU5zGYc5XuJW/v3OjnFG5El8R7FQEn1ecLq55obYu7MQNl97ZYQyG9Zq331tangrog3TUX+ACGgruqAlmcSIb0N830YtkpXR3adIO7uKtS2z4tVZ7URsI3AOGHOPF+mZsQhKMcKqRyq21TW5HownyNiZ+quYkqKYiSPcfq8Br2U1pl3IoP42WUeuUuhjzKLoWotAhb/agTtb/y0B5r0j2YS1XoHRHP2qvvvVOIQ=
    client-secret: AgDDIIQblCaZ5BVGtcwF5S+X7rvNI/fGr2uKD0vU5o8so08b9Vb0SVRqInzpLNiFbzVp/hlFsOTN2qjmPP1xqnhzlte7Tp9DLJMLAjgsj40ZDQtUOhba+jwDj9U4Zwp5+b1a9/LUeXvNWs1qfEtFAcSv5JCi2McvEj43eQIUXwS8CCGt3aTOaeQxIGEi4Ssn8UyN2h32+aQYNeE03mp3zqTaEZXk9E+qtSRiYIHeUNIvpwLta0tf3GXQPXB9kNh34TeRWdhz1gJFTq93K4f28MO2QWrBZzTFqxiWqBZZ+CVic/B7RyExxloFJ40o24fjieGAsCPIP0IWJDD92u62+9BD4egAnwBPCdtUC/uQnSRPFJ2nlE5BZkdjecjctx2nWIxFYKzG0WqlWfqJ+MuTDW7ItcY0vgCvoVMSeHSxvJv/oYTj1HYwJfW5yWR6nuQOGxzUq/BmO8yZfOHadWjr+hUfzwCKWGxmW6BNU6Zu8t18JLZSN/shmg6IhJ349djSuGS5R+WH89pUd+OCS0Ld8iFB3b66sIxpR7W9K37XZhylVe76BUe8TPf4eC8FvrpDO14LzAZele1S9bW8B/UumbgRyVSbR8y0GmEy15mmzYORejO//xfLZqC5R+P7bswvHDnWBwDFsdxIishKmi1mfaW4i6QYE30N6Q42qGpwvp758rSk8PjaCnaPi9kGu1rKxxs5yND3H0aibz9KjUm+v5Yc0DOCB8HP3WA=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
