---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgAu0zqTi+/qfuOlVj/FZZ62Mv10RLokO0T7RMric99aBuPqZEUpr2rft18h5GTwNp80qvpptxuob9HuswM2kKCJUycqg8en03OaIwVcfb/7x3GNeJbwBOBPncHQCxYuWfK1FmwFNHsvJxNuiXm7I8uMVMXhtxPgvKIUYUjVFvRh1rX0ldFD/tgdAw1r6iVUi9km+BRt81c56r5oQ0g6ZcnFZnKiEcmL8gfNSSUKItX+Ux/tzqXbaIOf7O0ImOCS9gEXywlOWK1b+1IhcaUCnEiUwBdQC9u7BzkbdBWEFKBni0qruC7bwYyfWB4bWmZhwjd7A4tFJ76BCK3Gd3jCWoap6lVkeNbiWT5RwORQTlmYy0ykAp74k6MUByBwbhnO5UjtcFaDhrD9pt8BGUGMjKhSxygiLxeGl3dWzzOS2mcTIKwbRoOsTtG/fbwa+RmEgZ3ecjhdI3WIZR0EG0cyc4R39yW6PPukKNtM17SbZtK1L7O4EInyFPD2hSJ/ptaIMGWwj4h7mRu4uaTeCidkZwOWzzcAkW/JewNgsMj3ZqwV6eDeIPAHGDffoUI8rNLOKQ7J6aUdFDqsJLKBjHD6vRODRQWc15ZxEXs2bcnAmZhmKLGqv9+Fp9QmBzIdhZdxlB7doZESVLwQtOgmR/rXNYTWsDADmXmroTH7CIBU+VTHuggNBmFTXkQ6Twcrl50nyH5QpRNCVpRKFeMJXi0tU/1RPCs=
    client-secret: AgCFCKBH5f4kFpT2gpntpLEOpkLl6O6J/Hxb6Nd08MmpbSH2FrlYZKjx5ORUN8RDDrTjqUXx1q13LwjmUcWPkri+OpgrCbhUDRmZNtAVzAegKQp66nUsLxy7jo97HcFr0eLOWm5WwhN8GNy7v9ilxqfPssas4YtSaQ5pIcd+GgxOdGA/eOQIRRsr20cWCYAxiygBo7kjAeIYKPlxfjGnAFmzOj6+r4NvwMaC3X7c+lmDumIL1KLTcR/WQFTL9P4lEGk6w4eGtgAJtMcOj7MG0uHpXB1JBQM8yd2efs8VceSvaWPIjWseR5kIIjHNSMOTa5SYuIBA+HAdP4MnqpgfnEbqkh4Po+cuM+JMIdOANV775aszESabww9XyyMROkzZNLArhLmH9rmM8T3jQvnAF735s0c/0QMNoVxs4MXvK9NHVXwxk7kF1mi5a8EVzUinRIkOBc3jqXZKUZX9LFcSdVIQtHbQRyHYtYbxc8vpqbGGDgLxI0EYHKOJXIqUnvd8ZDe+s/gwxnSbXjaCYkgBUhZs5EIbc0kO/Zz6cMUWM5OWgbdLF7MXLoLt1AMpTTTaJ8bYh20wsVMOmxPbc3pDxnreHo4MICuq60x/U/ek7il7T1tAZuebR6R1j+oAUryckG3EZcS1fw5czb6KnJ+I/x6n62ll9QT4rBvVBgY8kV8fwezcZVSRNgdPIfJsTGzq6Brl+as/rtkrzABIc8Qm/BtMFiOUaA0yYmE=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
