---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBKVvIhBZ/QFf5QfIzvKK/Ft5/29/0pHeaqkWWfpjcEe4iD1Zs+9uluIzPkLfOKCsXcB8hp6iuyNKS96cDMJpIO53yG2jp20XqpkfNxRJegjwE9ISZKiNJXjOuQbR5s3D9zeGGAF/nhJI9ORsVjdif5nJ+mwzTMivTXKAp687MQ9oc6HG5zm1mQ2dsVzJu5meIrLkUEd2Vv/7iRsbb4E7UQ7TcjreDgCEOY6N5TmOjcuCvXkgICQiLKO3KCjqsqgZ2b7brYxd3004qxatX+vBm8AJNp4r/hcY7ONNm00SE3E/NtT7t/6fw8IXVydzfruLm6TMnO7BxV8kzRRM6J42IfJqZ+PZ8Sfe3LVl3+eSVFWkR4LW4EYoYFAU4mnbg8H6KgxBNe8nxqDEB2vWMBCwysbG6/QGM5p8zlTFAxV0WOioprdUQ+aw3M4L2Fsnz/S4q5CLQpt3T62iDl/3BySSZYxr0/rvDF4Aip6yLZE6XPPToIYXCaJorsk1SZurwgZ7licDBskoZf4aPjf1pZN0J1bCwz0dBBYWMH8B1+qDvW09vFOH3WIEibXrxTFqsdihSE4YVy4NRJzQlSFIyTJ2yk+8SBD8LmzV82v+gbxnrLlVpVMizkJFoClYLvezqCJOrnhBLKV4+Z7bljgG2xz+BR7Yg2oWjVXGGEIpk12XnlqS7skW9J3erMLX73RqJNvCW6dEuKGa0XPR6h89Nk+HBIv2g=
    client-secret: AgBLD5/UT/YBr4lfsCi8pEbZX/qJYu/ckzEfKHb1Fp+iiVHmZiLHfa0oUrrERMOtl3Kw0FqZbBCozwgFVz8le/f0jmrg7oBMHQL3KjqPPPCUzfhzIhX90w8vcQA52qhBWPB00CqJu1gKvdtKpzXj2rPqu6OEF68b7Zd/3JeEMtwa+LFNQCJY6hRWx4QptStpPZ65voqY3mTcrDbT3JsECiItdr7BzDhPWuraT5U/IXfrUdiQ8nvAoebSyVERYilGT5b2BO2/I8NzWe/J85l87lvg1PLFpPusMpsSqBnlpuRjY6CbIQ5gqA+6yQ4vDSBIEK1dRZSQY5RDlQwgobrvw7tKoqTThGKRD57rJW10Y3NOdh35W2mAJElsGeXmNXx3KEKkVKx4gJzMX5nRMUkETDXm7Y05s1MwyjsDo/hQwynxoylzAvsWIAjSB27+LVgsun1posTtGBVD1OsdZRBf5XVPWw4LSEoiDWYrUj0NpwXEMtmqOeoHKiBTDF3GHSPeExf9/OLEWt+tCc7ICxRjznr9amugxV0GX6MMFObt9VClYwSfVAy0Vg1EB2Pn1joCD2RKz/iup7As786ErmOAs0Lcg3slCWA6H6RmBICuzRPX8JOiKGejnvhetO93heWekS8AaAMMz9/Ja9ACZ5oVqgPRIUjxKgMZixy5SKzXx01e3NTH00U7C2wQ1TBo321NKM4F2+rA7SWzuCM+nbwKXO9boboqLb2vWLg=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
