---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgAKweeFLC7H9i8X+DtkGwKapsMPqP/qGoBP9hS6pwN+k7LS0DFtC9hC2CFTVN2SfTmBO1O7qsBweN9bTkns/o2qJTXOFuZLO+36yZoaXTitFqNLa886SeN+qiJRInrnZXIybCZkwoMuGjiCABSBnb1b259E6gM2aaNRgtL+bwjIP8RaCyR65yvOQRzaMjYL7A8kv5KVyalMAMwQea5pZ7U6Vws3tG/CV7alfOzdPOsnSDoB3j6DEKHHx4uw0zBcvp28+LUBTqYmPn6kaSh/HXW2IpUBK8Stgn6DhVprNbf9r75rhRmi6Uk7qRZnz/5lXOgUoxupRpwuRMi3mq4Izh/BQgkFru37fZBcAXvykkTD2EkpCRopiMYVYKI0oQg/oYYsl8jOIwNirR4dvfhu0WTYmW3R9fZoZgbBFIP89jdTrpm1JbJIUTHo2emR9Px7/Si4CdKjb2S5BdsmPXeg5xzjnZ3uS5M3QF4VOAYIhZRXkhH5jdH8GVrdysj8FENHGqYBIc2e7QoRIgODzuZshE+yuifRpIbouzJpCVacNpJHAfa7zjs+IQP6Bs2/GtoXiwvf4p280EOTF6cAhsNkniYrDCD6fCTrEGWA7Lk7hVCrIvmbkqsicM7cxL6OPg6DUsP2lYv/LXDYS1kugB6RbZrmSpbPCMG34bjpJJnudKhNvQ0Hf0/lNayPSQuwHs/waD8it73eOzr3NraEs/SbTUFWrIc=
    client-secret: AgCXvgcU2LlgYDBryZjAitKYAdn9jlmzn88sEWWaks6IR5XqE0ILGdqNGa+7XL2KmEu5boUTSy06QQzDmkc2vM5ikr2re1BIVDg86mdYYt1Vybzs5j+spLaKVDgdoSez2bwOlnNBbpP3He9/NcHLxyIw8R2pRUzEUrAANQGd7WRJD6Mejs9psC6VuifrjwY1ETi6NlJ24Sc8iOmRTPAx8p/c83FSQLGknojxzEZfUBVzuZw5Tw6pxPDq/DfSiTzChdw9+sJv1fvs/6mpjQVs/MtTXRAKWgtLTg9lkG7pASPxc6tuoanggAgbYvhIiiDvGAPKJbwvgvUkmezDhnBBJRkG4Ng7k7MBqz/plW4ESiCcJ7D3I+Lyn0beh/UtC4lQsxG3afJGrRShYcIqsuPuY7BOifeyHf1Nj+6NzVm60JhN4sHK/d5TWXcyhC1ANXHvSkzWdRyqglyZBX9VVhEs+sbJEBrX0qwCQUA2DsMc1KGQOM9rjnt4PtbInxRp5eoKASi7PyVHMUCUGxtQdpn7oNSVHnOpHMpjHEbS2EzX1tNXmIqFtUeVSscFa/9UNtQhdr732Twuqr5sQDf0HBTJk8uT63E920wnAmhP6bWCylrArhfv9lZfvRrnkpb0KmN0Pq5pNs+/9CC3Ltozk6D1G1koeDW0Jg+9zHYzk8lM7VqdUYFCh552QbHwijGWTfyMgdKm+kODnPydf7cjA2qJ4US3vjt+9rhTKhY=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
