---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBKrNCy8f9IHvbAdp4L7IdmdJNMtCS/Avk1wT4PVZDCHRNmryrEI5E74aPwv6Hr7QfYUx8JlxzZRR0/nZwrPyAR5fHWww6dc5QKSHowczeoizO6M+KJiOD0FxsAUbrY9d5E8cWrXhzVuOqB1WAl6n0m3yrX/+9y+Cq8+GY+XfYt2sWLPMzxf45OFqpLxq7hemvTcpWzI0CTqW5CBj6xaEGYLH9lIcvL90yYOQc7PebSNQWpmc6dpbaxIGgNnO6I0gZJrSEnAUDi9lIR+8OiQ8WXv7d/ys8mvfYi3vKy66tpyxH0A08MkLb9FcNCLSLTjXmUwvk9xM6eJv6Yqfj3oJ72ReyrtepgjgR3eI2ixLQxQiRlg6e8Mtj4D/ozDeqUa9hUGkIffFUN2jvBY4lXMo7HJbyHEiMAbZC8VVoeGORz06UpGamxN9c8zl6Qibi8OsmhKUmJuVOl0ks9RjnJ7v1LpLxL0Q85yJP8lDHRJ0Hxmd4VQjzp1xRQ/wWkH7Jh/alkIYTbaREmdZvBkc+0NvEz8QQCIW6bmYxCqsQYA9w17axcVWakxWBP9Zo5EzzqGlq50iArGVTgIv7fqe5POm/dvJBl/5HJsgGbCpP+jXzEV7PpT8TN/zUpqiuqlLcri9jpcsNqJoFxyEfxkpmZJqP8vnwglclgKMJKuTAg3CHn0f0eK0mw8A6XlHphsL4roRRJ4qCx8AW8mL9q2yDtMB9rmRg=
    client-secret: AgAyTFaF3i6I2HonDhJOxFggsfpMnft2rJfivJ/amai/b7DayHREJNysfLjzUmsKtBCWLtQSLuDz5IdkUZNzgfjglg6k00kRXAXXnMFhxWS1/yXRp1G1hOyEPLoq5p71YZAZniHOQ5fl3G1CkFvwMEfZMfRxwY/5EXz1i08CkzftCUMjEVwbhIKmtlW1zDFF/Gef0ImjdEuL/gIeUSowvy81rRMF0WGy5q5/7wpwDrqVh6clNeiJEXhkDAr0x16hy53p1b99Sf80uGkP+r40nAFHINU2duDaUn8WnVsuDo8B7qdRCiXTZE/vMDo9KviIl+lm2f/AmCn+3gs5fB2kpcyDR+JT6K6ORLau0a9DXlLaTXdmXyc5nCLuOi8pz/A0NqYDrkZ6YfQTiqN87AY+vx6gFt2PPqF1IsZkf2hS4ZQGhi8ssKG9ZnpUmnIZh/hvurORIoU10WcVSHxc934GNARdFaHH9Y1N7uq8X6H65q1GJKIXb+tLBtzwVnpauagHaLT1PEMLU5QURFKNRxCWTcpQjQIqLh1kXfnnYp8Oao/piHf+FVsLR0oxyYJANjTX4mX/9IsIvXPHgMhV3wNNfAqGB9h1IWn3zS1bhB1h9fk6lTm68uHWL2Hd+CB4NvE+JdlvF68OrnmsmPPHeFmw/0qsYuHOlvio3w6S7gCE1BXlmB7Xg32wY/5o8uTgjjrwjBRPaZ4cnis2Baomv/yORkpGgoyfBzWK7os=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
