apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-prelease
spec:
  entrypoint: main
  serviceAccountName: workflow
  templates:
    - name: main
      dag:
        tasks:
          - name: create-prelease
            template: create-prelease
          
    - name: create-prelease
      inputs:
        artifacts:
          - name: git_repo
            path: /tmp/{{workflow.parameters.app_repo}}
        parameters:
          - name: version_type
      container:
        env:
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: username
          - name: GH_TOKEN
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: token
        image: python:3-slim
        command: [sh, -c]
        args:
          - |
            cd /tmp/{{workflow.parameters.app_repo}}
            apt-get update
            apt-get -y install git
            pip install python-semantic-release

            echo "git config"
            git config --global user.email "tomasz@wostal.eu"
            git config --global user.name "Tomasz Wostal"

            semantic-release version
            semantic-release publish