---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCivxD/1yCffDs5VtZ2ZHvSPeUhk4h487pmtH+ho1OvJyCDAwZxO4BipZeu0a81cuDn5sXfozHs4QoePl+5B1dEFXcvFbisPrO8HzvwjR/dD4KYXzpYxORzT5/tLiUo4dIwKgjpbgVJEz/nIdmNmB/ScmVfaS8zVi4B4kxCPjZrlp1aZdtlvexXyNyL/JM06JctNrsQ97DO7Y1q8gijWTOH5kZ9Pdf121dBvxVOPo6G5g5n4oMF2K+Z6Qkoy2ag1PH44SGu6c+kcyU6sOUa+pRsB0MtxLSiA/Re2fHHrbVbBZ3ojE3kAlTO3ozjSgIbT9bQsNHzXSdMtvaA12L8kmtHIg2jmCV+nOAWNuGUhSRHt7TI0349/YwhT6Vvo8K8Y1rgR9h2H1o66lIrI+ufGbQGHL/hCjivqZt8DywsShlkgsif6+xHDfguR/lW0otfnAtJwWQY6VuDQMpr58oDlRqKVqjeg39OCYhEKLH6/gQNb19iV+PAxB75sI/owZ3Rx9TOyNLLFI/YffyQ+FPT+JwoSY9hjnyAxptoTNpS1Bx9tx5fb9MtACdqn0KQNGUHZe1h68ul9LbJXl3m0T3U3Jn1uW1ARDZc/qM1ufH8op/lM4a66stkaQxEWxzBQy03nvRkUmLzwcLCp5Y31RxhhWWfgm3tV2bCW1mQTqbD3/CnsUn6nEiAa/cXVZERxX+B0DZ1GNMsizm2k2PYkC/1Q46EDyqZY0SeGYesVmQUd/J/b+USkfdGNeK/2W97MRmWHadZfilHxvN6nkcGxZEnrK+xL3fOhsbofJrMSEm9UUyYx6V9Fba50q+Xb1d7yySRPj186iSItjcznrNb1UDuh6GupyYK
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
