---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBjPQt0xOnHq+ZEFjQkqPSj/UtFU2c2EILPpR3ajk+grBUV3+uByAoqGTsSNrQPz2kLUDfP/7gGV6fVLBURGkTP+zBJbBCmNK7Of/dZv5fjhRv2KMS2xfMzSTc0XTwSVbaUhxhyb6cXCmwrcMA8OJ30K7Pvify0ytyo2gOyhwCdeB38STnKUh7VVK7MGN4ecpN+ub7QCQ3DZ/r1f4W6Q6rge66GBr0yTqgD6jiL8p353+ija5TXfh+agF7Wina5nyomll/dek0WgNFsR+VR2WFbYxbOzpkl3UPDV/hmpNec4Qc/5pZNaDA1j6SBa/G5gKbvUIOqIF81CLW86EZLPNEw10qnsbK9akHPyOM0rKONJDxxJv1uEUTdJaIhnzTZJswxLmlKiP/lyBldvjaTm7yJcnjNt53nuHH5fvpRC7AvCYomJdACEfjsK6/yRmJcTrYWgHxSXREeYZL7Vb2qQeLZAzI3XbgiM+dLMUiiYTYmkXM6qKPuad410KM0BV0PDBSxX4Qrs7AnLhECLtEZx+a8+LL/VvtdZjskqaG8of+vgh0NSoZvfE/7LWrcX6Sejk2AT34chPwji8qDBdlgEsABEd1auJYlhKOcvzE6Lh/QgNqZtfI+y84OCMlrX3ZyeCgG3ZF9/F8DKIeUljrqhcHilMxE2a2pPH8dOTPCSRmWt2OKfQlkgtJOcuBmWDlAEwqVy2tMtXPdxIxy
    root-user: AgBasNQIb/JcOim35YFs6RmOz6pDMnZSppVRlb575klpaff1gFpSPSH28N7c1UlnNg/t5tV3m+4rFgp4NFsgmm8AdanVrKdCMw8VJT9s+g1NLmqMXE1/ec84/8jTV/7Lc869Fhc/aZP0wz+/PXkKJ0L8MddlGvSyWygZq3BUP+R2RG2Kmz1nFR398ijKtIQETHDLxa4x8LSVvQmpGEPVIg4a2sJRVe8d6AznfZIlBT7r7fzt3EmAMB5cJzxMejqs7UU95cSrIFeIIvmEPS+9NxLBzfeawecCF/S2hFKyM/4xlPRi65Mjy2HHR4uUwEhdcYdnq3e42C9di7sFxVkT+pz1gKbU9Ebh4rULBLXQPXrwWGpTjo+b9ywq2KhdZQl5a5mgRk1mlPzNluYi+K+TXcr5PH35Q8IoZ2NvJ0pqLFcZjPSs9WJOZx5K38FkLN6gWKZycDs+1P+QNHWj+WkDhRGSdFquqi7ZLUFLlJrYsjwnKPzd4LjKWYOzAsdONZOrJoe89YdhoXuljuFiH2BYO00DUdZa0WMcYS4a7cM4MZUOeRiKwjc74k6Gd8cwlwrSrgU7SxPnTGEJPeNz6A+s10MVtoZdnxxYsMtWItR9lT7CIr6gHnGHNHWJXoCrZz722MR7ZU2CD9yrfknZl64hdn/nTyvKvFx8uwIr2YPHgd9jzI/0uyEWFfLVS4iHe7W7zc8kx4hlHu2sFjKn
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
