---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgBCKacZhiwaDy1ASWrgl6LTb9F3Dyd85C0Sr2TeBgZ/mNj5zPi2UqEobXlVhwRZFecUEtiNex1/5PC+4Q1z1t0n9+GyKK+rLg82Zg0somcZ0Zy5SQZd7I83YkCgv/tCu3K4offFPENkfsZFvdXmdY2NmxBdVzac3fDZ291arTYs8vao4i44wvdfxNFfFMzVRPlWOBrV/wpnU/KIERBTmgWR93MOBq/SI1S1KATFGtJD1byXrHW0rXro3cdjDz3zJVfpKHAWtXIxQd2XF81fyiTlSqpf/oRnVnqmRcpm/ST9DAXbDRCJ3K1SO9fLOtIK+0rerrxJNaOGFz5xHgsEDOsC95eHLIhkOWTISC7hCQOVhz59/bsD+Ziz4uLapa+bmp41+DodaT/gWohst33zyYzJTTpzbLvXhCIzf29S8L4RPsqrPKZ8CEiiOtXQ3WVGsDDUBouP/lKvY0aiXkOnQFhPZL3mZUiqyHSLTWZqIvtEWngSg2QiDebl1eNV8iBMmC23gpwsTGpgHjppjErEk+4HQLM7ISqzCiNs5dKTIgxB0nMJZbrFVFFw7d5vEuEPs5BnG70U9+sX/Oer7lSkdKjoJYAfHupE8Hxyg4/oI0OORA/ebAf6lp4rsO89qlfeLbMhPsiK2ejQnS+thoE1yhukwGPiDj26Ac9snXnE6WvIvUIDKCrsWyN00G3Azs07kHGP1D3zoTRUXmpvI5aLTe8B/pdIKtQWLs3RRNgIgsKVRiD808mjWPQK02jlwksFl9+ByQ0BAIlpT6yj9zVILrLNwmz7F64p4jfzlSn0vZV4OPjNsrpNaz/6JRoHEcnd/z1xwy6L8llSke3/9O18MS5hBMtx
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
