---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgAeUMsysCjj7XatYUxTJZCRzs6+9YzbI3+0yIsj7oN2kNS8Ruc8/HPzNg5okR6EJ9CzEQ/hlnWVOEqGs6JNQpLevY2emQ6udhYmvFrq/crg+7C1Rd23OvkOzyRBqqBoXlcdkGOYSupLw/X4ulkMhRMAKVWSLZSmIJE0xLhKOKXg/Kqp4DXauwVn43CklWnTay0Ht5NswKsEyE1kdOB5sQGtAZQs5vzEI4a6ec+si0eECZq98+910trfGkKw/8Qx23hMv6ujD22qyqga4C5/RXb4EBa4DD5nakPudy5xKVL2CDwn14O9sRszIIR2lIJEpJHG1SuU7JD1/lUcTuBRl4Cs/grI00bgefNJZi5WHM55QBzh7ZFL+NMLic73BPajHt0gHK9f8tzsFyO4oGPGZywEAKXkxniCzl8Fs/uvchhKNvbeOJigSfeTWHMaA6edIG0QdalhiGu1H3F2tPjYPnqZ79/BTt6smCoGopaUH5u94aM0In8rp6ZT3+UQwTEcLClWsIsVQEeKEhY9V10xTISu4PpEtNvJv8aAWnC5HmLERgHrYQ3Jyep7lUaG6QOMoVtA9DU/9/OHwEykkCOONROygrjmqKmFon+zht/DxmmaT8V5WF2t8FOxMWKzathH1iFMv5VZAdCMvdlHrJ39uG3TPi46NFqp/jPn9BN5Wyp981N9BgvtxVQaD7Wo8tg2DIGzDa14gUS4wlM=
    secretkey: AgBXDLLAfRAdc1j+tYVBG+Gy2nI9qZ3Gr206b27lkAEyJzNE+aIpKxpiH5Arsw/p/o0tTco/pw0IIhX8RqHIttcV8dlCcEyjpL/1J1Y/Ur/jjQWGjLrQdHmK8zufgR/2oMBcFLUOZ7mwBxwm+XMjXX1kUV/LBeXDOBSnQ83Zv/dXnhcvFP7ruBUuYNq2rUlgziKqz3TZZ8TYDJitxLqgCUo6FaFG4r9m9p6oPDkCDMBPHTp9vG4m0JL9pfYp7fG/JjQs6FfLyIawGCj2V6n3LH5oHrPF93p6nEStJblwG9kV+m9ouH/PibvDOJziVY3ChB4qBIAb/Z0wePnnSlD+iekb+zTb8UysaiJpCIUN12t+4aeGy+V81q/ZuVLLxoA7QHij053mXxJSXKECLXqCC1/+Y0VoMYDqxwKROe6oOz3fKgxQq7FuETc7rKb7bScLADHlM5FqayIONPTpv6ULfLb7Cktc/XTTXrviVdccPSn3/p94516Yx87541DmovfyFJbtb6dlabEvqMUGuK2XX4JbK/nHvIk6nekTyZlwKGFErgwyAoyIEd9x6Y4E8I6KuDpMgG4SNf8P95kxOkTpixaKVzs7ahwnIrELTq/YeTYMRJ3AnWRv72tA5wTqCsUX/8iXqqSm8cUKP9+aITMelr1Y3YzgK4Beo9ycix8EWH7e3INiccrOUalBRQK7x0gmsIC3nv8TKQRC64E=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
