---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-google-oauth-client
  namespace: argocd
spec:
  encryptedData:
    apiKey: AgCXbENe22YpsJcqyKr1rmPRVOXGYunUZWsBg9YTHn19+2riCEJDzRQdp+rNjQw7aiC1B6A24k7H9kXgdY8PTEkL8hNh1cMUx2vRmp62ulILv/KbPF6FxQBKNo4AsdQoV6YTGidzPCHAOukKtlrLuoqFxrsXVyT+t4CJ6I2Y97CP4eY9Rd6XWGyrNJCHB5OK7QUYbOjyYbX8sbFIJmzy4Uaqrfn25clNuvQlpe3Ul3RjYf3W7nDkMZ7Ovha/4z+ClrG59DhcHsCteQOZub2jQaFOqsyzSab53JMp1paYJQOiXUJfg0jgw+iDm6sIbPEn0W7tmvvXAs0DKHrguh0+s/DqpkKrz8RKOsJchbdnjhlz8/vTsZkovtVK3uhO1KP5seSoyrwSUl/aj2iLectHy6jdzdevHtoy4Q5KARcJwhv9o38KUglNg88rlMs1HDXztML3Waawq92aRVHHmucNIQYWB8suGHbASFVpQvlrrSf994iupLK5o/SnaN7MGzhM/hP3E3nywrK27dm09uCahfVqfOLb/RVU3JLW7gZpRH3Lmcxr/csr+9bSY6XtR8Co2rqAeldB8BQSKp9aMUf4offkwoplqrky9XMV6lqWE+Ch3mRABROVR/uMAqPtsYPoERcUx7jnchBX+ETJeyaVy2lhFuHU3BYd13gr4dVvYD6EpzH+U4hMk7y0JvXy3wdJ7mZAovRg67Mj7i9Yz3DjAmiRrIuyNgcZ/D10cj656DIS6KSO0rmXDduyRw4hx6QVY8/Q89fim/D2TCioa3qqAM8c+RA1TzSA+88=
    email: AgAkgSjnLQGArxYdVsyozVHbrvAVeNgOIEErOfhc1heDEkRG0ZBCGOMOPsyaYD1jCFaRr8qWDyfeq3KOYcIXWY4RnEvlRC1urBcbb1oPkHgDk1kK61JUMapk/zBk5jUCCNq/BBrKLbj2egAL1cIQXuDPU9ugRxvteL/18NEADHS9Z2ivBwmD7oUTWKY4tlrmhEcxhbo5BcyalA4tGR7Ane0tmPqCdcshKM8Q2oj+i25XOKDTiA8ZGKjRlB0FgAze2Zg4QgR0bgggv0MGiDmSZultc1v1MXvd5ssRl7gohpMQk8c3XC6BvFFbvIXSQrf77VGD5Pq6sq70YERZl2yY7lGig5HNpLbGKAp2susgSa9pFb/ulRitWk0IZvat0IvzUmZ7C2La3NDWrc06zFriTph64UD3IwSdaQhEPsusfdsL4jIjpsWEe61/wEtb3+x+9JeCNkL0ykMPt9k9/uOjlNxh4mRCsHJxNR1CfG5nQCzRxTkN5CzZjqqVgo6yR6OVNyXqeihyLMu8oRVeXnMW8pN0LGK6b15Q6Gx2EVjdBJqEdx3RW3ZiValZTchVMtL9+XPrXnm5WV0EPTIee5Q3k5H0z/TPmumUE6jtMKqmq3kPnencUW/RT8ukOoKsvLzWgzz1XPnNs3lEuqlEhwyyuUDggWDubV0mZcvS1JmaEDcQZk+X1DWo/ew4S9TDmlGeFWCbSABewSNPu18Zv2thDwnso1A1yllCob34Xzjnpx9QU2E0zQ==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-google-oauth-client
      namespace: argocd
