---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgBByYdTyDKyfmsoTTjS2hSciNDmd+gsEvcahW4ybKD4ipHNbfB7xteYOOObYCpM5oso6+6AGzHu2DCZ+H7j9rJADtGt2lrBcgU3RIdhjamHiN7QgqArEaFQ7/CuU0XoeKAmDgxU1jVEbburA6Y73hCf642ItivbQMKHYHW0euIq+KoPkcFrPt5QZ34eAvS0FJ4IvJAOLpNzF11VHvTFR5VnJkbRE110ZLdXaXzcOfqyNN2jt/IXznB113VSs18nRvi/fPCgMJyZWa3Bt50U48EADyYUahfVSRCApp0UfxhLMlaziuzBCkEXvRvh9cHwgkhlcRps8RJ5Y/KkeNqncS7K5V5MPTad6rAE+fGXqE0gd2+8FNEwTiF+188cIEOl9KoTvGzBTH1pCE5G2DG89BhcxEPoeGc7C5GtiDiYB8AKnKmrRVBpJ3AFe/wiEm3+PDOLzNqifycInDeTcN3jOpHlNJzLrd54XApfVq9h5Veu7FVxFUmByek0vgE7t9b5MAYJtNppMZEdD0Qf3ApOijQ7fhZdN+C1MzqKFs+zyj8G3XPHas1f3hlPnvKwZfNr8QiexUYH+NlisGgx7MS9S4WVtjcODv5guo9pzu8/qO3+MPqTvH/T3kKKHD9S27vQSSOGqwEWhO2rBvaghgTS4wLmKNJTW3RzCj8uCmKMWN0sNAlcoNxp6dYiKqK9YgNnI0hUxHtK+HCVdS3oGy4rma4yttsrcWF0HeCMZZ1LtzcJ2HbkM26PQ0u8
    email: AgA7uvjJMja7nr5OlJw1Aw4kp+QsIHldjKCqKR+AdScTSAxZV70LOj8aBTx2jicaQHP9FHO2KNmk5tfST3/+geKKiFFzA44yqSBMIlq7K5YPOf4xPen0ZHh9OxUZcfupbSPSeJvBkMa03demuPuYQPBFcdSJp51N8mStTSlgea5a3Dm7CK4lH90tZe0UKNAr1INEZC2DzzCPjTi0CmBtai2wxmaQTp5naYgehv4OQyjHVpuq7qkEf0fhpbGPPPwGMoQ0IwCspjxii9q5oa33b4TqnjYRDnG1FQY2bhJAbRb1kkU10s2lRfb14N0/wsYywcSwvI8tL9yDwQvRt6lvu7sfQWfdNsfLdUVoL/5Q+WN2Vfcyiyl/10dm4UHDzg/BZVGykL7araAWgQQh1gvl1JbJ2avdMAFcDxnxJnw1XZ/tbuVcNIa0Fab4Sjwlr32Z+ITjz9UFR11i5i7cvIDv7uyoiuYFSpJcDX6hU/CgbdPE9Yu85pUXP2JrBREpBCy1ftcK5uPlMbJcm0Nvpv4VSKxZES0UHaKfuy+d3eXU/AjV+Ijk8PD50nNzF6sN/s/3f9mKl/c11WB+0U7LhoV6q2tE0yU6oAtmuwq14TwtWGLWUqpg8cONsvRZWwitsg6B0KBKZ+JghxhFu8ZjvJPTRlGeGTSWHW86UV4u6VqF92+Q5wwdzSTJupJ7xNp8ALyx4/ZbPm6samwoHqRDMWz5f7x1jfNzJ7/5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
