---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAOc//es0JmoW/EGNRROk+VSfJsuBG/aKZco08+GbkVky7LiyqunclAC1RP2/3zS2NRcABIfQWMMp9rxcsyCyFNhagAYzT4Q5tTCwO2uAHTgyJn27+dxXCRwfBn8+CY+eBPaMf5izeYBNwTz9rMwTzeJLg5nbRc195pIOHq/KPd03Txy7LxgW66vd3T5j05ggEIL+TT5OFvH26iypRN4jw+rNq0uJJf3h/3a/BKoaTPFv8sU2Zp5nVAPVmfP9tLfVRnKGREWQtennKdGXP1Hs9/I0XTe6j8OaGfnLFRU33p/xNDNCyhxhLcShM+eS41qhUc823IEPi/wGskAhuQUoGKtXTSpzouGJlc6f7RvDoY7aeV9By0rDLR8Z3738YbVflKtiTiEZ4g98uWsf3bXUJw9bgsgZC8V2fuxtQ6OnX2L0N/GRkEihjWuVOtfajlsxBeRtdYUs6P/YTVpy82j70J1Xo3F9kIhKexfyVsFqjLQYw5n9moOdVPkmSNvwCfK4OlMQy0I2h6rG+FG61NNpOn47oLZZSWVNOySh637zM2Nwgm2zXdyfEpVcKF9pnww72XP/8GmQkkEc2uCddc96jk1BUabAtX9kcDYdCv7pSqiV0uvxo2bvX8nK+/UAU1INzyDZr9CiO6n0ff7xHZEeZUhmarWzcr6q+lxAh4zrG6xk+I0WJ6z9rWmj2gUGxp0jkESrUD3iUUgCGrz1VGlAZxySHTgnIDyRuutL+ldgy2RJx63eScpxUzPIXr6yHMqtILYI41+WxXPynEaO4jiCeLi1ScBKr5QdksLmAcdqgl/WV/Qy/szKpJhVfl2EfqnbqOopl7QpfITr4jAKVYKh/JAtYHfuaSHsiGhts1YI7F85ztAplMKyuYSPhgXALXV9RNGo0RClAfxM8/5UpfUwXBcQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
