---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCBnKGCKMaSptYhS4iFAbrBvMgSx6z9xgvk/DVa7BzZMh4I8LoYso4l9SWcEpz6FmugSd4qILoJ5sz36JOFWQiXN+Q+xCRu2DqwE8zUlcrVUE3p1LJ6dufct6vHbRznn/BGDggRknI+CcLUm6aBcVWlsMV0RMMfGHM/IJfYsj+t8uxNOpv7He8utY0j559liueX5mR/oCLz1sucuoeHQW1WXshXMViNtHs0pk+yWcG+fT7SpB4FuwT9zENlGD3oRomdUt9fwhuQ8Oe9PYB7PLaPor30NQ3P3nzjtIA6w4/MRmFUOSBS3DKMU4ZdkwECwl+GyheZIHFKXGmlAuuIS5iBBKgRYmD8+luImbVoVG5Ac1nYd+6aZ2UQdqyihVZUzPhRCTgogZl+OAPIbajJkOWYnhp2enmWK+CFDHi2ic3l3olXnOXcBC1ARPN7R6c3ce8cgkye/sYobsue190WeRp5NQnuP4U1iPumgYvnCmIYMpcTGMuMORcYhIqueDApKaoUyUJyxPADaR8p03/jc2DoCITqJ8N6PGO/3nwG1VHO+dY6l9bha+hO3sTy4on8bE+5EJOrVr+Bhipk+oIFsgQyXM3umVbABfU90rnvUwITZbhzIOmLLPRRO2cIWyOrsBjum66zDGLqC2iXru0rURwkqLrYlNyY69y7K15CyamB+kGkU9FonnMi8tAWor+a+3gmDj7L5dLgAkOZPxQhOya5+MGXFbJjIZAXzuMX65al5hy4vYbyyZJXJsuj6rMLH2AhMLhLC+oHqi8vX/4yIrev27G8kNZJkRMc+3RzgMqswAdNpwqxkc+OKqyisYmnKw0NSdrg/1Z83EUe+6y4pXGRpDvTjyeZN6rzdBX7IRIGCTI7X5hqgr+wjhn5Idm6vqSPdlQKrgbJV/oq1sSs8ShTVg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
