---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devopslabolatory
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB9ypgnN8zP0iHkKq85id/KsiesDXtPtK8bAlkaIdChYy92Q4XZQD+mZFGxFFfVLNZ92WwfySA6+js/eBwvQdn5DdFiRMXdW+GzI8Zq/8FRFubexcKBg3mlhHzGS+Yp++KHT/JLreJRqqxzxOxESxPjrV1aptl1rcVRbuH0FzOggokoexwEXWwXwqV9Q6ob42RpiS4NSD7NCj6kAdqf/tFzh9JhVZcNcPm+MQ6euHCh08nkBMRTXYb6LjFyKPVeAakDn9ea3033HzhRC1Rsiflr4/ZKIwcgjojgVuiJ5VpCX9REuJCssDHT7eO0sKfLBBKu07fxms8icyeQICuWf9C8AiTtknKZ+pPUVVrOGE1fBXhTBWlp6AUq6dHgsnmCxn1HXkKm7aFlzDAQH4AllShvMQtwNQpljxF3YVXmRAfVJfl6jwtbDBOAfMrwR56d8YgjF0cBwfTK97H+Cx7Z7lbKsjtr3dvu7142RS1QO/Fgt3R9PSwzhRRXQuU+uSyNKCJpBSFkEaFt6O6J8cOvdv7O4khkF6D8v7CMSrmUrazt8KBtBqByAjOBj1s6gZYmv6oRAXXu6Fn7NwYnvI5RGFQTm9+fue1DyDxxxv/TqSrgqCseJ+crLgZnN1UuN01R1EStcEEE7WrzhLYrk16DT70lO/xI6gLSfKccqRvJunasHX3xVDniFwuavv4veK6ix8fBtxAkdB8zqfUO4bzDbgQsdELHpe63mxRfpIRdBex1+dmqnONiFzCU8tP2ok7XMarkLvF02WtZABlOm2zbafRAU/yzP6IVRz2VI0yjc4TAF3c4rxn6LOVUL+3Q8QPruekHZkrbhOsU+R0uWKq26V5dcHygWLZ4aXiQpqnC4OfFi2bJFPBCgPP00DxMGQC774GfkuSYklUHbmWlCG2KPIfVdQ==
  template:
    metadata:
      creationTimestamp: null
      name: devopslabolatory
      namespace: cloudflare
