---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB2JTjXpInjs0NXF75RY5VSOcO0o4E/DpaTIL/R7y14bufjkyoL3UVFi5YDwY208BPiUuyhLVlegVLoS+UJFQZ+pP7BIpE1//tW1B3Haxp5SQGxcqyAd32Udd3K8Lm6hrFEsYRc+7ge1waQE6QtKINOy2gDUVTm2antuwR6tUAXnAprJ87ColJXYx8k5BzJTWf41kznqERvaEQGSM0XaBrnsIxjV4pnii6FrW2HWUlOnoMPO7xAFFs+brRI1hX5Pb2a03dq7+KwRHc3sTm27c9FlOGY0arkPmlOBM7lo/YW8YOHSmuyeP6rXOSjcOJWZLX94zteHELLjrJiPnHK6hrUZziGnxMTUmRDlKUzh71RvOEGNSz8T32pBG2/jePq91lOnFGjXMIr9ITUKNLlQ0mUjeuvtxy+6rg052rrnyok42ErrWXs9uZBlKQuXS41kdiFULEXn55P47HiuLChuIGoVT89FbvEVTMfMCyl2IXUxBPVuwHPh8w1IyMsYHTwDBoRqGfRuc9NEDjGWfeBJuomnEwRPrLOJAUJCCqGuqgrltdL+U+tswqqXKIeSSJyGZACOaQPLYD3Fo1W6UH6UF5AeciX6FC3BoEMS4fh5otXL9MVhr84b3BY5ZSPt1JLL72AixFIZ2yR1kUHMEPekXZaBsr2Owr/EQuQYdw1vtXywLo70dIbK5iirFuiT42qzUgi2j4GqkrHPF5eYy56VnfW0j4r0G1skUA1Z2omm1qMcew70oqgql2pZd6qR6UGDcDdU7pLlo9rbIn89M4/kojP0i68CRBeA5Pr3kEGgpbdfm7B+4wBELrDVo1kxtd4Skd8MT/YqlrReIUj7sFCU3yHnlVXUz47RuaodLG8UOgRK5H/JNcG/T1tiCdgqsGBt12ucogwc91zItXxbEi92k1ZXg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
