---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBn2FnonayJPKTlHnIE+jKWqkjGVn0MeKraCdqFAhQgnM4kuSC0dPQPe6WkedlKszx+ThWOAHu/FPMRW6hDvGjhQwWlvlfUtUOHCmGLWVjdwg11ZWfvCKEivEt52vbcNrJPKK/GMA4PDY19EB4Ah3Kbkhe2FaWprWyBaro1rIGY1f6lZx9OjwLLWkmRaqSE1D1TdkBGtSxY7cugWShH71OzPnA7xT9AU9QW1162+CIyRVMJfGYJbm2iFwu6ECmhED6HWxADqauDu0kwgjhEpIv6Og+1MvPw22P5UtaO/A9HSzt1NLdDA2IQ5M6TiVMoI0q5hhTBQ5F6OJIc4GmTqCmSDNRklJpl9Cj2vLBkzZG9RaOycVve3PPOwGeOBiH6x3Ktw2uB6zhfkingZS6OF62fyQLT4O8nPfxLhrQNJZRa2BnLDVrKQxiegwalbmoeElpOcNkWx6TTKYvgKcTLHcRzbFj6CoUQA5ByiWLx9mOtyt3u/JU37cRI+CVcJS5/Tu0ZtV3EvWU5eiH36v6fyTvpi8Q7fcbnFMgz/sZTLCBavIGdsd0DCLA5qHLOItlgjDoqSESb+jUsUmNMKWnzlJHulcwwUQ1WhhqZ82IZwmkc9MEaPfFxKirB3h1t1wAfXkd39b6wx3b0ZpmdsGUZzug4K9LngHM3ll6QQTz+zhFUAEo7BM6dA8wqu3hwVdWiqt0lW+D/mW/u/NctFu9xkq3mSGPRG5a/xW7TmS1nrHHr9OaT9rYML5+5nZDHeUGwSeWO6cqYb7jaQbqRGwA5WzMxSM3Hr3AvN3h9X1tz2I5Oith9LHmARsg5jmFxuWX/Vdt1U6fzUYbSulxBsF9nJmRiRm2OXLKYt0T+CN4W8S3ecr7+MVJHY2Z2SOjJc6Rh2yLcMh6XpayNt5V42ajdpoTExQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
