---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgATzpWCqIbPDufO/saZmOoWctUStwI/xGlpjyB91/iN/aX5lGBlhttT3dckfq6rlR3n9SVqpssZuB/pUoEm5TaiJZJY86K7A8RI5vZ7F50R+nAY7E3nVDuGQBa+6mCwwGLI39Q5N71KNANgjr+QwSph/v1WZ2IXi4HpyotXvpo+NhhiZKtVeD9RcbrSx/70/B2vszAU68Ud2Lb8t7RIDwldX1nIx424XeSPkPcTv37wMnImQAoEv9eAoMU4MNbTEnfIiL9FjXC5oHzDicvRye3jk57WQ92hMkEczcb8/VqTpyBS80CWY3HQphisHtexizuxINLAjPkdi/1KYtJmi2MyGxoQv9UOMMKDWn3K5+9zRwMp1jUKv3LIU3YUSR5uEeaFNbjVv1+bi5uTTi5TBJJ8UVeOJNmHXsVnIdMAZmt2XKrYfe1eM/YZK+wO93/TKcjMu1jHv0n2lH53/wQhKusZgO55F0ezlqNvX13pVjHJRfTCzbYdfHvkE0LzHI+FB4UoufgFiYClEkdHnFoJpQoNJt7wybgKpkR5tXoojb3VijSV1uTRY3dm1FH4jX9HMY0Y2qOTFlWoI3l/A0lX8/5j9Dkc2+M8O8bkKBGUtlxJU0lUR3BnN76jKXV1xYgGGgfbBQLC527T8M8G4+hBSMQz16v4LtOpSFemx58KaWeywAhqI+W0hWNnU5LTXt8Mz9L0KMgNNTsdaU20okbq4Avmsj64SRCxQ+3D6tAmzmNrPTuhYPHjz34e
    email: AgBpx8CNzegWvQjUuC4W6WJ3sI0TAncPdutiJ8HQhSlYjVSI14o+n1FnPR5ggAaffaznE4+kU/Te3rU/GS+kd5v65azIRoomlUP3gdkQ9F6lYWxy5k8UjhLFlQrkg4/Xx9TeOvPaHZJ5xPZMhjM7A6itWb7bmzp9TAYqQjInjaxL8RrBm1LdnclDKNvrfkAFphIhJX7OwYTekdkenEjIP63YKbP/PKTLh1UQHlvJvNpwZ/BwWPY0p+F02uAGHmoYJZJM338WiPjOC/4FsGViRV0tfEVOd/oVksYwxKFXRa42fi8BIJpphYpGBA9uedAaj/qL1Yl0ciTcltVSHbn25zpEaUg7r3cKsG4r/1L67yTjQlo6cS+xU9QWgWVCbwYpRV4pnFyZ/oWi9Rft2YzEchEAZKqY7xrl4f27X40ik32wJ+C17zVDymZA/bx9c49LuoHRV0EGCzZ/fm4Ehi+g/Z/AGdd6slWPmTvsppGsVWTTrxYH7D1vddNq4fu/juCNNb/QMu3vvC+kBMgycJPolEYgrQaGtO6ARYlLNlksP73VIv6K6wLcqLdf0R6YQ+gmeSsxZ29Yq8QRzOPtky3PNC7b1lpoxJcKPxDhR1K5BF5uzFzeRk8TYdtdejYMLKn5TEhLz5OMLAn09KRZxzzItXFczFcGby9Wm5TyxjcXZ+wIu+Wgrj5rimVEpbzDkqbMIFNRkIzxsuv8oF1cbbZzO0zK9yRyZt9i
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
