---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCdzsaXFhaKizFsA8aMPXPW1aiOhe4vMzO/v+CfT0RP6LQBKfGl0E9P1ySzIGnKIHdzzaMxcLqTgItUu8uiAJareL632rAxA2LvzBZdzFZ6xQzkSwB9BVzxcNocA98A8IL28NrKeB/rSurkANngud5eF77LpVozb+Ku8HG7N2fBRbTmomqA//wbLy3eLmt2ze1Kc+x9p4QfNxMjcs2oK14JMYKyH44Vkl4l+MraNovRWiFVL6+vqHuQ1ZwbMhRxBLbAYVl85QmGCA8K1IjZoFteqHhr/nyCteP3oeqd9f+mHxt7UaKC5+D4foxvwAOiszznYDV/tnbmQDDmXbCFWp4vElrO9pn8LyP3b+gDStiranbdlWYkkoxymWvJejIvZmEC7kOxGBFUkSq8U4DrRmkCf/mE1xSzTXD+UaeENOHf5rgb5HLCca57bKpjEX/je4IeLi0Ad9cjTehHyXlTPP9ISYKOx1Rk1V1ooHOEXdRrdo19Jab7FIVPLV0RvtbhSnbZwCqGNNhUYkrS1fSe/f7CBlIJUa5nQqOB73BkILAkv40m8p+S8JmD6miklMyaIcRzKZpE6tyVOwZhr/wn/tzG4VzslGkbx6mN5hu+PKhmh7kooMerU1PDsT3CSMrNk7kvqa3yFfGXnrqYm97rKOB0+i6JmcdDYeDTB9DfqUGFUMb5x6BSb8IbtyrgvCd/V3MRv5WhMzorihZ1vHF4XRqqP7aM+gfJ85bIdBKjJu5ivd6oNz/4hpK5S5ukxGwmtNo9J11A9kCctNyvXXf9mIJMTTF89Obkf9gjAfezU9RRjqlI7IMS+/eUH4AJUEijLQ9u8pz4ElNkgclUWaXS3o2QDr5Y6N23J6U1/Bcy0JZNMVdRUJ3cH6Vnyh7LsRhLlDxJSpK6ieL6A991yMOOgv+l8g==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
