---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBJa5UPIosT1/cypotulgHeJny7jHFATcL8Me8+OmWbFlA429ze4lPaN9Bh+ILOs0ENNV25lWsInDUQu9Qgx9FixrjcjxQ5PcPFzaQ5gZ9IziMzlu8DZsDn13KojbOJPnx2N9FMcR84n8mmkUVptSjLi4ISpmwI2/V9BCvfcSgiinnvXzk/4PWuJPpLjTODfpRBpHpOn6yJXbas1i5/Emk0nosn0shs37j3N9I0VdUb4iCVy7+TcFl4xUMb/+fvRzu2f69ttC1qDkwh/ZyZYFEE5uNgcGiLntvfRYx4SHOzeyZgb2VgZ0zBxnvs/diDbzwIPha8wSmoCQHzdrtV5ApXCOXGn0EjqCWNU4U36Z4T+BV3kB0E+c0SLhNIPNwn47TNgxfJOoW5MZDW/gAmegQX8SJLsw2IAKOIQV5f87ZXSo35mAkhGGxG9WHCGR1ZIr0rjkpPOJRQ9WF4s0NNJyRR7xiHVolxIkOMvs0z2JZHfq7aKJ0L4WlyrQywFXrw+18BhO+Z0LKyRKqekRYGI4yO7U7Di/A6sIJr60af/mN3qpw7VYNSmwxtZmP2xuNCzot4Y/rLAnFHWvHlB74v/3Jr1NLgGZ8AWB8blQwHFfo8Jv6NhH8GmlFEpzH5t7gs/1zyJwiuq6JTrO6QNrtq9FXy5PVa8yBDhBBngE13W7Qcq5u0C1DHTSVSKgeIgi7JLFKPKb5/m7vlfkEIt2rneelLKC3PPZk8S272astgVnuudJ/Gusuu4mIpIU4goYG/zpzdw2t3QldR+vFoFohb+5xJSqqwJUqNzc59vcsVYWO67pIwDfPBckgv1eIM7+fTySQt0IoCuMNnv3LPz5r9CsYaC/qq6hhuQeZK3M7ipufFiQhP8iefsDLWryjUUAzueX6//QsnzPrhZXoxkk+16nY93Q==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
