---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgA5BVDr3zmMGHgUWGCB1b/e8Mbgtmc7F6onPoxaudVd5kzotbg7tUuLHW6G8wiNIKZgiyV448+dnXSos75j4OoA2W3cnkSBcDLstauv4WYoibapwF1KEtp/rY3CiCG9Am83qEkyeG5uObhO6NoL/tXdb3dOnkZ0Rj0jAu/9rYuTtrykyE4x2EM297Al9OcRW8HLg9dkmOCWndH92k+v6n4oZFjI1vK4HgcdJM1PEjcQYMIR0gV3Exxd+K3qAFqxXQAwEXMqZ7+pFAt9Tcp2Eiit9Mkkusnc2MVB0neslD6ZA0tuxIlC4qCCPQRIXkyFHcSwjiwwFwy9oPDSciBax+hnRMstm53PvOiHljxH2uD3ZEokEm+AgGuhp/gdAlqjFLOWzKKAxGl4VyU+hZ6p40wAEk/JJkd3zn1/nAi81kyfnyIfdh35UMnz+xOupPZv+rCMwXq2SVTQZ2GPOdDobCe9+JcKFACV9Uj3Fok/p4LJTr7mFa2s4rkxGDlXjfmZwf0LfDitgY90uMOXtRUjYxiILywAwceWBk7MwgP2Wo8tezKabYwl2XuTcGNPTh6bL7vSvQyzNkNWKe6SysxovNO2ZIWfTgZA7CxaypwnUGC/kciOzxPDbsxe6QRibg9vTfBy5AseI9dX5zkEZ376ydb6XzJeBpz4Ax13rRqVKlhBIruJmUhkNGfVZi9lZ7ULCeT2hxls41TvFSxxaZN7v1YjTdeFwgNHYcZ6csJG7d2fRNcUvVfLlGuIEyg4Ve7v9LY/9Iypd0bvntEDUCm12n5zqkfSjTXlAfwdRf9EOx7A2ukbFvp8a6YuLmPkMV9NYpH1MeJxgTWSxJZqFwxSbDPB3aAuDs/oUq0NoSOs4o3qXbFwJTZU5iDmGtnQp3xZQQ/fLaZRbCcMhNZCRZlwabk+iA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
