---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgA4fHfQo4mHynRAcLQkfHXnQswX7zhR1W+Yn53mFLwiyCFicWPr3YklAQ5ZQvPsixVKbFf8PJVwwhWvQ79Uf1Bggm3w881f0bYsycRHaPi/1aS6PtA91IyFvI4jzx14cvFbOHsPw5SK/Tsk2C8x9gdLjdW4s1pbSBw1vyZ2nrtHmTeSN8iI/O+eSauZz8Y/bpZbTNCvJZt8jDQwJxb6veAHkVU6rcJB+lBuG5UgpWxTjUaPin/b7Jx0xdosZpO7mG2+RUgOgNNf8pre+2gh8m/DUqK3J/RAAi9osaDgJv/ud6h87rucpBW6HUr827stcgFd7xL/L+An9Q+MmcePSbh3wDHFXupnKPxZe77IvsKWJREuViqhXhXMhPs3jU56qSpTsfJKWgM07KV97wuhmfiRMNqZ8jYzFQlUpmiurxHwGnjja9ugF+M0Lm7fc1sTaJHLdFT4A3SlniFUIwKX9N7cGDXYYuGaDFSeIB9kH6CoYwxt3Yptva2xVIJVj25JN8ZuFKy7r/T73NT6Z97fecKZgs28MFJ21QbNCFTgTkJ6dvShnUB9ST5Py5uz4/j8D9MqQ+SW2TRw9KKsAxtLZxxAp1Xbdw8MGUtmmgQGLlbS6mwpaY9IzB9QxzYo6+/REncYqBLAE0OGqUSXWBRamBMl8efpOS4TJty9WG5Xed4/28ejXo9YTShi19Pzo6ZrMrlA5gIMBM7e0XefreeiZzhT5rMenwE1pV+J0j48CvsPE5rOATQO2VX9
    email: AgAIKCkZSKXM6u2jqsqoDQ0e2JR1uJXxJJ6opT+DVZ+yolFq3G5RFm362vnrIO8xnDg1w1FfZ4LShvaITMtPwd+AqFPbG40Cj7hIGrNuhnnxOYTLIcgUAzaqzeGtFp1XxTzyS58U5B9i/FPqcxc46NnbaNR+ECmOjM19RuA2ryD5dOg6Wz492pzvx6sijwdpdbqpZr0fmvQ5LgNFSEmqQlXX+YFLQhHKdoTKy/7p9gDkSway1cQvPMSgNS3MFN25cMUOf2RjI+Ee3kRNqhkMKpKThLo/CjWZ8AcpE26vFYvNNnXlPnLCioEsjG/ho3V4ouGN90XCdb5Ruyw++uAPDJnbgPt/rYiGthqZV1bhNEpHlqUIwuY5RIZOBp47ziWFlLLz8iyST4UHKScLKbrdJM5nRj2Mowz1NtjPEwC19E8B1Om7nj9cW8K++Rj8WZndtlW4AEUBtUwHV7EASvSOw+X+qNNKKEMI5wH11tCrmvpbIwWMHAGbK0SQyQzxiUP8nTSGP23Qkzk9to+HhWJDezPnzi9nD1Cwz89Y2EzMXXBaOIkNKvhgIXz2/PEcraRJFG6nvb7V6GAm5VTWuowY9YuZwaX9jo5MuQaFulG2VlZJ0B+urOtLBhTx5nr4H2pnymMQm2b6gM24hTJ55f4rkdkOwGNOkQ/hF8r1ik0m9Hj2Hy0WS+IR4WG1cNMJoC3sv9p5b2NUTrKNyNzMy2qA0ioVeqbrepGv
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
