---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDSRuruZJLOfYLMQBCpmQjCP91CD5Z+hiMAQBWZiPlmPHrYRzC7b2wj9qK6HwCuOy7waR+nw5cRKJqqAbkCUbz/N2UB59z4AyT1RTDPxoLR/gfXn9mNJhfg9rGJS9hoCQYMF6D2MIUMgdVCs780X+1lPvIN3ICbr5qfQDVBHTTuzk4iYaoh1DY1eAN3yh2aHX8NmDmoBxulM/CyVlBOLi+lw4sxsbSPzy0oE3sugDiMg2PDOD6c5AXKXgmSXB+3AQcjVBc4IX33FS9Idp1gJ5bnYDRPCbaZZqI1BHsNWafKBq4WqT4z72bligPEwCDBjBsxfkzpDi5U6VatZEIWJrPjxc9lMMRzGAzX0mfYhvrjAvk/5yca2bUO6hX2qDG20bfuUX14HIUoK94bkhYSiy0wMKbTnyI6JH5t1gYzsBvKqxwECTnHnb3qtiYEe6xH5eybLB234Mn5E7hv9bRD0TYh5cL3oeArVDubNGsrNVi7++5NWaJDeMzMaDULptfaxMfOPGqAp3iWrnjAdBVnHmPBJD2HYDb74XPdxgDMng3UIOgltqSwXg8ZMbSBuFFgMT3MtvPhb1we/we6Rsi2KMbH2E8An3TJt5iR9ZDy6RysOKWRUpQMjQk9My72gV0UML9szyAXD67cugAn2rgI4WAIRHWaPtegJU77z/G9Gak4ZfBD/wh0gT+cMOUYaDTlGNfnA4qKDIjaMdXf/q3MWWO9OnZaBSd3j4CSoivVeh24RRdbZa/UTUB3/prnhHixmCX0HVJX9PYG9cLIlzQbKkeecuX/yEQpc/H9gaSaPuknojxubpeP+687/GJIS4Y/OufkI/5ybQtlEuGbtEWfikRbnbg3LK+KHrujQWx58HrYXOkbpJi6RvS2VBKqPIpYbihmH3Z6zGUb+A1dZsPTv5usGQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
