---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCrLsbzw2Z6JYHK0BrT66Ay2HXwEnfmUizLMgb9/UrUuNN2tdemnIjZh7qN0pygLQpUg3AmYYQGcGbCRW6NnAf9l7JQMYCiFmBVaBhD7Or+ZO+xTPADILrVVQre9QnbaGygbJssLt0Rz/wCesiiB0E+NP7qsOWD94T57zmzA3emZsXlHf8gr9W9IxoaTOROKs7YL9X8vV82Oqc2+ef8Ec1/rv5jXmrpDfZPufU9XZy/wBjFo5RO4Tcs25T40ENQVGRFdfEKZMgH0Gr3S38EYIYezSFiD52jprpnHaCShXQWsTI8Cq/fjRUsQJR4o440JVcLFJN218y7iXi9A365rltgYyGYfGojtA1Y6iAD084nm+GR2duQ9wdeLFaKVQfBuhx7TahH5IkZAdDDDh90yjOaWt2w4p5I1pxoAea0hkU1CjSzRcDo5TRmgRmx+hfwnXuRAdreWgpnrJ3k7/oDGJYXCBpvqJhQcYEvgUbu/T3/mn6KV6KeKkg7WmjgKHUzhZ9zDweNis1HXa0fw8jt4eCEKhh9PMUNYUPuk19tiAuHJAz55XnyY2IJcdwGUycA2u+agqkkNFbvhLQlKJyVHneuWbOuMzRvtVgqazDp1QUAFpc3XnFvJUJl/9KeRO7mLXLc8tVFWtZCvRbW1kvPMWOzfvEudGz0y3pq3HYIy9gbiSQJ//koPOImmx0TPFeDkwBylogZYQWvXnC2ddfJBkvKi3FTjQZ8iSUQAClePcSFgU5vg7w51Q0/Te8zjjpdG0eMAKJCUrvsxe9S2lcZCArXPEvJPbaIkcsXeILgIQAPpOk1TAOJFPmXhx5eAdcDhlQEIiS1fMCfYMcXLZq3THJTc9YEdUhZeq6fiKJEmXn1ytQPAGp/8Nn8giDRiDM3mDIYGfs+ju/Pc04mh3oeoCyyQg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
