---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCcGIv0udUVmpw/ibvoGTf8ZNX8lvJ6UeifgVPu8S+0fErjSD/gEBuSlvrSKsGgRRM1N9Igj0hf7wG834hvd//ffOZmIMxzxUn2Knxoc525A4Wxm+zAUpEkTtraOO7VDrZX5q1St0mE80ZTpefXyJRqrvl65XI/BC+zAY4AJWhbYj6bQrjt97hjf3Vw3OYhuNkk/6TAhjg9aQx1m4qs96csUY0t/XXw66VvKfw5baqJMOUbb5dtuXJVng0BsDZX/vDo/dHJCGl6Ttf6238Lz+FuGZU5VEIIE2SYgAFtD9iW6OA/sk5xYpLvaVORqh9XR0iiWCtqRb12DCmmFu7QIi+t1mGSj6RvZln9PPZEeVHzLtMFRXGjho7xCrBwMI4z6wOvDeQtXbpRAFffksOMv9+E8Y+/lM7MPBzhqdixcrrgcFgDdcexTndhXNJ1sBhuGvSuU17Syt/2uOa6jr3JBdyLFJVgSQ3pXM0s1fgtafIRAiroNRT/piWusJwnf3opZSqvhD0GPKuYCaB3GIp79Fzo7Gl1eEVkAsI5EIaOL22Pky5LSqUXZbXJdx5Vjd4XLShiCxY2ZvHQRS3LbkmPYPejCrQlt+w1Gc2+FEcCrcL4M++9NzOC4jEGCZ49xS1FG3xXhZs6G3lOV+Y5bEQbq4HV8VlhuVbXpSfexnsKdnlNTDS3Ob93vQwn/irhdEXGAhmeldvySkhuUmIHx7i6AEsY3rXIvgukeXHmd1ERPFEJ8D3OJA29rIxYPm1zMC/t9xFR/fhUDFGYuxjRNYfqVL4F015imd802wbRfOF/KeTfQ9G8JLP3lzYEtM6WiU/niuUU8F5iacGr34vw1G1V9wB8+bxPKIvJBQbxSqfIGXA/XTHWjts3hoOfvmb0wYwniJjQ6zT7RmYMutNbjJ4OV7Uetg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
