---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgC+a5+tQazLNPc664UtAP/RaCEVsBKzjS33vqS8PFJmiB7RQly4X9wv2zEZqCw3JH746l3aOaguAd9jvceCEn5wPKM2qkEQeOgZ+EzaCQapUAagxWjbRREB1fWVJIDsSne6kGzElI72CCdFZMdzfdWLc0wtzpIJB9Q3N3+cKdHU5WoIOeFim/MzD/nN0DuCRdeGEC04GhqtGT9Hlqb8Hfv7A/7cm3ozsRpa8BcmcrGwvZ868ue5ioIIf/WDeG4cHPGGAR6brIbCWvCNRgrRKDBDXOeaurIpI/IwQamJZ17Lo4DF7uNA9YllVe7NQSAg8P5tzTnhqs9u/r0AodUO1zauzyQbd7bCGtt4Z0VgP7UknaGbR+TkVvx12IGGFDEhHjHOVKfD/owZ47X+jv2joSv3Ml66oqTDShWibnzn+E794N6+Umin5gz6jDM2dP3BE16SVO5iy3jWaospTd6ZvyhqBuWwQYJi3MOgyqbCcSijmRbJ9EhmQ5o6Bm5It4e41X96A+K9uW6Nr2vuICV6ZV/zR+oiKfb1HJmtsLRpdsywdb+kTSPuKJNF1TIyS3KNAvVlal3Vy2ENW9SHYdjmVWOuZvpcqYuBRu1AzkUKGrUdNm+Zr1XtHBl25hfazkurcmDtrC7/TtP0bOOpFkeVm98yv/yKqtKAkdcYmZVkFjBB0O/Oqvg9u/NwZyCSsWc98XUbjm7sl3G+9y6TY+pYxACwXY73uTAPEpC5mb04UQdzIF9fwpHpZY0eS7s4CKfvK+HfVxecVtDEcircVDzA35iCnbRcMVrVTADTLt209uA36KsKaAzlNjAiq0UMwcEnHIqZzaP+7dKk5UMscWMEDJgIcf1DVY5WZBRrmM5ULUv+BbYwydD/tZdq9glFsj/6c3Bi/LkMcEwBWK88sU67ekg3NQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
