---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCY9Jz5FMZuI74RgBnfLcVMaU98suNHXIm5KxqmYaPEg6kk6sAuNGJb3+hC/N8G8K72QnOo7WdlQh8itwt6RH+wqEmYunm+RPzumHVpkTKyumAKv9f+5eUfCe0F1NuRnBaXbYJ5/03sQWPugRK8rMknX72OC0QNYMddfozTZM0MJG6BOBCoNwAwGCapVmWfZTrJVsCAr8lsh2knaaYhHFWGNt8T4GQm3gSxonoPkpqBbnLHSKs+8MelR/MMZ66HA/OjizxFloNmRvBBm5O6iXT5vd8zhvJ5xotceWXxJewV8YyGMNywG73Q+nYDGib21Tg3unkdun/28lx4y6AvbyO3p+EUksaMY92abiuSTXjggheL75EWXVfYly+6DkPen+vqZjdYC5JQeF30ynf3NDGF2GNKk6GjFwW3cmZCI+kl4yUay+U0mz/hnQUAmV8/1pO8EgfT+E/p/OOquTAk+ZaqddilI0y4kf67GMLyw6J7Dx8D5wSQaq8Uoo7zYYhXdy/ngAGgqGBhIS7CxA1CkY3sACP+SK/HxY/pMc5jvBy39i3RPhqrSfHyaaX3/jTNBhCYtwgG9ucn2iwdOeIijZx1dgxlBgcBD17dxGfPiOrZRiNZMNUIU2RcprgOjRun3h2AvGtnUwDH5pfTOUNr96KFjxEDIlT023vHvB348yoARWprzbcmC5VZBFA3Xt5dXBWeOhx1gpJVRkjcWXu+ONM0AmG0jT3jXOyQ1NxSBUSr/nCKDYNwnst/
    email: AgAoD5oEdtNid70uPxt8VJez0aLbv/aXNECY8F1A3z3/qrES+LgUdqhmbtvsFRDXNyswNuOQxXZrdIG7Di43NlIefSGJFMzDR/++7HDL88WKiKQeO4SEcsyFqv14OgFL50b3vCAjnq6lAmb5CeWo4oo38KqARpaLa8xwd2BXwvtM6bMMsYF5tmKZ58o4Cpft5iaoOgGqWhWVfK3nvTIU+zWxaTFQU9k6MkkfHL6tE53qL/aAHxJolEQANwdfuSV+k//xnlVk4kd0nZKoyuKj+ySUusNgjjaRI7jgTZccKOwZQ6XeDXVm7dNdyTuvRMvzW41DfW5qx/R2Z5HuaIk7Tj6kgFMcBFxUO182b77q3d5bjoxlOjgNe2LnlaH4WGrXqIClQnVnLr6RcPQSiwVUoDtI1t0MdptjISlj6lPD1lYSDYpmGP/TYtmTPuE+j0E9sGlKrpfG3L8yqlLQOQNMOY/YGMWwNUG5PPwOmg7jPsQklmWmFmQws3uDKs99DTNS8gYKu7AbhJIQemNX8090m96kwWg0evNriRFhKgiVHv2030SZOqmxdzbpfEHI7EeQBI9BBoAF1ZxwzyROmjb8V1J2nu+DTO2Itj60ZBHHUHhP9UZSUGjD6QzTbdjW99PiMKbkW3pyCEkSSkj6g4of3Abn5PLcXqAnlNhjb8A7/bfU1Gsl+rd4Jwb5uGC6sJYDKrvWW0Sq6ivP/VlmI7w71vMLmPt1zTor
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
