---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCAusCc2dsYu4u6saEldhHmMFbZimK3ak6zxOkSk2iNf1MdJNxKL9TQLUZP1V7RiTfwFKXh1IdlojfXcGu44k7Tq+CmS/f5TofVx3kRCzkPqewpd31Kct7r7g7TylAyHtnSvYBp6BR/6nhU5GqG2RUK51VtyMIw1McIscikWfw5qe5P2IkZo5smUNeGdExQxYYezxtQzDcXX+Gp5iG8zINE/0SlIAptTjnL4GT9GGc3pOV+8Uq7SRGXHSq74y/QRd75DaZoPRjjOnJ0oHu4glef9EBpS6P98xyCzpgNQbTCdZnGvyx9DRp8ipRmExTVOxeQrkyjRJ0Q9Alsf87HXwua7IyGGi9cyIDgHXaNw3Jf7DHztaDkWAebp7aaOAY2mNahLB0ZD9r+wW0Xe4DIHPUHzpFwsyPjzlt8BHA7zd5gMaErJBdGsw/zcqLlYZQxFmWCgGlIuIi+atNwFlk3eR1XFr3G0EhdlivHWEy0v/G+ajaDSbnGREJiQmEjuTAw2WbWo8cxytF+Br8TAzHdBAaeTayITfcWz+6i9S+UXdlcidjPhmmpkrd53Wuq19NnOjS7h+xNX5fAeNeXij80iZYiWaMR7KOuQ/QlCxgi/93222q4Edg70Jh+kXO1ulU6qTNICb+4tFUmWNF9okjKQQIfF/Q5EeJ9n1H5bwFafVbwX86nxHpwwuJLsx/g1kKc+odbZ+R5cR8vvbxP/DYW+FLJIVYuxRuLbe6v0nP4wfRKsXiGWhS+wt+u
    email: AgB5AsosA42yuWzY/+uPdRMK/4bbf5ADu6lYREh9K060N1lcEHUEuzd0ZsrHsLKYMZGF3K4d1gQZcg1G7NyNHakENvO4Qp1rFgxjMnAWWGW5aEoX6G2CCWGkQRP0jVMA/jODo9VRVzSgFqrN1aI1VlmBH2ulwyddfvKCrghQMXWOt3FsuB3/WeSLEu21v/OBZ3zOmvhErj8lfY1D/bdIe/kv9RQBzYLeey5jzEi5O8bV8cQswJ8rkiM62uOzcfvb/jbf4KudsszChpiHlzeqZbgbwl5D9OyQIG2gbPnkBGB7rnxiR06hB5nt60znFYb0BzNYTyspLuZgDIpsc6e9aPw5T2+SLbvC79bWR1XCu4mBU/Umg3B3VwS7V74baHwe9nMtXyTg3+pcbg26OZzTqCcKk/eUmcfXgkQwTPsqHdjm2xEezYaLo3uj648DUiP9mVrls5VGBvvcN9t5t/WqWfoM5wlgShFMuepf6YaZj4+INhs5cjI/IhsWoiSqfcb89QjhnHsQPlGmGUH6RfopMeYpBoTyhPejqNe6lvvoRGCIAnhEDoH9Xe/EWqTYTmewP9ibIqQTe055eQJFvxhvBUDauDWMD0+WVO8CrwMAUo0yOlec/nrW4nfQMs80OYBkAFKX06Ox9ZhT1RGYRpBwpk8OqQKyA179xZGtRHBc/9SCAjKBRF64crFDcbloZzbGeoGo8mBx9HFruSBsvs7mT4+vVH6Nj/3I
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
