---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCS6dpspnfdWO1rToa/phvZ4HU6W/JAVugU3RUFAWlsLXmx+iYzrLgCfwtXXuI9j0sDmILd5ZWC8q0LDB7nLYHnGBwfCu0zpX53fEB6bbl8Lbq+SsF0QDEGDAHvffeXwKU8xabRreHP0lj5MyonLBi8m8Op2MkekKnQxl+phUim3P0KD/8cC+7xlOzE0Zu+DOVFwIQnt3+V0ERkboka7STvj4ZH3V8ob9r2YiQclEFO5L2ZDGNw4UDQnBnj3FT0u8FrP2hA0/qX17nAckrwWVZwmjV4Cbnf8Ej48Jm3n2Qhb8u26e7hxTx3o1z9LUz+m6Yn6KAdNnRqQJoA9gVzQeniNLBxmrCf4ymkgkw+vI4DEqdaKp2S6R1KSLyyLNHfZPc7CbMCN0+HxSpxhczl2z5fF0jU6IrmRonG3cDr4kUwXAb5rUeaLjrS010qDNuVn8P5k0HkPnud/OLHHlTtbc/yV4zBMjKrwQi4V1qWpJuBSiqOOAm9w8RXQ2p9TefiJdc4BNKnCFuuZ5zCfjIAdDtAqcca5vIBTzUBfdbtS6T81JpEUQT2yEwB0KiEc4DuM71wDHcZoDw8zL38d3I4MEUtlQIZ0qp+cvW2hYlCygDWXOdkDcGqLIovWh5B4lOIBmcjFX37UmpAp7qa9yT8pBWz+tpJSoF+BoOLRYZ9xWE8DsC47+f9tjoa1/RxqtOq+lkKgB1MV27RVYfQEwXxtoHmV0Zt1dyTzFIgoEisATbL76wKJMt80drn
    email: AgC9Qfxaxu38MIvjhaOZnRQxiC532jRsOnXnPZyS/fX94SWiAkl0PZRfx+8OV5D872p6gYo2K4LdEpBZc13AKdMOYdVUPXp5NiPth1lH9eDFlGGPQ3ncBXtTsFPWfSh1lYIw5nRdU3JdlvTCHiHHvhqGjDDWdXIojHOyYsHOms8ULgXpRcvt6L+2B/eAjAGlBuvynT2A/IPqMN4HDn1rWcHlN/N4XqVnv0p77SOaygjWlLCJIuuE1Kn6Sq6BPZ1h93GpiDl4bnjO/TVIQRT9pqrZ9oXWeiTRUTJSYNrvc/I4FeukMVSt5Bb1cDVZfgGYVhZZj0A4+T3l1/KmqsK1X7M+2qmDaaLEO2fUuSlpiy8fkvUZkKyWjmleccfc9HbV1hNr2Kl6jpxiykPaOjLw56potzmcn12A3n194CNsm256pSvrMLkHJ/py6l2xczGJWkbuF5NVU4qs0XlVInYMhSNcB8nRxNvqqXWGadykTsXa30FzFnG/9K97ihLb2QwPvY1K846LuF0OCpZ8yE0vJ+ydL57KPyQnyxlq1MGhXM3mFBXrkNVXuiu/iOXweOLbthOjUI0f/KL9CTpd6ie0lbbH/BfyBMNYS2Y6NGylfxgHP1ehAq5VuVKg8XhnOaGf2tKYEqoSUDT1Lvc1DVuyZRO4rOdGESLU/b/NaDhsV0xGOdIrd508S3A1Fs7u8fwi8BoDNWPaD8xnfEzPx4joBOGyGpbx6OVK
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
