---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCzzWotLeLvBI/py7ayNdpsy6kV1XzwMcG/HHeoKnL+DL/yMqbLzAk9SMIOgxuYf/xo2WGcXECY/0GEviFMuep/21EkriU/cergo9qa+ey5bSU2UMnLHeetq4Nnde94+N3WocaMZkqi1Pz20iWxM3OYoq8pcZMRJrH4pagHqXq9/pobtMDWfuMuFgs0mMBxPshCWyOHDbqwpB1TuV0j3v1Uyr9jfgooOdTSgjpPv5x6lGhtf+4P8GudDguJi5emp6SSKO+BO0GipVezkMI5Ex6RR1vFpgB8+P/XYgpYmOPON0/BIu9XHLMG8jYvpIrewCxc37iiXDQeVGMrv0SkbZ8WAuBT3Du3tIeawCAxsb5uvZA36E1j4Ud9bg/nlkVbXyMbHECe+tzNNZQpU8GTouhB13ZC3PixUJJbEWB0O4y9P7DU5JwWth9RhqYFZSC1+tiz00t04gBH1meu192LZ7+Qvopv5ygklayW/2BxiZkCitNUoDopyP18Hr+IZYa2I3jOQ9rHKSJDTBKSa3dRqH0gvOmx1KMTgZzItD53Wk56SYPE2M+DkL2B1hpd7lxCsm1d5y0FYCEU6KwRREsEgBkRA/0I2BbLxNcqvFseYTZIE2g9QjS0W57qUM1SVdJ0I37x6pA21c20IRIwurY3+IM798k6jXGovO0cDUZHRQt9B5HlfUHimcNSghhXwk7EWxQyU0OLLcy/KqQ9Bmuh5ALpfFlZID51fTUquc7v5WuseiGEbQHAsDGE
    email: AgCC7AKerFNYnd3P/MLeHF2hbpr7Vziitb/1YwlsHjd4+PXcUsSzVI3LwghGvPmr/1cnwm7ZNYITt9zIRPP0HnYtc96Qkn2Dvj7I/HXrZjXjS/uE/ZnL9DlBm1zSojatpfQV7RxU2cPs1Af0NJoT2bihMbFmOwiDtwtDazKPT+M2CO5QwcyFGIxn8HJ/i/ea3lBgit1Tkncr7xU42Eo0BY3PzVX3pkrMn8KLiEuVZrkCTLpcPLD3mLbPrEGshX0S6Pv6VHpn/PHslE+BBbfzcAD0KLe+gZXeH/1gkz5P5ZoQVRLeZqngCCIlsaDspcmQYh98A6VTovxkvpb7XUC3Mwp81294lCoeezTO6zttVC/osGhayFcG1PYV2f8WQn0QDZ2IZ1Gwuy+hpj2o+mrVAe9SzROCzGbn/QMnDfFykRJyvBzOts/6BJGebAtWL+PLixuuPseS+VjR7kUIYU1tYokIrIHhbQx1Yv8rrkxkNm0l5H5B3mKlqatGL18vWfb3yRWyGVoMUrlRM2Hf2rlntbaoMZkM2694627BfJDQZvmyXijXIQzxnfIEAzbI8u5nMovlleYenNAi7M02Czb8nMmtX9Ig0kPjxngKMuzSR15d9SUXsKGx/zSCMYorXczmPF7Iuvo75072ac5UkXQhXp2mtEmGuS8EUsK166rRuX34O4n3/xchu4CCsN/tTutHqGIEIc3Ug/dul/D+GAB75v3cn8gd1Yni
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
