---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCxAHBUz7YflvuVqRlxjYJ/bPqOXVGL72qHAcuxpdTrQtBHwdRDeu+5WazJ/SgOBtgVHiD4Lk+DNUS2b9NAVnq8ScLJAPj3NCENYhtsIewzW35PzymX+XrrdXM7rtwTa0Ix/4X4t52shmL0oq/rvKzr8GPQDCJ7T1jj9D5eY8OZRXMnVm8ycYEupv0YbvqALf1SwCkphLJfAuqiu6q6692f11no9OpFeEHsXvpA3dwdoGoIeLhggRmDQi+uXN02D7US02695P1YidIGoH6kS+JIMZkpfdxO576gLsUCV4AzPZlCdDV7Yx7KLpivN8rxqLnLgN3K/3zxTFDxGAvp5VNcEO4bQ7qHfT7b45TbX9bWMI8defmBozo24xykX419agxOILxxtBU4TYdeAhF0cXricGo0dbuxLHZC87Ti4VxoA9EqLHRHJ4tObspvWDq0PPHeF0HZCsULtsfxsr2kVG+2x/w9NkfN35qn0UTwd7aeVH1cQJDwyoEhtetlfU1sEsJ/u07pAAT7cVAcL5mLdemJpfL5pVV3N2TCPqYav/AVHShLOoEJkXQUrMERq6X6nl8Wu9C2kqxtZFBDX+URkjpl+MAYBi9yvM5CwaqIq3wiYNkDpqHEQJuqjqa0zsuzA9TxL9Kvn2ekZUwtF5GaHrE09Nmt7Ii4WvqUNnmRrUK1b9ek9PpahiLLqcpReAYyAVvTHa++GBSIycDjLT+OPZkC4TWFhHE0JUpkWuduYszKm9mzOTCsCLab
    email: AgB69Ikly+s7AT5Ym7oXZ7h8xxEUKKzcWNhHaFTWCR7n354mYwXe2/s85627nCP2FGa58N1zgY1mwBGousQuoKrdLP3A7dcCBoWMb5TLyQfWdITHlqQUPsOaQCM3SaxidLcGKIkN5ga7zLYIk3ZNIKdTyc7YqHNixNowpx8vjS6uGPHv+pCVBbumTHb4Mkniikh7kqnkKE+6mxle5lHbHlWYVxzMGVc1Nj0bBhkzO/b7T2f94IKdfiovQxhExzWBOBo0Y13jsTn5FsWrITm2by3M52F77uO2lfYZj+4zQ4I/9cKTGmEvEtYKhloqi+AFJse3z7DITL8bDwag1ZCPiIo8CfhOSwiiAzdnPmRYV9ggJrMvfcdyDrXXOWj+hTjv2NWclsqORvQxxBKRY5/rWSFjE3sf/eozKEAQ+W9bvgYnJTM7FQTqpEJMEpH17fqx1OYyH0BZynKTlhG031Uclhm4l6ZkE5YfM7CrQ6ToAP+XSdUTrecb/XNuJCRDxg4iHVnOF7yinXi+702lBPRCd1D+q2u6FJtnod6xMuwZpmTnXPvJ2dOVjpTWJ7HyCPzjplkGT2zLnw+suz9IOcfiRsPIPEgd5Zq8pfQOEBqwMLL2MT8vzV/XafHyHjnj0mfi5N/BsRQhilJuw/I1bnrj4jY/5BpDa1+fEOREM4U20ii7g+fmtmKkaOCFE+jS1fe5cfKsCSSyoCNTvIZE+Ji2LsvDFLr+PcYV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
