---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgATatosd/IUnvhsm8avts4Nh8Qp8pTuSAoWHzWgfyRBBxxuahNcof/YP92L7BPGJ/6sopFBzGVJz6PTqHvs61+Fav/R1AkxFlpByxljw4CXGwcave1sF2hZYrOb3IXxm8CFZ2SG2kOJsy16lqktcYAI/qAyjaeeWCvGBTVIB8zVKC4zfzHvYrITE2Vl+KxDC/qhpjXUMrg57RJBYP5sgZjq3z4660QUCBE1H6oXZr74og3Fnp7EgpxMA3QAJMEZ9H2Jd73kvTSljRNSEzaML0SNcb4whTmkIy4iiEXRH9ulVsbKuTQWOH5h6tWird3TsHIfiwo86Ofe8JDhoiKGuSF2rV/HO/JtGo4AuTP8AQitfbJHXR+V54zvvTOLjy7sb1Y/Zlrr0qOZ2A4YkBoAWzAE0xYR3hKqPE4OIUENJVHPh1jtbxfDCLCd78Y8r+eQ9GF+Ode4/m9BJppqxrFlmo8vSWCVHa2SXWIX2nV4ZWtlV+wH5QbTYUTqHBkYJhpOZtSkxIElJaMqXFocUabnwJJoUhSST2xUiM4K0TPeBRvcBSc3vKIcP9bJFTa3XHFczcgljfs10qq8aOL3+XaPScTcTjXl+mHxmJRyhs2iud1V+wVYkFoRxCdktdwHlyTBrdbBlFUfVbGhF1qBlmYFE1swXYrzMHTJVn2/8IQcfs/kLLa1M/nf9b6P/yh/xtuhd2i6upXRM4yjqFVZS97QJkMv1Hz9PZhs2CEpcGuJdcguxBjbhYNi11OR
    email: AgCHeX35v2UozWNI0v4brpggtlhGWyn0XHn/V6O06WvIm2NIkjP3Hor0OWRlYYJrgmKQM+GHqFdnQ27YNJhuUt0I3quv/JgsPvWxIGzmE2Ad8DZOeEn/sfYyPFgJXxhy7XA97U0zE+DL14FVLWx2BxzeEbedETIxiZL+NKWTG2ZfJpM6w4+mw8W75Vn8WfnLmF3xtTEbGIkpt4l49xk5OJhx/ZRp8XRoi/VtgnUmN9XvQUMpzEUAlFG6IYc1VPkyXcJCKGcFIonyV0kOYST3j5clcs4aKj6EB0i57JVzr9Zp97uoOh6Fr2wjyL/b/sqCfY+3nkLf3XCeqJNHLcX8+ZEh5S1LPpKVPovd/BGGlxmoGM896ZFTZFNWFxH9/73Qua6ikxu3y+yEUPxHBV6tM2WzgQImAT+mwloJLrE0SOwEZFhT745MfvX0+KJaA6n7sTtXKxnGWFP4tfrIgOQBqkrTQMh4xXdv8AgRkYyvmA46gX0EIbwZwmLC0FPTHKejXQHNHvFeBMxcRU+7R+xjf0sckn+3lgi0eHfMR80YHMxqQgwNJ5GeOrEMzI4DDUvCtCCvAP5cjVC1OPftKSN3yvvXnTPRM9q82l6SPq/jgj5SS59Z72ytfD0pMnS23vHrDFF3tvLYYA68HHvNqH2JUmz0b8m0TwmqrccCw2tzgpQ9GmuwD4ip37zcRg4eX21zn6NBwv3CQFGh+l0xLxuSIdEhVURwevOY
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
