nameOverride: cloudflare-tunnel
fullnameOverride: cloudflare-tunnel
cloudflare:
  tunnelName: devops-toys-demo
  tunnelId: f951b180-f316-400f-a34e-9a38aeff91ad
  secretName: tunnel-credentials
  ingress:
    - hostname: *.devops.toys
      service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
      originRequest:
        noTLSVerify: true

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

replicaCount: 1