---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgA+pZ6ykiuY7p6l8GF9sbBFzfUMR/hzkCLWD63q6KJ5la2vBbp7JwFf5AFIBr9AfGuwM/mQOwL6CFBUwqWOGgIzmAyn3DlZZ7Pje71Sqy8wKBSeg8DiwzLNMfqvP/0tx5IvTV93sJ/gpcJKDkSOfmMtoB2gihDfeAFCuIEcRZEVzCnKgDhlxjUPzp3bYKinAbG06thgHzZjAt2IPAUorrw2PXWGG1ADnqIV1I6xuipnGAT8F4bfB+6iIi4sw1xQoGptWJzK4uyCi4YsyeLHoIXi9B4Z8eAqxJu7c8/bMBJ9PgR4D77Qs87OmK5gzy8/tVRLUjMihzeHoFLkBlfKc/HIPxTJ2/jpeKkJZRUa5676JPHDBrOSZF4DfYpZIFsY+hnpzv0+PwdhGTWFHkwbVs0qN/GioMILChmsh/llXFVhzFIVx85QOq6xXYITk+NUnFehQ+W2TLxcHo53vVNIkqIJ94ZSRd85do+dTv4AAgFhXJRGCINn6Kn07jvBr0/96sITFi+kUwGb0lnRwoiqtndVX7p/P+Rlg8cRVjCKGxsA+wVoCJS2JjZ1mfyaaius3JEtNYFu6iXYgUJDtsP3okY20U3FKrApUNCTECbJPQYZRlAscWvbamQzGU2z2e/2cevVlX9aR49VETXy7oyea34m0MASxGx+55ih18CAv5BusKH5CJJaEys84uwcStr6C6+xDY/VvUO0VKA=
    secretkey: AgBAWWFzbFi08q9xPbVCpm/geDTCrN0qdQzQrEtaqUarzOF+YfTxTdUbLwhIFocqO/JlzRJIvNq2xC0koK1TIAoPdo9oaq7QSdirNBMGZlV5qZuSDIYsTcJ2x1U6o4YFqV4l9VpqwLezHKQWkZ2VfEbpzg9rRP56W0ZkMLtPAuHE34wSxt05ejKvoAamxDfVAqMZVoR2c9RI3EzlEL1+VLWAVIQ0MkbkNcOTMjvlXiTNbPsZJp5U7wOXCkJ45B/nimXRsI6fcIIf+0Ln/71IOl+9YdkIn/JuLN6osLR+4wAIntXJWDLuZvJ/+XNpQLUDoYxaMqp5mQkaQZHoDKC1242oOXOooXfk/VPBmeJZbrz2PPLuvtjG5nlJ8cdwWofG7xdbHfluu5xYdFmsrR3kc903HOLYuDIwRxz13K7bmpIHcuDZO4W4ENu/AW6cuSfXKJrKKV9hUNjb6Bgvl9cEkVXI16VkLnvZssRN1gBDYrKI/MNsXkNE2VJuheDUSYrHtgnkC7TGw9HlKhDfr88bHvxn0KasJTBLRzpYhKn4NjW6gspEEzwl4EMmE8vLgUpQpDztkf9vYbxr/l5ZXih9zBvq1HzL7frxsLFi42jKpP7l+mLtj4jRoUENbIG5O3GAcFR8MELDncriy6giqr+ocb5J3Dk2vfg6j+lqAT96kKzevEYwD3LsrkOIAlPNAIwTtUh91AKQS87vPlY=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
