---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgASEgqPkStgvAkVOsVg7ECuYB2ZHOmPw5OGclcNYPI66W6M9o2w4UEkDLY8CTi8DoDbr6eCUNNZ7xUJCgNY28xwxc4baHhp2ZXR7O7jAtsAwrJyOFanDyvXqoS7y8riqsFMXFG9hv9zT3Ut+riqHfosqq5lDBJ1rnB8WYhYwcd5vNAmoTW7kd5xshUqGQAT07N/ZVxuB7NnAZKCTdAB93OQb3NqQHhexM6pHhvZW88Z2SgXT/gbVNbGmRR68WDZ6NreuOugE328os77vU8U/vSwY+drqtKkmBPjLr+pBOFdbHsG9o5OodW3kr1mcwY58BTyKYfi1BnuupIdS9tkATemrGUccrKZX3ZKNQan8xuiFRKiONmL7AwaBjQ6vqGBMUpWLnJj9Q54JT0xLNkTAKYURqZDtwQPl5r7pnlxc/MN+k2HNdk4ZOTjySB8piOWw4bffzBLl1XYwQTdKUCoC5R/1ht18elUvRmkd1GRt7HE03kz15AOwxe4zbpDqfqhItR6Ax6ut3JsQqFyaqTUoe8v+MBB3q12m4IsnoSXf+g5rZT20UJtm6CPCfSQEN3DIgZxqUTS3w6Q5q7wj6NHjslu4XCuQs7vSa9UfF/uKz2giqc3S4BFpnGyoOhJmITsSnDaRDPbhvArr/Q38XMbAC2YO98fatg7VQXntlK/BdVi4FpGDj6FCGPA0X82666TgCqiR4m6KKxlHXiwQTYK8GDJNNs=
    client-secret: AgAqD2fV48xriOABTeTXVUWZOeEtf2lSug/JxgdYH0ISVqtgpaG6KcAi7l6LewRswPU3IGXwBFulQEz7R3c0DLr96Y5o1PWqnjy7JrUwS60Ln+5v3Z/46pBsaj2TcsmGhIpCpISDCGmL4WB9uIj93D5+kwhcp8vufGK+YgmO/L7szObK6z2evkftrFy1wMv7RRq2/dmjzA2uYcY8u8pt1/zzhpVUskPpSMzbWun47f0NR1TVCG+WLbOL1y1a2LO/o4NZMCOIUbpXVkrUtLieEIPL4RKbSGB181w3B8TAjmfcGX0vsbt4oGrYefOn5FulUvnAHGs1Zj8Tf/GVrgGIJeIXdp+AP2xO/Zj8VDaf8V+2RYDWz99484OGuwmZYpwLlP3B0pS+JGyp5LMppZegiYzbxtjYvgRQTwlFaDn7gYAnxF2LxelXG+cah1JoK0frhGSUIXyDcu7X28rOOAdghe1IZI8EucQcIdubL+KSTP4bNLf3BsTQo75tHzjSanHiQYBdhm427U6E04SWYxKvtHpr5UCkuxxNBw8N/24PdEV6+7HQYYr/SCamc680EyTtKqZ4HmAkQWrEwLu14iNcN1wmOFCvToxBZ/IaFR+uah+76KH6vwmIm2XPUKa2/tWiCqrpCS2AT+q1+GW3Od9symruqAXbqHpcNGi2r17ADWeH5JUfkteqR3trgeCb85lUs8Kvk6Xk/n3OIdKIJDywgYK1Go1Q7B4vpT0=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
