---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgDKdlAlXXwsEUzHBJ3WtXI7y8uQwL6FJq/MxTfqrXUzpXtK4CkoUZKiqaEReEz0nZ9ireKmHZB7ydNryg/IHMXFEr8TUkCpPfPeHeHS9Z1U8eGDOXltpZ57WmwzJy9/WNU86UAA/pYRJu59lqxLpvRabvOemzeQGBsIyCgELdnVtC3fIOW0G/HsRVXbDrcQVwTAhKT0F6klnPDJF3xlgo4+KZNkD7n0peviXvU1IATja/ZXh4YKtM4GfanrUowZHElQre/L40IS8NPDY7/DaWElEXgZNhQ2mqsJPIr8eHMO3H7ysGYA7IXT2xYsH6p09NApt7hhW/JA206vC/19IoXS7SUmemp1Bdxndf57Ot30Vt45dL6/CDrLIeDbSpBJxOJLJWIWFUjzAO5hVtL2w5Z67XYhF8QhwEr2Jf7gcuwdIwIdKI0ZbPOGvTDFnV+ikFH2JcJCx/JE4akXe4imUmlyfJ22KQGqwvpjzM0RfUtHoLEx5fZmNqHDmOwmUPzHWBTgo1fX9DfklTnJPOPpD9youhd3T0aGliDut9P1HfS+iKJkzjLSpiaucLwTU/WcYWh9abzSP8H4wm59xYgf6yH8jczTVYPLFtx8SOllBbP5IMefeKT7knCVlqVH2fl9pfhX1roeduK+hEExmnq6lh8tWqX/XdBqj3IYFlmpEukSUN8u+pHf8WXyhwJhrMSCy7n/5RU8w1FvAXw=
    secretkey: AgA44iGtoPKyAsbL3qdACgi54HFfsF1Rklgc6GGf4eNg1GGKMnyeoNVJhEXaxQwW4ALw/MtdA/B3nAIwCxVF3FnGybOOQmoZvp1C8QqPqxn5MzLvG+z8lFu6etI75A3RPP4cbxgAN5bY1Vm4DQrBQxp9frVxLfZte72rKPYOeEblS2cui/96WKsafNPick9PHsOBRA2CG0pF8rg2i8oNXNeV5W6hqWyR7S4afo9fQ6Cr0YfiQU28J6SDD3byXvrSc916TQ/gq5KC0M4Rf72q45lBh38+TsfDjo1lZg1uh07W7nktzaMjDtrZEDBlbgG2Ndd2FPZu9X9F7IAINzV1/cmg55zm2Fyu3j1jooz1A5GT8O8Xt7B0cBeVeSvcYUIJfyF/XHHVrPNoGPZZKqzBz1AzkrA05EfJbPcdxMG0R7+f/QFEyt/Y9Qo2bQ/Oc5mP7xhPhlhH6nHDhnKXdPzZBxgPctY9p/Yh3QEqABR4wTRuH2B5YiJuLc/8/pY389fC110I0VoUGg1kzCgg84ZTxrvRLfIgFimBMextnNc8v0Bgt5SCO2UnK+bPFotVlIuewH6PnqnYymbkuF3jnhVTFZ9fGifvIzlH96Dae62KdTuOtDzJFiu9GOFx1r9h8D4dyfY+fV977V/9w1LqcI6aa/tuLJYkXitoPkQv9sTeUcHI3GyRKLi5mh9xlDfCv1QWRt5LaDyA04+nRL4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
