---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBmvtAE4leylEAUJKykUS9LDlhk4ZikJOhAAcbGBeSDYejl1gOgBGqjOBrneLjGF6URowYsh1L9sXtX0tpFO0qElQasvqfqWEloz1PBKWQ53ODqWJaZ8gAF38aGuQe++dN0XHtOIjcGhb55rCoWxYAk4FP25e/i97QxsLgSFyz3roPDLZeZ5lOb1IfFQTxLEKEjdbIPP1rMrBXI2t5DQPwoV2a2r7VE+FGN9q/m7IEHnwkdn4vzocKA8kNHoaOve/tmgEYfQ1By+akrf16onijFqtwtbu12ZwJJJqPiUnb9Nq9SwAILPzxTA6/3BFfTQH3J0vXA3paTT/XeoPTp62LZxMJ65rNHRMVcpjJdOgy/Z0d22LlAHp1IeV9spA6A0ks9XiuQrtx+6Q6lELT3Q2mVtJ6ITOWm8WIdNeyBy6XaTang7r7L58eHBeZhWUNMrxo6K/sGBLFZpKWmW8lg99WFxpMwxyTx6axWVDjaKuakmQf2AVVPExgpLkPOKFd+FyRtr0L5Oe8T8zars6OTMbA77ZNwB3qr22KnZAFjZQ/EUjimSZPLxVU5z4dZRSPZpF5ysNXBssbiXhABu+3xYPHHLgelAchJ+l3Sqnw5FhfodRtiQHJGzZTmJemEtXuTzh9FY9WvCiJZzg19GFDHpKWNaR1MDStY9MHg4t/RIPA7IUrdVLTMtpGvSRHDHtZwnLvll5yuRuIwYm8=
    secretkey: AgDBFySTnT0VbcIZbNBmrpuWNpoKVnbe12qF8ZnMhk97rt81KJw44Vm0NSfdrHu/2LCHvSAo4od2t6XPMAwjsT5OhPvek2Hbph2koPh4rkgcJAJ1vb33wo9C1UYljk0gBrqfKQvgHVlmi9FxUBdM7idwlaNDQOGJ43sFSmywXD8OTNgCKWa5g7cVXc4Q1xs5L7Wu2FTCEB0XqVZoVckAIldTyYVj3MoiTNLr+cb5tie6P6wXpIrrHC1ZMRS43KZ4SrfnHmfp8RaHxlPY0Tl4fhVhAxw9+3Uga2ad4fsEjeH7UUYwFQ+bOMTFdU46H0P+Cvcjx0AKZTq20NctuP/9pw3lswSNpiqvhFg6nKeL/Gw7QKYWnXwYwCsDiTRCY2UmuTgO0/u3K9SA3NCtkr+RheDgq4c9Iu7oe1gug0Xd45AePN2V8ytqhWy8KyrPT/9n9y+5qVpF/DIBueFfwPtmczFk+9/JsSgdLmOTckaPa9igZnd+Eb2UgEuNUJbsxxHgqFPrj9mASkpo/HZaT5ArEEsO0+a4ImpG36KxCsua2NBcZQ+P30jVAmU2rV+1xwrRlxKCMuO7/LkrUEhVaAsePX1SrDMPQb/y+5oCi5tzrbNoJKADZDt/tWSYuvFCPofCKjlGYjXdsAZD58XgJGY1LjZLUzeFHGW45KXax9CnoqEEIAfX9jzcqCqjkdBZ15aYDNc/NAFsLx6Ng7w=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
