---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBDfWacse9UEoFM6sRMPUV7Hod1s4GwwXYYRIlyWzH3WLRbEKJhYeRcVO8KlXmVuFTek3qtBbrvW3OrvrnoPiYJ2AhNxmVSuRIrndjGyN2bxdEtk2S5rlK/DA2dw6XrmAPJRdxl7+UWz9Mi2pNNSpVtPO/kYd7t4kONoBw/ibpz+EL5a2HjAPCS/qvxNIMy/u3N7dhvvkuB3o6PdSpYbnHj8zcMMnZraO9TZNeqwXney6UvJIrUV4BKXBWJyYWSI9C26JetVSiBno/IdOHzD2cxmHVG9GaD0HM4peUvVBsXDdS5esYMrPIHA03dALE+7Iet0NULIwBid6aw8Jg4KTs+K1eC/0dpmB5jUPXq/H0p/CTgrIWjR3NwfK9eCPnaXndY7MvNpPM59RC1yyxkfCdhRfA4iPtyD+ZOkcrWBTgpUP+bMAsfvdtuHaK6s0CdMFhM1Zf8xmf9oJ0jB/6Jr8wD3qIKF3oycO03OOUk3LLeMrOk0+Bpxy+T4Ur5B/eyNYywSvjLy721cIyK9Rws2V10tcWkhqWbzSITwzpgvqrgihcx0MtG7B08LlzKW1D80ibAcsneHPWi3QOWDnM3yp+7e9wg4V3FTqh7V6Jv86PMJNLLyNL7y2S0L8z8n76ilsRZ7ykF5xc1CMuhC3MD6PPC09bPkrWV5R4E9wfSZRqpDpu7NnmUJ4oyuFtSI29r7sa4JlTcLH/107J2x+Aep2YNkyU=
    client-secret: AgBYMXno26zsSfKwvxFvfDAVdELk0Yx8a0uHMr8AqpQXrX3n/HVqonOeQYWweZhSdsxAd4lo0iqCMcvJIa1ihTmwJJRzub5Ygq7SUayoV0lx0hKqea6P+IyLer0V7QWpnUoIM0xgkCo/El7zHPtAKMe2G1VtEjmUsgbz4bJNA8AgYJU3+hQshuOjceUr/DF2klW3nNX3ThM5QEG8gjP1GV6/we37GBRMCuayuOtOwdMUmfNn3GmzgDOuMaO0poNDBa9gUyQtzL2IuKoINWWqCs0BFyJ25P6vg6HPYi9/EcTzR8tI+dkgBHOsNyebipjwD8isyDc2MKEbd59/w8UTuHLcIZEweXoREnwbwiGVfKN6Lx4H4VIN+TElv0QqyW++jLyGPORkLw6BL8bpPrqKAdJ9f/RKFLvggSLadRv+AsQzS4ChJAnipURoDHsCFDvwmoTOCSSkrsBk4mi/eO/XuEu4WIBurTV1GH3q+1F9MzEGT6efv10Gd636A+e4jEuwVVG4JJA5/9wcMTj/WeyTSGT4lfDS9QYL7/2dEar5pkBHlrPFVnqxwlAH2ZmtALpV4Z2I60xqOH3MJI2tfZiAqiBthFQKhTYor8FjqxSYW6DosoavlSz6Z3HV5+p27V/8YJjkaxPoHYdq7CcK5u8R7GTCwF71KrST4Yt0FSxbPYIClrzFNJDEIGUEl/UJk9IxlERjIN3BkjIsYuMsINH2LbCIrdcqJqyJG7M=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
