---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgDBCUopOZql4eBSXX1I49AfKmd4yQMyz6Y+XibE1QB4CyqUTiEWBnpmMYVrd5wH/jgyhDqQ4hOlnEd4lDv+2YP+UaccAAUbzy0MZVUyTSYNFX6h7+kWdq1v3wt8MxBM7d3FJYOnV0j5L8Tn3mHNcMV9JZ6z/VaqIwOJigwYsDPpiVFrqjuK3O7S6k+RuGAnQLcAvygdOK/c3AB2g1Y2e6uzEmmVBwQYIV1DtOaXJ5NnQdhrFrmUTJLUW2ULxecmof5E1SoDvmUQORXEqzvNJHVe7rbULnnSrGUpvt/2BLwrvKbZJYTlEzD+AunXx61cnYe3GopipYgijNk9apIo7Q7HGBA9cQobgPOTJHg+KspOv8fKzgZ8vPJ80mCLPA7spu3P9XFOpai0K5+v7N/58MdjyqE8OEX5VQDRLsRpTigsr582LDzyvOujqmGTKtyadF+ZkqYDklQYxu7bzblwmNiqBk/UM2bVljeoLZx+IbuNiSDv9vQmc/OdV+/1fPfB9r4Qb+/tEMTvOSCS1jpn5QYcLrFYuNwacBGFQ4vL/+bllOvxk/zWwOmbO6ZLQCftqEC/+3ln6h+S7B/7W/O0ofJgTL3xUmxithKMK8u59K55UsJBdAb9n4Y+yCX3sDaqVfULwN9OdtDLQAOW9inHjoR6SzEs31Gq9qGY5zP4bBp9PeGqtKwqFR8Eq0/OcwxYXqa09C1SLnRH2vQ=
    secretkey: AgCML5+t2/CSsWTklXO4uAfdV42+qmWjNqwU4UXl0fcCeThg8JATNWZ/Fa30ArHCP7T3HdvXjcwyR7FPsh0qFlpYxJOIaN64PMYi5JJYtqsd9GD669BiJk1qeHnk8Cob5X4hZNfHJxVRKVWDi5k6rIFQCm/Q6pB/2Zn6os6tAyHBlYVs4yzLXZvsd0uk+QTjL5EVZG/Z4Sz2voI0iM3KM+mQCxklMRN5LBar8z2PO/SsVsyc0WV61kbZf5Y828CblroamXGiagrsBhHjTGQTH6aeeK70oqyYpSUs5Nu6J/8gsj6CcM9Qix3+2cZ+YIPsW5o8NHtB9+O5wqDpEnykxvCgBADwMecCdTCyAvXnYuBoqG4r7vSEFzIK6W4kzzr2ZYH1vhkH8cQQKPXcYftqv3f38Qm3JUaeMWXehnZzEz5Y8yPADljJGX0syPS5FvOWgFa+894z9r71E27x8EDFLQM6CZnTA3jfLF0dZGq6BlFymVyreay5xgQQvyLgTouftOW+SCL2Kn5yDvauajUAy8XPpeaAqXSX00cyiS5efqo2Vz5xavv7da4JLZbzkhf5dOGSFayIr2rAT1hG47vZAicxHRft6x3PwvMee93gRPL0SUhirq8fRtKIjsx1Qu+7J16QcfqzVoLM6ppr8syAbWytri3xvFBu9Mpt35UVvNKGjTPpKgIe02ISHkgP3WnKfib4amURXrRL6p0=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
