---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgADL0PDIT2ZJrsVfePTNAv7/geIOyDCFNyyxDpLhD3xpLxU68CH7D540LOVQoKl+GGMWFh8fIYhrJ+4Y9YyMr1hkDy12CvUjw4HRtW3ClvBV1iAlmTKPYGDF1JFknu+Dft+5QJaTCNwctjMtvDJXzXDwnjR/F1jy+UyPqr0trLeZQS08t2NGqzrmFJ1ORt7cLzYtzHw39BEufFYbN999/eMqVsieW+ThsOl56sZ93hvtNoFeYJKT81VF6J8lOAmeNMvtUeAP9EL69QrHIwF3gRZQYBrm15N8pJH5HjOl25aZjKjBOdSsrlXBMUFZK60/gNnUy6Rq6iZpC1lieDUaZ4rp9Ph6PNY7wQ49nX25OxqL7E051dWaFU8BFr/C3De8+zGrMY2t7yKZ82qv7czT/VGXdbJmK3fRzCpzXbjiK4uY1UiqKy0ClWM4/o4GQ/JCGGrcs5qj9S+urn2uC6+PDQ9Q5aHlAu1OJSKMulP6D3Ujf1yM/uTk2trs/LswJJiA1Vb9PyzcY2MDlQbrMii3b4z3H60tVJeATq8I+RIKz0tH3fBG2Gn4qdk0ddor1SAPYDH2ZEOyYLN+bsjDtuCZeTYSsjmKmxAdbPkfdea854oD19y7K8b2lxuP0N+/BnHiBNLOYjRGvA2xzZuC2oTQ1TeUJ3G0HTK3sGwj+x/j+vDd5hT8bWOCFU7H2Kgg3FiDi4eQ901pkARF+c=
    secretkey: AgDA8y1YpUe5wCKyxHl/2EUmfxE8spF+MQ2u5WjWPUQPTtvOKphpWXW8QrUx/svEchuj1TSF+Wwn07FVpi59o1IxmosPipAf12IgdnuUa1WeouP9J4/mPZ9koGreefTRNN/vQbTsakVfs7DVy3FpBhXt7HOGRQicU6ADkrMvzBzoOwuYLWsqzS15PoNF03IDvUdqF9g3gaT2KuT1mgQh0+Kpxu9uhjJroXs5IWO74z5he0YRfHEv/RWfkKZLKVJLwCw8JcPaunJndS0TorQeshowCeekFkNI6mPhxbG7ipE460Zi2UVwLbDB5cr7uD+siKXTYfR/T0A/khD/OrB/c+5Dlitb1DuFP/7YQkdy36Buf70B09Q7e9NEdJpW5sWqS6JBNWRDub6pFyh8NqVHkTvZdGIiWQbdsmqCUcfRK2pnx3JNZddGQwA9wMGN8J6sWr0GgMz//RFb6ZOTftbylM5ca1gm4gAJBefUZ+J1v6DNDADI3iA2emMZ4rWzehozGN5FLJI4BEKrUM3Wtw7qtdcdnTBttxzLmqWEzMo8zK4iJO1iNbr8Zlw2D+eK3J92fXkeV1ehiZd9wvEgBQZg/5CsGfB7sdNfamAXZtLkfs2vkcYu4gRqawUquGBCy4Kta42cIT1LM08NWhCPJ5RXd9zMCdJSQTuX5ZhJOTFUFVvmGrxMhvBCTs+tMlW+0hawABMRSJAXDP9IdpY=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
