---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgB3Iq/uC1vj7bPTyNSj7IBELNyZY25NzM6UqAxdKXw51EcSY4yhhLktSz9jbZxkjXWRL6c/Y1JAgQ0yfxSjsW97oaXICp6W331otpcWXSi34lfr7fqyndFz75vtXbL+v5uVlClv7ibYwTK7sUWsFGhOUk5drVDOgtscz6IzYJM4TIS3wIdYFpt1v+YUmiSTZ7dozLGYjj9sJ4tMj8SkXyVTGGuf6XcKQgVxBwSxFcaSMYLCmBL1rMhajV0+UHKDxoqlMNSlycV1qtXPG8wmfLUvIShljRaozY8bmke9+Fu//4exYGFwDLgj91W3x22uVqEfxEDsHHULNyUsmMMuU9N6TldTfQOXDUrYQwD2xK/HatmZrbNAqCKL9+FalF51LjuKZcnS9rilRKv1wCsnT2dNUX7hzmqpjCD+HIgBE/egAis/tT7mdCt8T4Aqy0SnD0QxkG6giBmWTw/bk/4LCEAMOTQc4+2/ETv3JD88bPzOs8h1N4e1AYFAKgF94rGvzynNKJrWhn7yGSa9IN0boW3NSUwY1r6fKvG2xhfS208UbdmXjLxFyK5wH/SDvIjUY6EAuZhtOTwYPZYA/IL0Sno6YEfxTVclC+2UogIM5cBIsJdicQSMiimvtlskX2SMcxrCjWGf4Kj1HAabHDJIcyPbpZsqDX4wg4O/fxvdMvFpdPY8V7EvUPW26X5ukvs8EKgWtPSYnWZ7qY0=
    secretkey: AgBkOmmhkb065FavZRsgB71Tj++YPnft909X2UZwYyIpEegJcJvQ7h/KlA8KWzK4zrqgUPgn1aZoQ0WXA6HEZxZhAu3kwYl3ZB6trVP8QsamhKTCwf5saJPoUWklvi4WTtntiAhGkenN9PVZkzMPoBZeD1JBX/XWAVPC+7GhoHlLIs9NfKkFug1JLvLACxz/pfehdFgaQIRk15c0sWjiBqFtoWxsLblHS5cF+3MkJ+Lt++nVMxDfgf9tKYxQtsWj0iLZnJfrg9ov+sETFpPStHfhrrFw2JLvWsnHeurmuNJ8kL4mRIidJPI2Lwz/EP5/kZN+Uvku06eEqSb2sGvoKmj26DFV5zktjsufxoIYIjHo/Rk9yJrplnTUAvgsvomevUJVkGz82BiTWlykTkrkVFhp5abxQR1oY7OzzEdUoT2UL1ltdzvmIHJmHr1CIpnXWq6NEl5nlTQPO31g87gFlQMu5fybTqePSK8pHWEeIBABmNyvv2c3CiAjkEMnUVb8GczUalSm/Ac6TbpYlADMWfXgUT2ycxzGrYR7MT9IZzwERe4bcf6aRMJO4YTdqnT/KB8v3jR3kmZgrZDUcms8++W8SCN3sSSvC5+nM3zvgbeAcSaybg2YZ1wmY9ylt2E/fCh2/tQmxqn/mnWM4NwXI1M2kqTux9pha3HnxWMl/1vaaSo0pCoxz5xj/3Pk+4hZ6xbuRXnhAMEn9bQ=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
