---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgA5da0y7bMDGotqvWT7/T7bQ4p4XEedVpilbG4K3G3CyEKIbA0Gzbby+KoUHr72DFnxs+ii6opIVRk9zTRBkdARbgeLeo6EEjT5jT/8BNFFCI++2dcvXrtG3vAIpzGIsobX/9YcmpeCXxhSGjoRIrGTedpCXb1Mu86Yom33K1DtiHknj5f1fla13RPpaxLu0ZjbEeHpS7ngC+papD0CXkOpAK1TSW7XEcRgfQK7u1yYUEwyFrCSmwM55EI96HI1ygMl8n6HPgKf0+NCRQtYDHKO/sYP+91J983maIxDG/9sjHJyHjHfuiDU8UC8315T/a2CkUa6yWbEWkU0CfqDm73G9CnX0NvQeqGDYftLpour0HrYjTQqkb7ZdkRDLQmVjXgXlTFwMHfSzPNLtXGKND5ZdFfriekHM1L4F2Q4pvmasQtmsJzKaqH9QGbnKhVSwDdJGyOw82ZpIVptgy8dKFFnnzGaImnLP4j0GfRyGQLkUFHhruoRBb9PQ47tGjyDMi885RVQPCBJ1PG10ZBKj55JYY1jfFfivvQ9GVr4PYtbOdeXf6aL67h2fYp9KA5PsGLA0HzOU7ZeCQkrT3az0Z6J86VDgX9U8xS3+Hb+fmovsQk0yIGMoIJ61Kx3LIGNopcbjDq2pz+S/LOMSpD4Q3rH2Qspsy1TkQoHyR71FoDdWMNBf541Kwq0oRW9T2vsQ4G0oLb7YiCAVFwRwgb7/viNWHk=
    client-secret: AgBarwbn1tSD/cLcWZ0M33dfm/xKepCjfIb3lhK+pllS0d7LOJNk3E7Cye0YN5yzFseZ6LTPTjMn40pvaiuB4Ur2LAevq8Y9ZPBNRFwD7pPQS6FyCURboCdBUvC7oS3+DOxReiKEbt3ssJV2NNMwU9oegKVL7pdQVeq+TXU9FpBnS0F6mV+1VfEXGrJkYdZaARg3Q2jKh+RtI7HrTYxj1/nCpRGPiWXzDLKeOHyTF7GI0BL1SNjPrPyASUwqYYcpOyI9M516cLKiCcXpivbEQnljmTQuU4Hug00V9Nf8DJ5UeUmLMRwf9dJ4pQ9bR5UoUUCvRN0aDuuGAQ+xL0wyniddk1n+aDvYXs9RV/72U2UdqjWk5l+aVIoZyNJsgCRPMevD2KIQN2KMfGla5+TCc2fP/gzdMna02iwI5sTWs74SgdWQUxwxdHegC5kVgfAnnWZpRX8tGClZQ6T7a0F92j4yUsQ5jaZ4jVorVOkZwaUDsupWpYeEfyDZ6kYTtozCWwxPMxfp+NMEQMDJnaS3QxFxmxytlP5V/J1LHuAyJVSs30rp7V9s+hdfsMtJzumiEDNfq0FZdVreE6+rnPNvHbhPxvd8kdmqzS4kjgPm39JXda2GcxuDq1iIYr7joxbe340MUKHiHSfnV5gWmwLER7puorxYMrx/t9Qy+lQzO1FeqLOLIi3Rp3eqrCpy7SFnUwJCTvDvtYZ3CJv0ZBgr0jI2HTNMaYqHm8A=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
