---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBAsegXoIuFr7dH9Y2b02moiqu8C81NeCu6s7L9LLi5ACnXNe8mYGdYfOUBwRsaVhmkm4HfbRZ32U7NBpSvOMDKfpz9VeyapHzhU3ilLZLuPH77nOVyfnZea4zhQHyRWRSUzzwep/0TtWO4/WfhTGNPP+KCxvr0Ih6R1Ovx7iy8p9i7IYAba8LN+5kxZjESY6G4vCA/NFGHB+oJJ2QkqaVdcuth+erwEuvoz1QXxgwezY7+DuCY0OeKmHq7yUg7upDedvx/E4BLoSRz6S7RpycbzAUINVIBmL84oWKbCcZUIROWXJPaJHOESkYLRxGlneNEL3IAF1Sudg/9m1jaRvdp/o9p5LPk2itQh3LtkwOgJT3ehodmTYTCSfSpj/Qvab5mjIQF0uzXdyKNqZZMuRJVTkJJRgVwAKJaPI+m46vUN66UPk+iirpL+UeXW7XkqKsm8ziAbkBEx2BKZeo37Fw2K/5863NxLijNqmTmOmABaDpnivhr2MB4EcqUcbplbsLm7en0AMLpLBIsRddIbcj28S9o44afNdR6GHG8GxEi6ZUv5h3P4sPqXTjMosNq93txXV1Meicl/R6I/2QBhgt3TMouM8Z6dJW59c3UPE3CMsr2AZ1yIUolEVb8aGbnfAFtmSE8uZXRiXjbbMUTx8TZat/ttEJUe6AFy8W17NdHJYJhFuDJb8S8RZjQmJDlPS+QrmnRjn1f9PQ=
    secretkey: AgCHFz/WjvFyJ2dtMCHsIxQ3DQHRjgp7CXZxe4Nv1G//e6Fh7cQzcR8gBX72bRGfClSeeO6KbcKcpvi8q7FHWyHHz6ZfM+rPGcpWXgR3A6NoKp+NTg3rYziG4aCk/WCNROy2outAplH8mB7wGvnfEk/rUFJN8OmUYwgw4S2MgT4TygFH8Kh0dghBS0Uf65mD0VHlkRS1LXdNCH/Cotw7rP8xDyEvPPUnjuTee4P6U2FVaDUVZ9NM72ZUjKw6lRCXWPD+pKYEdKMnV7o/bjHQWWAla50WA/Me4c/nV+AXV7olePIRC+AELXy28BNCXWKS+uL3ZJIw2ARGSqACRuy9RqtB6mNzRM0vywoKDO6THP4noFFFM5R0QVmkPeGxYDUHPZltPnTLHdVx6+v4nKaLdYzeSHKFoEfRykBBmEzzanhrDGT/+heFbry1ja8an2QFAFFS6fVlJYPGk56kjpld/CDT8dB9kUMYnzVJ76wAVHWCGcrNw62dgl29Xh93z573wc9cs6dP9dy/SomhZ3gpZnfUo9TlN19apI/6PJnwDp1gE/Hvy36wYRrkVhtaYa0AL0iVn/RZYoT3HaVnGUfNJGuhdfuDX7zoI3SZo2aegJoIWb4rprE0s57N0lx+kHoPPjugkRRFhogZxQFNugnQC0b/TjZSXClIKGlVoe+xfeLq5wNOIOFZuldPaDYk9QW1DcsZrA/qYf3KlrI=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
