---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCSYKotQslWOmJye1DwP1JFemzHc9r0eAkS+uhvxGD+0HSnoJ9UgjjSBTx02p96rWnWpXs/xtZuraCDhthf23Hja50RZs0tH3Bxmrrx4JpYbi0F0fHBEWGAS6Kg073NqOvyydbmhkiFkv6i8CVkqLdbaObLiz7/Rc2rx6e2UY2ItEAQL0Q/wIYX1jzXMLKseRBOfg2UnwzYjyyU9iUm11VRCIHPI2YrYv9shOwlZhnPz4iiOPlpvSGWPLhyXPZXbPnfd3wpUauHaps96Cd5W/apNYKAKHUZcDyvYMfFZ5QX7mfIrkPu+p5fNi8Viwzi/mp7uNaDjIqolSewZPRSOBFDnulDPO43D7JXWWsuMC4dHCwOHvJxkwTNxuqYz0GKzn0xqe4eLSFHy9y2ynjr9gS8uGkwGgzLwOzLJKQyPr1nUZi5svEDbAWtoQ0pYHSerxf8O7C5rvSwX8Et5QyEwC0MNlKYIny6kkuU9K57LIsKSxyY3Yoqn5tQt0ki6O+J6H0b4+USEVeVCuqPm9aio6kIn066UgjTFvVD1Ro1mU3OvS8WimJBJfZlWhCM7ejcki4d/PscUFH7eUu8RdJKj01JwGBQyhI8m90iHGbi6CCnB/g8JrVP69LVg7k4lThOVzhTuGMy1UbbGO2EoLf3MpQbUi1pOezroCD2eiGlbRgfToH9foROm+2T3R2T8JTQjbVNAFZcXWuRGiU=
    secretkey: AgBCTFc2erqPVEW24Wv/vf3Sl5f7+6424+0Qnz53ncAyZ6hv42+JwYW3ulAwR7VKHjbVjekbST/VE4RMEP3Go2fZ3eSKlNs0J39IlvCtxEyw44ZsUxpABOBRlw1bEI8wLpBijVS44os7sBxrns7D4/A18qDgnHG/n7+XOvC7KCA1lSxHY0u87Gi6Cw5ohrEPPbCv7urP/WlWu2uG9D4XT3qSGfOItSwsda/OI4IlgUF1/KmBxjwuwfuBsiyeT6QUzmHgxOgNGaUh6RupLxytU6HPGdPxLThAqyAoRQmVEFr0wPRz3gTlDkMAok+GYaf8jDzKc1z5afjcvsb1MfLrK9bcM/C/B0PYxZs5C7ceHSLZts/mchuDCAI4ldcrl11IGNwpaNhFrieeH/hgTeD8+9B8ZQpZO1vPxKNm0p5NiIBxk0m10hq+1JGh6Wp40NxTHUWZOMATjLvrAb8NhRfwrFpBclbWbglAx1FvFrb3xDgblUkekj0IrbXgSleuHFltApfLeNv5Y64G7dlaBiqms+TlH70OVNUNDipsD2BW6xl4efEBWUT01xPe0vEm8r69D9XeJK2T6wsiIbU75odlkDovT3DY1YY8o5qG3pEWMXdBD3lBlAjRy3aDHwYi8GVvlTTX+BX4rHZ6d6YVH+UURiPcGCSUhsrzjar1J8Gy56beVslgXq3WafSxNQG+uzXsIc+CaBqAIV611TM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
