---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgDKEKLFzye5cRahZWJliifB7wJzwi4ZOnGNGGPibq/lVB8fixzP9UHQ+ZdLGSzxMwi4YdjBXJp5/qZcJhZApziEzZ+kqui9mIXFiCkPGa+H3JafPwtKHZ/EZwdH0vVBx+gG6FkBvrCEAwCqiiVOFm4dIb5v72pPaL56Zp31NPYKo/O4+B0i2lEdv4mexKQTfaF78rccHIZ7wk1Z4oOJMNoZLRxx1QfSwMcUIaHa4wrUtXXW/K47QZC+H0Z3ywBt2DfqyihE5ebgMmUnbsTZqZaVQNeoZzK1kib8YqEe1hk7CB5Ms40/rE0NJ7A1+7fAe2rafV3UkdKaVEWgrHQLBBHSNDQe1t7R2Geea/n/oBqIta6YOy8UvCvq6E69Ak4vx4Hbf+ogKe6XVHltMHhEo5M2yKwFbKZkxSFGABHxWjLgxTtRjlE4WrtRlKqcX1moZZQr5DFiHdqEkYYP8IWDn4Wf8NPiRkFOG80zqAVaTZ474KtilNVUAn37i55FnOCPkIFnqnQeDKP2B2FM5ticssRKT5bdyBSByzEVXTLNHQCq2dj+LGcQ8ZDuBlExHMLjqd8ASBUfMXeZptq2+i7xlR+CSULO3BhzyoxGdq50vtfe5T+3TQhXdy/QNwBBctyWqOQ1Ok0a0HN7Y4lyyl5ACTHubWdfFXBeoSsGLRV+T0aJZPhaGwdE9QuOZ+2QLWClHszNKAdrUlVWiHI=
    secretkey: AgCpSH1aG1vH3vFj8I+yNsl98iTeli/LbrPl/MQ0Ozs5LJrOJfXeTbqJfohhCmkF1hjMlKRGMYbZvgC0kyl9/FG5PHKshAZlw1Wlc0/uhdNEeKwKeLtCawqcmEguCbUNI+T16C6YVwsZc6iU27xLg95Av3Bw6QCnvO5qApZPoRZexjweQincg1CpoSEOVqcgn96y00l2Dx+9u3uHBx8PVxct1rsGqVGNapzCIgfEMouCrXcdMQLf+Vb2xrtkMUvGkuZD2vEX0IVWulOmdjh52UgRR9wqKICgeT4g0pOxDYbg7UrXujrYFm361Ge8Rfz1bPGrXBzyzVeMOs7PTTfeCQ8Q7+jbI01YcCGQwiUEK0tPa+HKvLss/mhMzFJnGZ4KXxB3d/TfCNQ1BTfijfXnlcsdpWjzW0zz7ZeCsMkRrGCQebYKVWXG4eBwtNb0NEBLfxWmk1G2nrM21Q/8O3P2xzwk9SKgB9/oBFdAkCTHXZSMD6JHupvPk+fAM6VqkUXAI3/NK/cfoQfpzyXciJklspIOK6HlL0Sbz7b9Wv+Vp6vS87p1RjpFeuIKeaJELjfqs3C/o8t3rN+K0hX4KN58944uhb5dYH8EbEGd8pN2ATL61XZe6TzexzW1wvLf+RczGgQqYhSeo3X88S2lz8hmc2mXWuWWzXuCOkT+a882kW1cbhUu7mBy3yCiEyez6PePvRAtgl2vYE1g30k=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
