---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCM3FaXckE+xzj0p2+XqPSa9OOweD+raH6n33F+rx8+jxlkF5x+gd1047SN7STkB6Sf8e77hVYry7MaSnLswqOmd6aOebckRdJehSW0HAwvxjMPkF/ZM/yRbPcOQX2v5x2eQldMaUagliXuB1k3AtzE4kuII2YVntexOo/puhTDcd3GoxYaCT/5LMA7yRL820lKXcUxJcl29KWpOl9zJXzTg8WP96qzbqYK9gpmB++pXDU4M37ffqB1jKggPljvYWv46FenhhouGWcxxwrBXtS3ONyPwLcRNqFJ9ZAtu7M9hJi9iIlnmoyf7aLw4p6lBItW7qhysooh3AH+z6W1caFY4vy9LoZQhz7xy8W3lDjO1BwbU6GGdX2hueRdmudtFS+tTkTAqO7oO+5ZKHOSK3k1WyeeuwVqHyJ2sk33aLjsA564+Z6Dg1HTCId1RPQvQa+O+XeiyjFfEs73w+vLZRHl+rYvXgC6VMGzczKbhpAhBXOKBD7oufY3NtSmYZyo+iCDY1EGcwJZQ9vZgKhGMEQuDQP1ceK0BTzaSEFxHVRy3bK+xQ6AWFNrjFZNJ9QIZfi+3R9byoA3y4I7F3tdXlNnsfDAaHWNdIsJ9l7yz5N7cIa04VujkBTvGLbUvIZHTfXo24YEK8qRerBdIPq8HcYjYerAlLTfSE+1JYqDC08c2hAg6GenpgE/+5Hkxf6m10IMLB7hXJ6lnhc=
    secretkey: AgCyBVZAswbxpBDOMhQR3K9nW/5YWRXE+pnPMwobapmFEs1rATMzPT0cQFsx1k/1sIem4Ww4Uu6bsjBUkF6ZsCccjCckzxwSv1fTpFueQKcRBuo8AJe8prmWAUlvx3FhZvrg7SAhkYGktLE1ub5fxmKxmnyntQez8LYkrsEau04iG1GS4HER4e/dcfjqcy2rgzEcbUCSHKHKPuU7BMs8x7aXSepDh8SJ5benn/QDM3nAoLOvvadhE93JxfHOoaERQjaKSFwUs3HFKcJzZc/i1c1s5pPJH+2E4bx1HyO7UCXrhd2Q/t1DmZYIUlMKAoAyIzYTw8svLCqUpXiEWyBss1GLGVF/qpep13oG8gLk7MQLOLiM5OQRO/aDs/2oB016Qipgtxnv0WyJmhheVfPYD2KLzJlSC/zjkqV7n3e9KI6yHWbZZmUs1FRB0OxqT+zakzHNpzkoRAyQVP9MvTFGL5k2Gsr9TxpeO9JxuE9DCiLV4NANTgbI9w1O9d3PgKtRcFdgbMk5jiIXVN6gJq9jaN1ej0qZTScKl8oscAAemgx5T+PBMmMh4rmZW9Sy717p4mjlB8ua25GVD2QY4SAjhkBXEm5f6JEVGTNypyGPBjy7XJVnh7q7V0aiRA+tGFVtTgp7eW6BxcHX4o9b9+PUp2MpGLXBM2Xqsl/OWKiJecAvpXTX0CZa1rhRuBeHo5OEcAhffPxIGdK3RFQ=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
