---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCN6sCWM4I5IFPn/g5BE/yYW86d7YUOew4/H0pktChMaTy8yPtfIU3yy5ic3qgkEzblzmv5DKsQPAGvXNqgUxR4yS73w46/l91cn3b2YJ4aUdJGddPMmM6fh+pw/Z/G+cKvYBLuDU0RiDNaClutNZXSkW1xrE9dssvCMZtXISN0p2jtJSKkAEs4SSEPQGMzJvRt0/LUWcuJo5ssO9k6xCwRVOOQwc73T21eNUJy+GcCuwbXwpuAUhMHwpH0Yv31GU0bLxqOgbrPB6CI0oqJJ1MwEBbBB0CPeM40unRx3Z7rKJMlqYh+Y0gph9RoV7TrNcMVomxZZ1GY0GwgPzo1apLSfU3STd6CEfTyzbbR3Jd0dpFGBcOpnr5cYZ4URVrZtNqARqr60ZjIjhcccCSs9ExUGKFWsYZNJa83R6n04xeRMEQcwbyk1xnJsJKIeEez9n2fznO6mlf2aCvSV0k57FHbseQvrKaufkfejWaDtFGdOKDh77esfyH+dABBa9SyrvgF5eSI8oe6tewEPfoo6f5NDlEJhwDT/kVkdIScTWKhloEHbuG0y/Vi5c4kGPDoeuQ1lvRkknV16Jg9TqRUYgI06KQUKvLcf+/iCU6dmcQX6zresbu/KHi4CjnnbHBjjN/rnaK/2VktDptPvQZqbocdFNe9dXE2Wrgg8nDePp7hcld2UR7LXz6oGKwIRvOvABIsqh9U5xQYSXQ=
    secretkey: AgBdi+INBXprxYqJAeaLaSMUP7Zfv0HuwOJPchWJGJmCAS3G9hu1qlrgZ7ZY7zXfwQI/M+3L5dE08cAb0ClXAjrgE8h4Bo5ySNnF2ZMVQaTYxRfL6bsYfeiJHZ4pl4KoBnGJCkAzmHp/lPeBp9TqaqVtE84l6Er9F8qq0s9asUutdW8ffPrs6GhIGkO8wtcqTzzJse4c6UZyd+GNIQyNaFGUsGr7PTFTdXt7UmFnhI7RzPHdpIJaq3ilnjlO8QBa9ZlaF9SZ4+OeelOc7DRVTruMaICFOFboFftz6T7bjpacCs7K1nIN0kkT++S+E/7REDVQD8XIFIXWcipmAbzys5tmVmSLmSqqff7nUGprTfY04gUN8Krbv1o7VxP+xsfc1fLzZ7SMBuxJbggYy39x5pnjTqhxW9f4R9fH1pZ15Ix8E2dV65OcDKAyCmo6ZboZgZFX+sIsvVj0MhY3tfKpHlnkSwVy+OiO/z+XVQhisIyxsrSPAXrhrcXZ9ipnoT1c1kyOPztafAgF2Yu5upsCIpbuKVgep9pToNimXuCUDnsBJVDYr/cjARyWrpHkTdtFch71zmllMY8PpYmSYvtqUx6e3yoKvFkIdVC4KRsJHwlem6xnnz8GEG9QcEeN87dORGt/QLZoKeA4jGpgwwl/FCLOuamMa1ueYtucfGZ7okn3d0VjMGHmBS37Tg6A7u4GZW+DQsUS0Pxs7zU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
