---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCnS8aIOim/RDf2TJgLoUIlclFUEnX1/BdUqtIti7kAUw4KQbxWgzKkIi/+ZFO6L9/7j6bCocGIyGaoQzv+wQ8+3L0k6MNCJPRKyiEPSQDQqW79M2o2zGOMC+qPyB19LsAkYZlt/gF+RGub60m2pWXZmOdEHMiE5lsjkg6YSMkmZL498kIpBNdwPFA/qAAOE51dh09LZ0dSHtb3q1sKAVrx3UbBAjyIyekgFdMx1DHOUFLEQDzDTvIEJNX4CduGgC+Xa8GnbKnkGWujbsu+3ghquLAAD+T7S9JroNjYncRpqBGV96DtJez28Ct42M3kKjKTxWCXDKHRonrRSn36rK7rbFj/iwIP/PhVDJoxZeVYp27ZNrTKEOYcU0Bx5LBKUyN9z5D/8SWCNd7vSzHxaKUU6YpWIFpvFX0IoCYeYLkzMvpKIPDWvuZ4YEaNZpDAM/lMzsFKZsZROUQwedRAV3Eoy3sistr4WPWqZXwwBkcece9G428x/nAO8Ip2pJKrh+1q0fld59y7pWIP8BuH0ZZBGQuKllQ7uQvwE1gsqmXX2GPKPZagQ9MeWyq3nS6/iR3ZMuyzfQMhbR7yfTP+9VyJcQljmkfPf2csR112kvRSiy+7QM28mYjqCfXh2J0dUGujZjtSBKowCUA74wmGiTqJh3VZInGxeof4hyO4dYIGf577Q+zd5e3IsnnKRQS2e/n0BP/yI80OHW4=
    secretkey: AgBbAGJT/stKJwqwkFMychJZU/wisYe7nQ1QAE9uoLnb/43PfRL7RN02nY/cm3+iBDz/1g0dNGkboxXpVScEeRMToJJc+22Fhy3jDuGkxyAGIQ8P2tcemEeLY2WeJnU2THd4O93UP43UQXD0qKUxEastWbQ1JHMvCENK4lOrqXtZhOynbU0H00u4761YLXk032Z4aG4zShImZsdSAjAs3Tsi0tV6tWFnn5BJpdXF98ryZ+DFtkO/zDnayaQlykEwcILKQanvYG2okX0LBWGlqX00IWJbiyhMZbvaz3XrE946C9c2Nrx3TfIMacva6G1ExLww+y+AxKA8b1FhSLWbBvs4+L7Xg66VENjkEl0GdWuk7H9f4CrIPEzm85s3NxK/eWFk0+j8wQf90N19+YWappA6QnKvtIrVa4veGDLb+qj/7pduLEagz29tw+AIez6jkR0JuWXI2gFx6W8/mqEvFz82xKCdsPLzIDULRN2A54KtdC03l2n9G1GaFeaCu/TSauIdHTvKbsIWTKubtZ1bz2BZ0i2ikbWAYGsTWq6fZXTXEga/3t0nmlIlYkZlJjr5Vg6b4GHT20rR05Eq6WYkQpq0Pb/ubXeCs76rV02MlQhWO3GDb+65UeFxy8+iwQPeqijkOYi5Y+/Z96w2vwBR3sTw/WBrTFBl7iYCYwytRHhQtCwxD2tmNBf8Obtx3O+yExLWn6Ys85RYfB0=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
