---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBhO34WqKUQ8IdFgs1lY4FcTcZDB2Z8nOQiCX6hwFgp+rE/l7o4yy9O4Gr1lL5Qrw2ekdC9GfZbqfZc7RxcQk5fthC/epyyknJG7PU4UvItsQiZYjVkNX8cJUJ1oYdN6LDEKl+sz5yt2zqPipmWMjize6kf9mH+Q+5Q27yFlZuYQQR6jzYXAfG9yR0N+z6W5YWzh1UqAWIxgRMcOHUHmsMD4psL3LwsWfx366rgpjq10FMUCaj5iBjmmset+FemtcHKToynn8R+5tUcBgBF28WvcZaoYFsht8wH8F45R09VueVJU82luZRnOm6Izb6eymh/6K/zy2kIrk2hPR/FR0iNhsLvavHGSdH0e46zHB9DQkipGW9hd22PTF/GaflV8PiAJcKUbQue5Gm4V0TiC4cv3OexS6xndjlVuGOwBloEPsnAgNOPBP7D25oHl0q8M0/U345SbFrUFb2ZlihIP4PNfykYvofCm4GgDoeuePsZ7PtsFOJkgZomOQiQg300ANvF4vN0GGok7Lf1Pq9CvpDCbWfmlg8pyvLTUUFOI8Bjh3r7G0AncKiwQDiPXqn7mFwlMJaumLLh2Kper0LIrZYXSvU/TavxL3Nzca8GjWbJNUfj+HC0M/pfcmvpwK+XGc0qvmhBUkw/Ri2eg0Pn9PxAddsijKsK2qe/FgDGMjQUvVmCUeg8tj0zCKa8RgEDpXWkwFDKtC1Dn7pPtUfCgYMRmCY=
    client-secret: AgBixyrpKvMigB/9jkyn4F5CUNpgc1G37Hb2kwZEYN7KkM5OsLwK1aZrvsb6bQrew653t06qKrT31aozmeSN0QaLu//HUn3ExPystMuyoCM04turYMKPFsLKvuxbyOuAjKGo/jrRyew7pqKBEQi4SagrUJ67oVaETSVwQDq7oUF5MbD0SqiAWtDpnc4DWHEjLPfrwaGl72owf4wKgJuHCm3UYR29BDdOsr+sPc7HMerrF67ZKMqHvt0cEUSh6Hb8H51pxYaQSB12SXdf98XzSsJUPaZiHKc5VHH6Qtz/QCABHMiM/rG/etG7MVa96XeQ5FI0LWsMhC31h6PwXdDdDadbQ02F2J56fpzcQHR8wKqic2LINE+le2lo+GpxmkrNhA7cM3bo50jtoVq0HQ+xtepqrfrhnVhTZ3+RrTnp54GdPWi3hqKUBREC08mpDlk4skbGxTUYx+4fcPEhzB0DjbKGpk2w00czRg8VcvyDfJtIsKWMMzXaeSZOS0SAvz/bUUGC0V0DusL7ULe49oxbccmm+Z2beBR0UUjODeGYTNnrzvwq6wB8R24xG/CLsCYpvCtvO60y4WBuOpEAgyy1k/NgLA7hEVSZwEuJidUHX2PDACDmuefhDk/M8rjqxGftpgJYlinl3TrScgwndyevBQ+PsQBAI9p0YWHuSRu9mvGlRzRRfcVgobClcDR5FXiM9nQPhfj3GRYKsBpiY+fyuwO20fsmaOmGZU0=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
