---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCHktCJ1m9OEjYU1LPcinO2DNNh4SdN+jFwR9LC2qw32J8wAl0BcBlRz7npB2vf0RhIKfkckzn7/ARl/m5fdtpAR4poUF0bdafS9ReFbluIxIVXaEdQqT9o1BuDb1IosTK9G61FIE1+yGISpWO5IgLMQscT0C7Rrje7Yyy9lfM87aIarkwcnD3HjjZ7nEsiXl3v2u/KDdsi+ryZ4EaQDmGSfAwJwRFfAIXygyZvSpKOFycYnXDZWby08U2e6s9HoLjQ6CTfspYXGbUMdr+65ynSxifAokvkJBVoSlHihHwpMYkkVOgC+5V3dw6yuN0lb3JjyKnxKjL0Snw/jHyW9DQ6eK1DfZw19ohwAzaqhB3KcW1ZaeNme6uDv2Z25GxkQAslGG2IN7j5BHsqdonkxlYM8/hbk28PSvs9lbDUAJgvQk0X0poRXDpbbVj+H9dEaOEE4EunaCNoB1OQkEijgMHRz3QoFwr1pIjx0TGv2Ga2pcBfxF5TeY4Yy2BNe0DwBjKMM0WMLm6RCXZRcg2+akm2nS3UU2WwpOS6Dr/K7OepB3Vkj2FGXFs0G2OvnuCUewSAldzSYe0TiDIQh0CmHoVhPo4RzDtPiv31QQzGYzFD7vMk/HgzCa/3jqVpjeQWX17QBDXODwtj1WCT0mxKmQvogqaAbVg+ETM6MwV/dA3BBoRg76D4orKZmEsMVYeskpHH6BuyLhbTD5U=
    secretkey: AgA3M/tXTureEOSrcwDgoBML6Wy9vTQgBJzQlQjDiHl5mUeizmmsSz0lbFZHOQZJfpD2eWBbq8vBtnN9TqR8XvSWC1aGgZSGbKIDBqxzhi3jzNLf6txg3lSlDIjIXboa/fV1rIZ5G2HsWhy70GZBEML2KgU09uly1F2bBHRReGu2jFF6Q42NGejWAFNLJxyt7bCq3tpilz9Kq2JECGU58Yvw7I9Wx9PzefJzmylonp9HWkGQpTO1ZBW4JsjAqvPDeCUUfQkePyJ5nZ1fppHdz0A6Sro1azg0rf4+J/LjC2Y1/RIZ7dPgKnGVgKOamu6rmGk5T6j6eZ2yjervZGtHdxea0VrkLgBpHARLVT61dtZ2j8g/GWaKvb2ZaCj7o8WVqRc71oN0MCBktETjVOaBMZa9Rp4hUyGZekfOPuZ81V1ui3WwrcAGc2bRae0BF+wc0Ft+Smk3KdF+1F7BaiCS6cn4Ee8XblNijXoqHhVHV4lN7LCbMt3LLcmESLtQuhuNBAU1Rs1Bw8wm0iEPJdWoMvEcZgODdpd9Xw9VuldWaAL5r2ck/PHfa6sEKYSWQqU6eO0U7pfxPfmoxTj2RE2lTuvA5srWsbJ6TId+hqUaw3X5RAgGGwhh8aFSQWwHP37KFxOwuX8qIwLoQ7dkRXTKpS2J3NzDgNow0lWe7NITskAOKBv6dfBUA5+IPkN/CsvZ6nw408D45/ygYEc=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
