---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBsbiMAltwHeYs+apc5qVATEKWmFRWzUe717hP4BwRZLjFke//It2uIILFirElOb3eSiYTFfvWUJCAii585sBOiLbIJ5ionkStaFb7xByeMNyYyZPftuUciv9x+nbPOmpEqDi3hbXA0WNgbHlW4jrp7OG/amasyvcR0crSdGGTKd+zNqPyfmZK7ZLE2HvGrkDMWzLA6XPtcRZEKlsoSqZVwZcvjWQCyHi6Xi7YIngygFW2WfgEZ1FsX37HwkIa1zCGFdwUvPZ3baHtKIS14wVnlJXGzoYKrMjxBxUOHRUSH2qYkYcYFQ7dxhHq1cPevWJoRpujEWoG2Ub3FXgWx9OhbriJGFnRr8F7ys93Ssk4LOMSeNoeyZiO4P6sjWnq97dcogmEBZMVy1tJONbpxnhqwddfxLfJxmFPkP186Y1rnIo51TQ6/SP9jpchdG/26T17jMAbQmfx+2PggApdWFl4zk00bN/+bvBfQXmi8dcToloeY/8yHnPcOaFSKWXLjFrbGKbrnCpoEcsk1Mu4mXkIK2+FnOj3Pi2Xm3g5P/HWebunl9jS8HT9pu9VRuiWNk5ryOk31iJiIHc1GP4HsmnkmO7WfQIYwAyYAQtZeCYO8WDsUcIOQT4SR41JVC59LiCL3NxE0F9fRhc84vkc3CSBtGai4doKvjt5FeOIkgkceyzt1M/MMCeIXL1XYkB4ZQ7NlzsIcpzf6OfY=
    secretkey: AgBhBSQo+55L7BI8KVrfLfvU6G3viBwZQQ7qjR9Dj+1g7nUCY5XtZCdP1u5F1RfdzHpcNPqdlihat2Wa0kYVJeWGYdtap6nWYqE1EaxY+QXhOLQGnykRZNZhG1jVB+PofxwMkXq4XzcJquIc6VPTLRZUF5tyFOHFXUbLNNKRW0zUvS9FVMqqclZbaErqnKwKXOFBxBgNQEeGi8o4G76beLe1vVwQZcjP0CmHEf6qyC6cHk3fElVcIjihawH5hxwagv7jEvbHx0dv4WBltPBTEXVYQqHJbrwcVBRhFBBM1jLdvXU7atdSLleV8JlU2s+5CuNOZSHb6Ssc2mMt6rrfnUZEspUq26IxTYFw5Ym973H3zR/8MCt5q9qwtq/hxDd+SndTTv1ZYn0vbRjI34ZysoGjtGX/WCn2ypXb0soYpGXONhTccPUXY7rC45PMIcXnXplL6kgwFuM4h44M4bWL8HKyA3gv48Ul8vmRwWrvYauX5ZKVzmdycGYC564S9lUnlJJs9OSmu5SGQvCVGGxZuDw3xKGWSWsLG7aFf7BQcA7YH/25vHCLk1TVX1et5lkjlYVcTNxfBk+bT2Izg99Qb4+bwVUVcNXVM0OA8Ej+JnbivDm53ALe5rxB6zw5UypMbMXFN+gp+XYvgrmQpJwFrUORQpW4dd4K2eC3/4PMQt2lugZ00A4ih/HwEnYk38kbLPkbZgFfll/m7Ko=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
