---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgCsJooxBmoh5/f90HovvMDmqokTrA/wVkHV1Gxn4kyCc45WM+6cWiewYqUcXuQgnGQVIpi0TqAHdXZ/atc5P72uKJzWfzL/a8YYl77+zsntGFefhp5hk3RxGUMv5vPUAR9ZyW39zg/M8xHveYtfeiJ7smASJSKL+AJdyjfvcjkCK+kze2ZPcFdZBJfHIZDdMhXeu3yCTjAL8+PUxjeBWLgHhB85+44N4hixbu2tITDRIB+ymRNY0hQVmbGbWix0OVX6vKebHKsSh/fhOCb6eg6kb/NIsUIQ47F2pv8+T+ZWVO/2DdvrJqy+fYJsAzq8EcwiXQFWYVkiCb9EGhOk5DY2KJ9lpfZ/q1NGiubFObp8rkJVJhIj7StWPVC5rm3jPricbXlNBFH8J7kCHQpboYvjzTkJIvdw1dHqLsb1Tcq4g7dptqxMXLbRzgaPGUzD3fldNHU/hIfLd6CChLTAvAkp5Objvs1rolNT8ZGrzhWH269v+sD/9ut9Krxy1CAsOdHXkgJ5PT0KPhvijRFn0l5gVm67rBaJpHV5BGzCiEm6ClqHsnhj3tTPWiV4IxAjb04ejQRRJSMLSJPPYAXD1hWFgtz6q+Uca3HBmMIIpim6KSkMYC9DW0xZQY2wRYMwTUqOzpvClFik2Y3KTiWheYtSfkS03lyX0dKIf+rBPxbCuFrkphaK6k1ciROPSu/fJ4FvdAAErkIQsiZdp+k9q2oAEzc=
    client-secret: AgBlCkcBNBQTW0ooZph5gZCl+vKNnAbCeNykFFJaLD/GIzJ5t5gIfYjwP0AxVemK1065kI29sKQVFygpo9Byc3ojwOpRULddAXTd7G7bV2dfxi1dEECp6iIpOOiQ6tRaKL6eKRFRlL1F2C8ZvjqNm8Hh+b13YxU+CGXauZmgevAz2+jPKUgMHRy8cLQDP7zY98lUKNuZMTF8XjD/ODrx5PfwB7yG6vfAb6sVKZ5PyxMS4Pa4gDVP3x91kT/6Yddyj8/aw2Jo8v1uu3rENJ5gzVJObETrNFWAW3MzO7nuGqn+RXA4jWtOcHXXJor0PiEx/LMTrrgTF50n+tQu22xKgr8WgG/ZZSVd01nV6NmssC5MLg3iI/PJ3c8LY3K8ya2JNQn518QmzMh/OfroK3eR0cBR2Hw42IFaCZ/nhqWjcLU8ok1NWH9N4iDZkTKpfbEIeNFY4NKH4y/lMhq/VG2fpLF2l5pXEv1MtXppLi7J7Pd6u+iM6aJSouyj2znm2n9De6DMcb9txZBCDM1YPCVmOEqsm5HIUonEZOGvvX/tERu7icndYGMmFawihFJv+R4h12LNX83DFtaKRMU/tZXxRUKgwVq3U9Lx3Wg0lQxvuulQ2abyp7l3+w/0LNeo6W8R7DzwumliP9k/fhXLzyTweABp1DfrABvpyGfx/S1fPnKhZSyJx52nZo9xFZW29QKMbZWul70W1Fo/PxRN5bVdIUJapRoiKcVQof0=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
