---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBVKBJX35WWbFsIb38Pe/uZi44bvKvEMe8F8bsHoPQCJOVVuN1TEmL3Xe/Vn5euL9cqeC/4sna5iGwAQPKiu0NThADoXdLZe+jLBlvyd9d2lEuBoWDHkN1HzTQ6wDlBhAtq94j61SuX/FjYWCZ4rxIPsv3nBQZcTpVekXaTSGYe+8mZ6aU7PlWATjYO6dnBxMVckZz0SMepeNAD0KL1XZP6Hv+Sob0iYAJGcGeXtDzLX2Zk+m8jwWk6XHljgAZ2OpdvYX2clj6zQAMFXu6XBgs9TwH4gSaHN+FUgtKOxpBW2oK199OpCoNdyGxcgJWabn5am7Z06YpKpfVDPBvhFe4cr4L4ReEQy5RQ8cPVh34kLtbrXFZNPBFNg7to+W8IdR5GTxkZAgReetWbAAzGNIvL6Qb5LgzmvKVEwX1+lPFqjHhRP+5yuSf7Ci0fa5odwffp/Oicsb0/TEsgbWDpkuOJUBHICA9VLOMNlK/UHcj3a/a0V4hZnoUz5JawQSi/7yNqdcLddDUiV5sAY/ZzR1dnfQyb67kOXouLLQlTOb+IzFvpEyPc9zdmK0gXct+JeYZP2RP8wiZzRIdXFb1zHv3xFaZb1rsRBbfk6JYu4ZLSIH2D08+33eybLehqRw0ZfgNvW/IohwKwmFpn4U6anP3peGe/Khpf4nyNX1hlWTNK/fVWR4a/U9vii5Qqw7iLrCrp+jUGlKFaZaleESDpiCyrAwY=
    client-secret: AgCHO65QrEqDvX81zzPJ5gOLM1/J1juz9RGVkvIURzhK/qnoTiokBVrQtBXPP7XMLDBSBT+WdZbmI1Rjl93ID6hGV7DOGkNuPUKY8b3R9NjXOrlXRzV8Vk/UA0k7z60mLlsUYLSjHUOukx9jGiZlTE0G7y/97rMc3nr4Mu/BudYz9dDQ9QSw0b/ZyvvUyFA4t3PMorzgA32L9YOh3HPVDw4KpGtKNC9N648bLqKjs8CsSDlRHQpmuNM2Q7SR4oLJZzec7pm1BXPaXP25iM9Y9c2lOwpjlTT/sShH7cHQqPum0Dz4pox3PV2901ZL6DeZwomLKhGTVlf577K5u2VuKSgVJnRzxwAnyqVgDUcDRDY7qdkmMvA5UJj5M9H6rxDsXGlQlLiQPvE1AIANea4nklmxMZ6v9oiFkG0SitBoNvbgbjiCkCUQBYJ1o7OZOeOR+gGKjMnxLX087qhYuYIU4pNGwEG5ixUPrkfzqDn9s/S+1iCLBr7mjkA69IGynHidQHih+Yy7RByGugq/ENBG3gy24CUREvcCNHUh87/Duiiz8tMHj/OMdQZkJ2Z2kM9+AgbGCePk5v1o7Wa7GydCHhEUBcyMWSSVU62FTQbx2vCuCbo9URKt9EGub93IEy5KszlY/fhGb+O+dZ+Z0Dbl+rzdV4Y1n4CLfsafdUNoBh7iQ43mrCq+x8M3jqWaT88b1hPVBVYEd1RPUP3XgVyn5GIpJ41lQVCgWBE=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
