---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBwKLNbRr0gY7c8a7DttERM+HKo0jm/WwOBdOLxLJN/2bcgmOHd4HDgHpMLIjNnHnF5sQGJErYzk2ncRAh33v1xO1xehh3vImJWiid6I7z5beLyaofj4SBLzCOb9Fw8+bfKkt+q0OMo6zk7o91N+c4vVQP5jpHZwMnHFarngI+ouiIBee3P425TS9sSiRUWI3HNn7IRDcVFQ6glFTFTrvVCXNGVmKiJcZ0jrCfvsmbX24Z5lEnlUgtzWkZTg1qte07X8wl3NovRlxMNQCXxRqgzy7iqymk/eOnxleHxFoqxzXIH1FZPYMekWsG9vJlruoe104mN4MGbnfjm55rQw2SfG3jxtE2qlXUYSHCJcilWIOYyTO6RZSBsx9K2p/pbeMKDO37RfTwogNv4i+MnrelrmKVk3puo7Hbjj+vbA+NAdsAz8HmZ38OW6+WpGxB6Ehkd9bx51I7zw5dPBWTj8bWmzZkkr2aeCxH0A9Fcb5nkYnkqpdJFSXQ+spjN4cpk+u3GDWOYl7ey3KXvWhbvPa4PZLn68hMe9r4R6l42YGx6ZDkPJhqxL4soXy8S3DZHhOrVL2Ihz2mXJDzccdQKH+BMCZkalWayQapx428GMQ32ubGL/kE+e6vLIoDPQUw25p+6ofFbFCAvTVfUvXGAn3GWHHYAL6PHP4P68UQ+SUDfbOq1cpzaffNk1oizfA9prhkHMlrNKCpvePg=
    secretkey: AgB8es8FBEJIi3Mod5Jbe76QrBjDxIbDYdyjChWxi9/9eqHTzoC4mD4iK8Ww3LW1rRBc8FJMYrRnYGUvmo7pm0YPPhq8WcbIsVWSg3oRaZbnjYZNyDoQ+vMEDl+dUKEema6SSgGXL8kZMbzgaI5l09CaWyIiIKqhW+VWypxXBedzP0H2jHyv8r8XCzfDEqqkdZWOUfVm0sx6EJe5TOeKSxbKCNzSZ7Yhxvrxcjlk4TlVIeuJv11uJNgngB9C+qZGNJJvULRa1hVmm90YmAhmYRr2umNR6twGraBOoRzJuexLQfDuAXe+7KuET0zPu8oKgDCpd/BSMxP5hYGM9uZW23VKw+XK2xWI9OJNfJph6y9Zvy9Q/q6EgC8wZsiGOeb3wtCGF4eHSyqOG4LP/4lHEpIeKjlEZvwVGJrrOLs20eiBMUqL1uzBbPdOuKrRnILLV/Wpwbu+JKI7rkEplP/xp8x+K+LM9lX3ueMMQNZt9uM1ttGr5IUV9z0COw8JQkgr3gaDIUUyi2t7TVeyHENc4hyxCpXrxKhy9ct6mIra7NYGUy+WmfuIq39O4TijGkaOznt32fTMZXgYQiNgfCocUMC/DcranUSyYKlzmJFW62Hv0zWqMdQQZULnvNyVRjmoX1HHnHPsGQ7eNsyAMxpproCOxcFhMcvY12BN+LoeFwq/F15JiLpVOEjc+QaiKf3Njz+4dlL7TjaWIec=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
