nameOverride: external-dns
fullnameOverride: external-dns
sources:
  - ingress
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey