---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB2dfZ0N10Igbu4zV70A6GVgdKFgZ++z6caRUjGwWAnDfe58lv6a7vREMd8di2U2TEaKg9X36E6uwNehf77/7elTu65wDcJPBBaTwp8X2ugJYSKlXUDrp61SkNgP61WRXOzh1E7HI8vM3LHBVsNyrFf2SQQQotxiG+pv9JfPB+IcbHuziNwYnCd5KIYN84InXcmT8LThs+ZfwFmoYKSVhvbMOuwR8di2OoYsHSUG2zRxFxyhU9bkKhJ9Aa34zjrv017MKARZ7kxl8bdcRJ73xr9XqolkiDWi+d/vkZ9P6V9SpFjMvZDUGeP+xDlfG01SiJGWht/ye62LAOCra5LDQSee/AVK2gLuUQnhuIg2rPHby/f69ZdqhyfkuVQnVUcq12ZChfUuIz8AZXtHvIfVbgY1BAFzeWLvoAuEAgiujZDpRp7VCbS8R0hBjbf9VyhPuq/CE6CiJmfokmxeoptc87dBpm0iA4UJlsaNDMPtceFyPwmNwSaGepk/ZD9TZ4NP5Y1T1WUdZ1/jbKWHWcKB1Msa1c+0tc3xtES2eILvpCiQwrBJ52O+3MKl/TTkNU/sQe/yIcszlDoJQL0jZ2OqiDCgLmxiKIzELNiIKhuAU+KQW2HD0A9HaeZBk/bmUOIy7HrEoE0UeBIxjf4PAo7zqvWr0fuVy6FGvLQogejD0vi/tnb3XkQbwsUEbJxy0E2wxKvK7aFJoyxLIR6M1OuBusosAamMuU4AI3huAde0Ug+7iFX9MdEsIMmR0S89wVBm/5o2dczRMpVIDpmQxwyJT52PUomJwnYT6YAcRYQm8hz/JkKTchMDzVYyB6kE5UGnY6G0hx2o4I9dWaDTtmuOPsSkD+1BfHx8GKWFLOKvMq+OzAgfVJfqCV0+VEafnWhsu88o60oxKmbRLZMUlqVk/Bwng==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
