---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAUyIeufII/Tz3KbqSZ/MyJr7tN2hLg2TVPsKEz4CKQObLc2YWfP+g5xbG+v9xFRJgDMGq+UzvX5gBShFapclnb3yet0sOcL9csISTd9/cNl1ZJP0nQlvf+r9NWn9D18vFvgkRqndnCAOdHYU/DhjoIyX66sjqkgjaeCIE4jOhEjsinHuj4OMf/e7JIoM/BBSVRsIKOIY/pXNVn64XWCNGYW4447kgByVXWVg+TiOp+g+M2jEzF/tVdZAzCcXddPZL/767YQYjIXzDwjqGlBhtPv26oUlOw4p4/f/g6hFFCywGo1TYc7Di9mvfS1eGik/U+Zb8SfAUdOY+ApxXlZOCqFKeP2D21t6E955Kck3EEWl+bUiP9BuxOOrJ0higy+UySyM47CR0j5ozY6DreKUXJQhE5BWuJHXYtexF4vs6vT8bNTHABDKQC5Qfab4unrREJgDoDNhOBg2B5Rv64RZHOHJmkB23LvvBKJxK0gBRMEo0hPs3uSMH04ez8Z9Rc/zz1x1O6rVu9+DXkV+ph8oOnge0oZB04yknJsdO+kxBQgXmyqJSCGIwaW7OBXIkbgbMrbNpr3UMDU94yyKS1ec+IOHwxKb6gI+t1J9483SmeEdvMIugepxXJPrkERV9jTonghm+CUwp0PIkls1HwtA+Xr8EPs/VzMCcyUbhMqOxVtItZVp36ZCd4r1N1Q//khqaHGwlMF8oQeMDAGkvIq57XxwjiHTa6IlFHz5seuvvbNkV3Q4jS9mwO6izvoFR0h2CHetlQ7Ze2jBXj/SFJ9UCmzRhS7k1x6DtF6d91KLCLjxoefIRupioQeL/yYI4Tug/xQI6AEVF9oVBD8RY49N1pxCXpmOY967PXYg5pkLcJlYHVYCx8R+BI36leDFPYT+aZ7YS9Uke0Dc0tZaJoxO4IQA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
