---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgCjJb4UbGTAwKl8zy0qCOQ5fb0976OgDTLxm4SgCahespTXLWjSFvWk0NAevgaypvu1ufTbNitkn9g25cwy/JXBazj1egmFgDnOqKMqIrDuW4eKhNBlB42w2np26+bVXsyNhYVnn1FwoIBuMNhhMh+C0XcLV/2VivJdw8/X8fiuiLyN0CoGqG9ISZh+7FR3Y0IPELEfkUC20+0HAJut4KtrHRZoAl4ntTZmPROjgCJjVQYu79K7HobB8yhs2XgLaD45qmIcooPkasK4SFsjclmbcjdarmoFFx+pHPBmWYWdREtfIsxIaBfNBEUbWn21NE/Z4/bu3yoJa9+0sJOr2YariHzcleFArgn60qVLhv+Ogb6UbHIGOF7gPfqKXEI+KY/kriP5vWIr18yvA9ajTO6hSneKev/196mdGKy+5Qtv2rGHTta3l3m+zm5IVrvLcoCuY2bW1qWNH+FKboK9BATe/Bppfjmll3kCTSWZUb/wk3g2XfBDzujMtZ5XulI1grWL1rpR1OOHXUCd25DRBC49xihIQjsNhsgssUz9jItmqyh4xWXOeAJEFj6jNNzrjonI8iIMFSo2ClAIp3zqBJXeCrWdVQ0FxOI/IXigYlLx2JB1NhGAiJJpEYqbx6qD/bIdNIdtZXrvmuzvLCrJf5v9wmJ3gU5Ek6OHm7P/ZYwiSrk5wUb0SffeleKl9CGOVeigdCLxdqqocjbO/R6P92qpRiXn+Kot6+eL/amlc6oSKjlC525Esb6D
    email: AgCBbOh6WtXSNIwo/rSY8VLoKAUPNLUY7iXyFAWKXQHr1FG5bLNJQXujSZ5D9RCenuE5s5HvXuwrGLxknYTP76nIeFc/kqV6qspEI5tqm8QiBeZzsPIixHntdWaPCEpshoGESgyJoTA1he0IHpUQZEQlTYGtHDOjCLUwIG+t0yYuwFxjl6b4rJB1vXTJ3F9MO9XyuMSXOf5ZXYHYzmMZzQrQ022i0BdTFkXvYcju79UaFWdYOSbEulAWzERzUmZVAoxtFYu+nBOpwP4u3I3GxNIaWzzj14mfGKuy0BnIrlmM+q5/ETSgpy0N8mvfzjilUUB3tb0mb0p1u3iJARfPPzIr/EltwN/UcLQjp7lfhLaRqF///LB+mJ3OvYrQ3YJX4SVGRNFGyKRuFlI+dSdj4gzltyyJVSBDdeg1hb2xg9dtn866Z7pThLW6mt5j2r3LJhwDUOKPzDo7aXfomZwk43MQqRK2uRU0ZfnOPncKh9hgaWs+b/MGnPse6is/rH/Rd2h7MlwKuL2+p5WscxKSuh0mVzUd3OGaytcpTuBVPZE8Zn3BCFsuKm0zMB9DUyTpjO5X/+erPuhLybU/MdocsEm95+OSRoNdmRfrPSeC6o5b1E5kvhnh+m1HZb/+tk/nSt9SoZp10qGYFizZRZnMUUdoS0xMwOva1ovLjnjSH15fYvtvNcaipyGNS6+Y3NipNMp6TZ1Laf1w39bzzu7yAMXfVuVoRjAB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
