---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAP1SKxvJkAEaLy0cOljA7dYoUV13CWT8L0HH8mF2AhSkgg6eMgmFitpLheUDqxlD2FLQjolnIf4NM63zbYc5Y7Z8NtJ5pAK43xqBUuNvhjP+QPul9BBO0NUNBm8AqFznRKlef5Mtjj+qj0Awvjc/wqF1QMgPYz/ki80QBdg4jxYcac+BtQwLWWvK9gJcGyPFWlw23GznVF80llLlgBgbjHL0h66dRkrJGnQpKd+FHFvVLfv9CSfST/8AFSKrlm2zt21ZwBxkdf3voRP5cTeu9wct7iPonmUkHqlxkG9sEr1Jfzz6eQ7wv9ilRim4a8LA6Df0eIeMourBnO4XkcYXa27MLXrZitrKBBv9tzpUZguRgWXOec1Bu7QvYje82yiX5S2a3WJadsnRHasnIsc57CO6zjOlw7HTt7T2MmVkA82exQbm0mSyymkMpBasnqThd/c8Qj8LCrsdFjKhm3BqJU+hWI6jPX4UqWxt48lBc8lLBhVvD1EzyprqP+quPH/WJYF6/2ISQooroewaMn+Hz5983/t3cGupjdZB93aaV8FjpSnajmia1/zIIg0656pV90TL1Ow8w27+QAnc7XJPBzkESdCxE9e8ERDV+y2v9o64/fVc7J/PHTW9Qngrlt8MeKAQJrR2+x56QDXyGmS0cbiqE5WYOrjszgJo53DnZI1/jhXON1LQENLKOj3rnd9Gv7JaBHHP7S7hvI2IN0qthYe6I5R7In1yRU2YgN4T4+3Cp9Yz9jeKrH8cZndcEeVtnT2VD9M5jSh9A6kykdtsgHBSwV7dpVycIuxA+rix4zYRWSBgovNlKpUuT5xGvGFSCPgKGATpv2wE6WHsGzs/N6wVSICAilTxfo2Jiph/UpTfgjVQEMK5gbaFl9qBMUeIeFv7AbLBTI5gqMfZefzZi3RQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
