---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDXcdG8TOokOvdJAb1iJ5c2uUsbH2ToouBIpEYTpEaFTI1BznsfE9kiq6Y5je0QniYr/XqdH8kqccICAGfGvEHmF+R2igcixeVkNtn/674xNi9mJ35g/U87AN3J8Aod2XaDVqozYn1m9rQ5r+pKtsMnoJgbqPz61+Uw7Ow3dxbKojIWqbJfH4Dz7lAmkBw3RBDleaJbFSsJd9STd1/TcdaqhfHl37RtF1OYHNLDkOD1JFv9P/6UvoQL+85mnVjT54ga4ujCGshEc0lqmgWVhytGifRC9FgrKhj4dnT8xatbg2JOak/5thPow4YWdZm/xRLzwhTT/SP4Sz+eZ0KSgmD8R4JlaKDNq2XLaI+Iqt2AmCwezFLYNSeu9ZQZMVT7Kb4zPBP7sp/xkBhR1qfZIMZo0NLUsvzbG3HJSjsxeS6+fHu31ZE9hgXsNvz8FbPSCZXGKQbMUa0HHaIN4AE2e6isEnEfJnmDWt1tQ6Vnj+vSDxLVkUgx9yAUrj1at++5K8xqjRQ30noDSkIsPOu/pUxPmzwu7M6qNyywMOTslWMfs6C7qsuQ3zlS2eE57KNI1c7DuQ+8B3qTLl1WMgQZzUSM/084T/PEhDTRM4UZ4nQ6XZ001qdQ9GECiaTyXwcaD4C4JA2mDgS+rnmAyjwx3E/bpIepHEoMKPPcltA8MY6J1RNnquRCiXA74O+TSqG2YQZoFPRFuxTVqdcDefUXYzuGrpEPexzmQXsprjgc6q+QAAwNRTDCq+bIVicHUJxrTeL1n3eFlc4O/XQnNTVWqTgLTYEbBLtvFekbh4Ghxy+mmyO4rWZBKNZx7Mb897P/hZHKAYZsgjqYJVeAfJs8toVDIbJE/Y4Cg2x/6d4UROvuB6ubr/FQ0EOX6j2H0BgaBhvANmmotw+Y3HnV6CqvuhJkZQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
