---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgC/3L1/vmUIPmwWUlz+doch+8gXYALL3oGJ6AE6CNvPXPFn9KHfqtKH+qqdUqB+2XP1KDnOuPZRHBJoJxcoCFA0DYRPi1QopAKHxPNP3KplytInCGMcq1UGf8PBm6xP3mqKPKzkre8SSgqOyrA/N2ya4A14NQEGk5QOUZrSiAlw7ylbeVb+gEaDlNrpGehnErYx2LlO+VArMV9/94uUryPSyKgNM0vddTgS1ui0WkLpiH18uFpn3OSBF9qJEgCNOMajwsE4AdL8HpYHC96vFmuGHrTPGJo82RDzw56O7lWT9zubkJemYGCG644ocVaaIVQezxrQj4bWZNiZ+ZihmC0cTNEpkebLdxwrqmkKiofdc0Axkp7SItIUpc5H0dOueVACOWV+PSo07gfqZaATLuhscPXvvrln3pHEwHFb4OIfUPnTrIZkkNxyRQ1QqGEWk+FiRrBVrVe/Iv9B/ztLDhXLEvSGmBSnPhdkRajPeZ/lGjMW895vuvyrBEOiNnjESK//lCIUUcP7s+p/noE53/LqTIzgOn1AQCmrCW/a42Eu1hJD5M3elo998CJcryE3qAL2jCXif/fVO1ajq083nksILIoLbLBs5PHyQZdA90GAIzhqRsAlAXVvKPEpwRM7s1H76f3cjdXfsnKEUZjLUTfEMczZ/7Sf0Z0O4hLBpxrSUSoLIKCcRPt+s4QWYi+Pzf+4b8r70hxvKcsHbjgE2X/b4nT4l7ND/GIv62jaxA2nKeaH6q46o3qXe8CHyNYYevz+6c5GOeiRZwl7UqYR1Kf/CgjM9iT6mUzAH+dtDwf84oNLgK3u6GVu7ZOIIeDeP+vJZ88xeeHEwPzLHTrB9eWBS/nVqjhBdPjEfQ3KYhDsjo1rSSznuMLqeKtE1zcq01B229DvW63mqANir9l383YATg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
