---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAbuIFtc0PebZnlwGnBVaiuKdrtVEOBSWuJd798HAd4IIMkAITCd8eA2AhYM6V9koaBd/i5wK8o4HviFziAcQDzB8gpGqmD50p6LNjEtIouxoeNRu8x8tBuTWo+vlauG2keDuYT1w+d/rMOVBUFqR/+Xg3y/AeIKOvtciCfvDjZRHfTYAu7e3nav3d1f4MGJZCzjfiWHG+3o1yzTREKw3QL5PWMuVWjplPQC//opjnLNydJETHrhc2TrFU82XH+GxDn83mU6vq2Er2X8rSC4cNAlhHS+NYToxOdS1D20Xiball/oR81JvMWDjIM09ESVbS83zHt+ez1mgcXun1LiGrtennf4glzhbBejWgI5J/E2tPSv3hQwcpXI3bF/0JCzckqA1V3L1+74ksihYQnRvtO3eDQ3C2rMny0ogX9QaJw49jfKzR4+mYN9iUfElLosc7UJtxBTwVRy0urB57IxfsklxCTtys0UWztPleG77FDRvKWwFcEnDZ0l+Z216QEMud9R3UEprDTYnKBM8fTeDEq33cUjWsYBo69Rrt8vsdYWjiFcdiQm80zMzrerBYcOgbkou2hAgxdY7UL5ffpvh+kBE6woq/bW2k5RRSHxEgzwZ0XNiVA1RiUioB4TzolUbqTYFo5m2UPSEEXQszihdtTuJ6qXBJnnNx7ldQR69r6u1G4fehKOFw+D389c1Gtmqvkl9EI2p5quRKwfZWWAo7vhncUAx5rWYRMlCA3Dc2t+kDaj2ZnziNepArJbhYrYZQiyzH8fnQqGdJbMjoJDVkFHzs7EKIBp16oNekr/c5/+rZK3ycs6t5KO7BS+tkt0Dos7b/lBpYNBG1FpNRPgUrdzI1R+Gng8vE70kHJAsaGvz7L+saaaWuj1vVhsjH280RqXVIp6NJgCQguIPLEDXgGLg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
