---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBcwWsp8QxvzhsPJyGOmWG7fn0dpddKMe4Dq1Hx2lzUQ1au45mrd081y5E52oWdlTzHxf//594V7xqhijllIkQVcVvihhkZE/f0GA6QPw0Ngj4BIWc8LtikdZu+2YG0eKsSXjXKdzMctKhC/XTMU/M/DJ4yQb7wGp+oK1UPKYZnTQ1IZoWf4TNJxb3xid69RCfTKGIvs+Mg8/kLB83ePXyKfEHN6Yh5ssh2m79FtlyZ7168HlfxhIz9P8taDp60fWdH/Ml2vT+UcyoMHhmSc5GQKgpdMpZqQeHXYz2DSGzPo+Wv2trNT4omxFRHzO3UBrXOLesEnDqrWJh4nho1U7fm5s3kCRJTP6sF30bo6MlgCDDOapDPTtlsYVD7INrImnRRkCfwyp0jeTrwMcPDq3MB1vvvlsnTMEaGRhUS/QsAnRAjd7IOjemvt6faqgrALeqMD7PQvXhGBrDki9lqpucCSBZDkbwTRS3ZPy5H/tY127riiHR7I10fNUpQIlSZmWpEl9H9YGY/nYSycvOOusPmijtMLNYbrWv12wJS3CVPreN6TWaN9fh6Vi3Gky8P2QQuF5Ci4jlOmu+pCRCmw8Krg4PbpTmjGsPnbteKh/eW0JSOuJj2VlYMVg1AaYRefJrW0SuiKZBDvTsx0OcYc3p2LWPZLmZgDLtHg5RkRPJWXzoft/gZsJH6UNPQ1Lri5TKWZQHU1HlYM00aeNpR1EIqbbIqiMUWwtwer3oZNvk4v/knzgMiDmq0OqfJg3wFFoEBRfYj8BYLgzsR4seLUnNJ0bWRQF8Hd9uYLASsjIIAkJtkZu81THh/4k7x/oAbJKqIfy7JpFYYRAzYGJewOiADcc2X2BBQoaflub1uFffcDhq2VMnUiKh8h0E3JYNRDQzuRoADJgQ1rnPThmKhrPbQJQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
