---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCxiPF7LZeTRybCbElYqYc/y/7big+f0uJYdqn/xwXBK7bYaodQoQedfuqzneXAr1PolYZ2jMJBNf8Y5F20hBj89i2xPayKak6MUi85KNhrfOiJpakSY1JTGB37tyoXytMQ9nj+2kQktPYOBOtJBKlTT4C0/hFFyUSiEbxBDoHXH5Q2ckc4XwSozl8wX6NtlffMlEPR6cMZrDObbhufVh4bmcR2N5yxolGzliuIEcVOfe0NTgKTcNB9tFPrzdeol5Ke+sVAidLJvjUxU+7MchLYo/w9gDdWbh0PnDZeGhPdMXnbeCeM6N81IrqFAP6c4s4i3AFFdDMdIE9zMgbvuME1Btqk8wdA4v5IETn8tHPW8g6RHXb38/TfYtVf1shsMVf81kmhOs385RJatV9Uo2U6nyS4bD55Ee8fIWdNdXPtgkco4Nr24GXiYGYDIBarl69WBsnfjnGny/Gzf1/8LOQgXCj5IOuf2HyoTI8+yPkVBfY7yb9L9f5a/Qh1+QvZ/DsRiLasMigF43tn6IobKcVQuaO/CcBjbaktsfC3cexq1bMrpkzomFum/WtxHwfBsQB18TZAf9Yrf8gUi2EzWxVFGOkmXTAzvTyeGQn/BlAYghW65hgYqWeWnOvzz7KtCsup3Fq+Rjb3IBarT6TgkFZT4WgS1cK3RlNhbRXkStauFYJ9m3lnv8+es9C5oa8PWUqvV5IZu2Vx93h+kqq+/67cfIy3sDRNcAWLNFl1ZGrQQgKoz4+0ps2wXCTMEA5EyV3jHb5FZaEcLn5K4RyjLyrncEVRYXUoHVCyqyse2rbS5FpwSoO9hAAFRRBlTC5BLFB35VCn0yQxjhT+e0P0xeJ44tE7ueEUmpPc60DEVGUHsOvNaINOpOtp7yQvtpQaC8jh8/gXxGJuqNmeW7AfO5HBIg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
