---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgAmOOTsEzJmx3yL6PQww4i1w2uj4abNecmu+X4zyxZB/IwITnJ6ldWro3riWUiY+GKKEfYSeDE9gjdDadSM3rAlkEC8g3AH2ajdDX+2nWcQ2Hgo/L7YxmSPvKvDNDxvrT9Er/6tqKFiw89mRvJATHENYkGF/W8VYi3hSCY9f+weYo07PEtjKfLiMLZ4RwptmX4JP/8iYfc9vhOHAl6Nx1bILwtEyNC/NF8FjaVSrSjB5086393TOug3pfCoueIBgyeew1mJMcsHcUi7xv1gs8TXd8SR7P6p2EZZ4A3bjnANzS2oC3S9a4JxnNgw8JVvbzNYDYRgTLRwN8Ak66uArCQrnTN8zU9b2jyJxFmYIwM5MSfNSOytFQPOTkJhM5fzHBjIcOnl3hYLFgXMvd3OY2SuTg+QZtnTPsRY4EVt/Osh8Yj7LlD29rf4VR23rflBuXVSU7K9sVyi5bitTGwu31rZH5InNaOjyXI3VVng4hurFhBZe+eAdx3PEPu3pxYnJdvKADWlAXt3UzozREmsygC9PlILpSdHGf1rpNkgk6qHWqz7Ye4cOshczc5AzMYr892s/sdgXmzSFnLC4O5XwT/8kiYPBTTZbEIqcP0ZOyFtYRxsikxOXBZTT46it5y4jbw32mnNdjH7DilStJUqNYriAsKJkJXRFWU/J4Si6gROCH4D27cSj3kcLIR0zmSbteWfTi0Rwx9P9+yiiEyvEnzuT32ueOIr76b3ETxi7WbHdDQm8umMbOqZ
    email: AgCDpSZrMnXABZfnOxvnwcUGeiG+Sq9HQOGGbWumbdUXWG5ZkHXlBzaWLWU1NC7iIbbpLDnkkKnB/PfVMKoHwQ80EtyB/kKOjLG5eyA4IdF6GRp6Jl/OajXnYLFQZ1Iu/mnrOo2YwvoO+GwyH2jUOaDQccONLQ/bJZMG4Hwr6e3lj1JO7HE8fdLaB++cf7y4TOQCO29VXBhZy0/1rwPvSz+8we/uv5U1kPF5phis8pBllN87bvbQ2+2UAepplBfhUyHVv6vBXpY2tF/kagZvZe0Cr4pBrGtoQF/UDqj6fhka5IqP/Y+gY0ry/M6RCzmsWJEWyGeuXdxg0ZGGoCxagJgXXzKo+0BjWAryAg5d8TL4CElK6hq2Ip4LkVhQj1Kp+iNDurzrtNs3zWXgYgjr8JpTvL1TEe2vqwf5LQLMfdu7rBZiZx93qYb2eVPndkXoVvJSpF2IYWYcUZr1xJDMxV6YY3KkOmV4JUdOetWRR8Kzhvu66W8CxM15TGIKyKc7bmsVU0Rb+SX1cVjz75Dm7hxgMjMQmp4oofa5Ri8pGQCZ0FcvpmOhHyPHEcuEFVyRT7u2JNMJ3ssQmDqGkFXXvuVUjbbPeadWIw4MRprShksISYuTCgnknOtkG36+kcSS5DfX+gj8W84u86RjiGNkH5lUK/didxL+TmwStH/Qr9ETeTAh58zyvoS0bXz1+vfqJmts2nx+yvhRaC1QoxJgL1ALNZsGjk9z
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
