---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgDAU0vO4i2PJSD/xzZq01rREIuKQSCr1l6uGPCv9RjkWBMIsbv+cXWvBE7XJzL+QzGdqKz7HYvF7s0gE5fGZOT7ww6ebOwG8Jm0yNroOgkRHfrWe3ynQr5B+IznEDYp53EZ0fOk73W/Eg5kfbiG0b+DunkCkUOnydnUOrmDgo5nP3NXVEHZKziSfjC6FXiemUTw3Jyj8O83MYdqkVVCXQ092YB1TZJABMhw1lzyJKxT8tRL6vh8KgPwsAd3hULsWFPxJrjQi5IBHswDRVZycdWKi8vPCh/A3CzExehqVACvJwpCpag5HUsMM1TT9oPUXlzJlrGpoVWu3WCXOSNnv45xOBJalFASIa72+wQEXVpl/0QSzYRxzBFWdHUI93lpeLgm7J7QkDrl+1xZZgpRSBSxfKE5PR7qeuOymvNFMVk+TJ0wRub44p3rzZLIRtP2hoQqugzRU7GvBC3ORtGRY78uTnacVW+D+ctWZk8Vma2Kwbumqf8sueFBSurvTH4XxkmhMtIYH/iZ8dVvQqm/6DB+TWoyls2coOTyLqSOyAs2q2BqKGvIvgPBT4vsjJZ0WzsFuDUQFH0ejBSq9cOfubKyHqp17cjJwHZ7nEnXA9t3qQFJQpJZdrN5PsQ3oY3oQaZpgiWdgiRZM7wDCHMgk9wb2jq9oc9Gzad99UzexPu2Zn8ij2bIQ/ObCr1MCIAQwUWJ9duF5JLBfA1W90tWNwXsbjxL3c8UAXGOeRGYRvVR9sgfRxtsYOmw
    email: AgCif7FMEQebQRXZn4W4w66n3sV3W10SQ9OEuKSSz3DHGeWvqkGjSaGy+u8eH3yoajXvyHHRk8k0mEgxGUkjrW2uA+rs+s2KJZUKn2JV/R3f6Sn8Z0sFVgbCd0R22ieWXpC4h15NoESAh7AvIdY8j9k7TasFI83o/MrvDoGY/pbwIJwKXLQw1ogva5L28fS/gv8ZiALHJ+79xEZ0XPokl+61r2JarWGZtzuu4VVcg47BIaQAdsNLZGGim6LsR97TFMg/YEdBs6NmmVxb8TDrFfCcSEvNZNqHslP/xI8pRahvgyxfhWzpzQqdMnkRf0TBqV2cLYPa1bmmUzvKacJCOaUWjDTaGlS/diOwTptRwoc1T3UcYuzXK8sruTfoD0qUAAZkYkv0tZCbwiVzcd3n1yr46RFP0ryqHK+637qgXQD9kyP6y7P8RXYiSqVauRYRpgnk3dvteSRjUxsLDSlU5O1WMFjK9zdgb/NI92+vi/kYCTBDk//2N4Kq3uXFwQoGFlIicvk/hVLbY9w03Ce1AhgwK/ILnAOcVVTYMpbI6ibZedB/oZvjvIsNPDyif153zFtuKmzLOqO3fidMO7wO6b+96TsOBe4uh1O1OREoL9jHK2ggtSYAhuYzWBes1YetRdlVN6atEDWBsM9hpxS8c+ZnCOogaKg/EErJISAn0ya4NL8PGfg0K++TrEzDiHUV9X5s5uzuntHFkVFy8wvAP4LKChjewNSu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
