---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCyUOd2qnBaGvESl4PYKnt2C4jA3QkXxWcilufMALSjnLZ/BnhXEREsTUIPQVfRz3j14fC8YGKj1QnrLKlANVoO2JOHLuc6YaRFL/ZoMNTHg5NXRsgc2qlJTUToZtyLLMstj1I8OuQuYp8O33gFbWATvUQf1nPSFVVvuoJk3NUvtWKCpRlQBodXGRIG4+m2cgwmZDOT/ZIkX+6oNjjegCM15Iliv5pki4co0XwxBOegQ8bemVM/EJe3Xjx1tWMyWx344S6xBaXie7Qa7hY3c0smhIkZxjC2GqXyLNE52IwwuUnugEzmOff+fEcr9aEAFkbzmmT/X7SAq78TMZVXxwxXvNdFlHEuG9BBcWNJY+ghlU+wohL9n88SnEJuw7ScTgla6lJ2uzwhc3jEZq9ByFLMg9houtn3N8PDKTGWM9WT7AX8EKDcuebuWKBeA+kjRJ5GnSBd+vYEZRxY9RfzyGkNBaAVhM3XY9IJEjAgHvckQwmj3xFEaKBOzKlWcBPqBllqqevgLQV8NWdTgqDqFRkWd3N3ypCKVjjRB988OrMuZ+7NKvchnQOCuuqVbCg+r0wa4eDDzczVNiMOrayj6Y/nG7yviGN3hsxOzVp7J30yt6IcCYeV6vw2FocZNBg8X6O1UcXCVlY8rvXhobwljwUWKSOxZXNPAwbCcYI/9qtSHq/LmxfeteHINyQQdRT5zvEaW7SM43DaLvCmwzV/9kBt1NZOwjFPr1fQxJbzyAS0pk9nQ6s3xGLX0y81EPuwiPRmRZ0b3tA7mWt5iKmQtXpYZBiAmpenBOyqcIUFsYYUnVhIGMFUVfOubbWr91TaEF70fvUqVHGl5VBFi8TrubcycD54wPZm5sEW1gOYI/YZD/UsjJ+yJjSEhE8FxEXV2RyZ9NdJ0K1INE+L5Okxczpadw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
