---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAIBWtUMC4VgRaJ/Zv6FyI5veyECsu58n6hV3EwiQSVnDx3PsxpBN9IPDDRDK8x5PgnD6CUHYCtNIK9vGr5hT6QUUHJ7r2R4xMfKg3UZ+tvklL5VL+303BCAyVe9okrwdaOUawN79BGMycS+HTC4cZ4Ea2+wtIDG1M6bDgfSZhQygHiDfg/e0j+GUIsg2Fi7pQq3xL79Mky/g+qS+w0TeS+FPRq0UXf1ccRLXnsc4Nw3iYelr9xrhHutjMSz2xcvQoTitvkCv+MVa8lda7SaokZiHwdfoTEgvMFTaYHBVuPUxyqOprLK5wBIbAKQPMB1HU54DOwTFIsRnDFOlCBr7oi+Vw3hmpT46es6Uat3u7Cp8J61AjpQRhBLG2nxE42Sz1mHSZit5gU7eLeit4pY9eFo3N17gdtUQ8zxOCueV2ShV6Gv3ZsHdBkZghBHvll8R1vBCI4g4hJ1Fn5nR8V2AVlwS/oGLhXk5q9OLxvlx4kQkMkrTeoM1NC4Tk6rQkuiYgpJNXbaTcLAWRIoCRDzA2s5Q7uj/U1RxphdHQNrGXLrIrCaZFDZpS18imA6+z6BSSKDzI6iXatDCRrYxpcLbPtadr8TvMnBzbsdQ/2hzVFHlGFlsseHFxnmvUAOwJoS9DL/AA/Q1eFG/RZpJGq1dJkB8enIsma7zbClwThwBQq8duO+oDsHKx+cV6fJhLaZpc6+K6WCYJH3MLUzyWOUcv5+R+v9AUEEPY+wOtTUZAU4Jal9veInZwjXPwIv1sbTd06gPwTN6U4o9nDmvsdK0Y8xWxEJDmGa+fzHmWHsbKaqzxpsKRWur9AJHOZOp6VY7gVdTREqyg6ETFjSm+YwNCFEZRXlN1s0/J8GjzFfvxm1VngsVC4KIlhevP4+l3Kwtkz+J/YlzDSyjHnSqjSNgu2yA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
