---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCCRFtE9kQvQALJEyuLVGwhIxhoHnOoSgx0o1OY/LKv5Me/tA1E42Pxz1wZH6uLWlYKifTOHJZbIw35wpW36aDVmtX/wFxD4bYLCPA1+nLBg9AaTq+QuRgKoMNx+lmEa/8KG66wFFb5N0LdkztCoFkwiAk0k8QAMM/kfQFJuKYKoqYlqyBOwuWMQhUmJRXrIN0JuMC/z9JvBlOGx5xLg+71muS1BS1yDHubebGl92oFz3thPKnOpdBeX5PinDgTcBy2ENStc2Rr4oINd9uuPri6qgRbAK7WZU7IoQbRGC5PwPxMIO4c/w+jgGhLar7+VKQBU+MtliZsX1A3l15paytkn1FrrlGqld/sgqCxkPviQUImXBpktXdQWkOUwPQTFSQEqFZNZNOpuEJqlfZYigTWuuPp5raWB3UUOFUb0JcYhp/Vg+Jc2nxIVLREByZEXuUzJ8VdexD0EwNMrHpXR1iN7hGbY2ddNitSAck3z6X434j9An3CHOXGHbqo29ybm0BQp3siaAfYCpprEP/ZYFlg8UbvD5U84QOGBUAb2x3f1W8bvaY5Q0HmBWlhGhGraqr+XrsCFshEXoTMHzYZMQp/dULxRgjQIguk4l9XKzHoGy2zaZIME9m7BF8pVxfhMukdu8UzhKAqmqMXIoB+AkXKAxbXzbSGzSDO9HHNdHe7nPP5bm+IuhZUgcswEmPqo/tBVV1o3NZf/1MMKJI21E/1TqM2ojWHec76i/S4bGUrzRM2ym6du68hAznI+C+ACEDA62fbOEPn2JEoZH2hfxZQiuV9MtlsTULYWagJ+RYIHTbszK90BJHP2CB78LAelEIbpLvQ2qaJ79QEnfd4Gs93yPQEN2Nw3DycMGhFzfSheKUglGN3ewou6HZyFKIzbiArAQckirmAdZuNVBvGTS/OXQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
