---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgBITpnxq+IBypcCNcwAtZLSaaknDlxdZNRRdA0Ljz6VBbccIUTTl3I6hyWGHe0FqrWOGwG19N6Qstw/OjDtz87cullxYYgVHbhUCOkEPvtaSEGSsWaMd8YKAFCPmkZVNF4AKifTlvESTgQ1iXZIf5854z3YJ1/ssm8qYp/glUOrQC0HTLZrm0U8APLrdrn8ijUETsTQxcfDmZLmATKGopx0N1AmSsGo100MRz4ESCgDqw+5ncXRAm+dzif6VyACcYoI+gTm7CBZbyDEi4mFVpEcCISFMN7cav/Y3Al3SSBL84I8HVr3dIiqm2liSomQ7E8YtxrNLtucy1YX2TF/bxrXrUeEd1GDbXwfdJjxuVvA/a1BmJoononMZlogMvp5JnLlUwTHPbwYuo3j3P60nFQqDnUvmksCdFsBaYQWmIRyfEEm4iLXjfP3PXp6vZ84BhBE1IyATKN+c222mQCsTNt3LCWEVDfXlyb54egv8redlxHIf29K8lHU5geuT9CqYMVvCRjcwSaNqhQ7tklUDsFBPW6PhOMeQdLzGEGnaAP0BFHxmbdLfDmDOeDOELQafC3E7yzDkCJdKrUhF3kaO3lTmDq+hULzm4PCOhk2dvBGkQUHLnmNALvJrgaaHCkvZXFGrhXS4wFb8J/4mVMCBbyqe6oIC10A++4npPvrMP8PlkgJRBjpt1lmGn4aXKhVVGDxhtGWYv2OzlRSaj5YAqMwVOIJtgQalM0mz4AjJiKh5i62a+vLnxKr
    email: AgDE4e0R+8H+9jeottguWgxq/rCAKWtNzOlYq4HD6bombWLbcPjzRAwnqA5nL4ysoRvpOnrE2ovAzyDD32p2KVgDAXrUGSGioJNVXFCITuoKOC03FCFj4gd+lENQf/N8EiU17kBV1QSf+sZhll/SWRsfJBnezU2ocSsTX/bzhZ5f1azRYA5bLILmbCXQPbpW2i5spklh2F1UCIos2Y0NlJJ42gvbTNVujYdNpMHcSV3HdWiQYTS/oB6f3cINYQgY7wq/o55VHVrrongcyHDmiTA6RC61dwqAC6XcTxtt8KtFv5ofUwCWaYsXueeHeIJlz8+BBaetOkX/1bxt729TLP0Cwf28VPC6wZ/ycwBCbq5CXFuTaqwFuTOxHvs/Pfcxe1/njTEWnUlRJ1pzweC6SqpJbQnhUclVWp8hUPnoZpzn7gATRgmBqMVSvbSZztGlRo2FDApXrzpXRo/3oumFsDwwt5w8PJ9opei7L7RLDzxodEhTO2w93+DsdiC7LKA7ZIP/UAl0P+9Km1dUFQ6kpPfnvUbi+JIkSsvGcTb/UXIClayYLHZmJkpIeQVKMTgTx0HOXzmAh0wq5LtLIibB7Te5ppoaFaJmsfFhhEUGPDH8rHFqFv9O2JoTFv7fnFhnQqumks4SdtSO0gqebOhdDsq94TPH4sUy+7z4qJdtioGz61jTToNZg7OYitsroE98+V5Pveiz7hlqxsYRzJ0Ob1w2UFLscatt
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
