---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDOdVS526Ni8c2bB60Fts3zTdrSZAqEmY9B7JdIR+uDUNtqBFoN8RLdc6Zb8AnMrE9oo+AZZfwrEjqP7Iy3LNlP8+sQz5EO7ZvnhOh41nKevqCtje5AoK1xyty4IPL4Qcu8Ccwm5RkeWT/aziW4H9whhQkoggQP7n3HUMMoZQETODiyRIc0fG6TJL047NyFrG1dI9lehHzojT6wXUgnq43Ec2bEe5EJIdRoZdiwbyttt4vBQGHKcHzaVVdHvFOy1UZTaCTmYgI51E2cYmb+izD2Iocrcbpu0cCoB59ODUW02HB0kNqgOdX+kBji/XjmZ41mfu0Pa9CqycKIexNtOS8uNxHzhiIb6q4w27B25XxeHFjtgJyc06nbxw9Ad7XDrCufKPVJYxQCgq+dvMRrnWG19z9TkjwY5ouC2z06dRKlhHn9YVwz1nN49iIt1mjR1U98UPuwSjQSnC+FYEIJXccPjmpqa1NUIlBCd3fuW0P2+MVjaRLerR3I3Nkx6uAcR+U5e0eg2P4lc7CXb9n7F+M8MzzFLxtYAY6R/edT7n8QWTN4elJf2fxR0BT+PFJqgz5ZpxX/DUWZDlV0DVHDbZiTMfZUNyrVSVen6D7iw2HhuvltPz4A9junOw+WcRva1EJDooUsxTVs7F0OUCCF94F9/kHBxpTbZ7AAtBH4znQhaU+T8DLaLAnvSbhBVRV74C5PlZaq9ALp40rcsQJIwAYwvwnvGhZvoj6+VR30ueCmFKyXtXk6zwQc3T3MD2vj7PYvpwvGrgvehDrYgzl971+1ZsT4XEmTG2e69PPe0onhh4qPnnGzUYbeSPPOU7v8uu8atFKmlZR8dtl1/lUC3w6sqhs1ogaqdZQN8Cp1aYAzKai0cT/trXpvu53Yu3l2owYJVjjsCk85TOZkpntiyCER6Q==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
