---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBQaXP/XOAWyCCSP/p7Hc3OiwbKXx6aK2HmAaRyRkJv/CzPglv27m2oltChLFvjIlRO6MRgxhbk9gMZeiT1RNvCHFOwBek/vLu3PzkE9esLCqdkXaM8+S98G2TkgN4L+Rn0Wl8V6I8qwkeHZ8uioVSdk0ZHSL0Si0GZxpah8GUCJJ+uAf45IUiBB518mbrGIq/rLQX/GYNhEOS3xafp86Wi2vXrvSj7sTIFK9GIgyO1u2D7TRrH9fvjYefzhjbvvuBHL2yic7m0bJOxZluTJ91w4hvGzlH5pFLl/GiZCfed1F6uQVewrR0vgeEYJFIbVLJTC7COIBxKq16o+WCWGF5ds3hbmnix3AB0whUCeZTLyirtMPEHhGpEG24Tj3Pf+OFBh3+MRiaYnKZECfR/W9u38Z1GQLYwdG8CuubuO2Pi8mTdoXPbRckIYP6IfxT+qdtVXT2lgpzl2B3PCSo/EdZNN8jDFxmB4FBz2rnrMycSVA2a56brrS7OdnSD2VmASOfrpxICndYn0RLRvjja53Z/keiFsZlNLNMtYZ3ECfzdjfibJUSxYVXmTtCQ/ziS9Cd5TTRacq9fqrzA9QQCGnRzrlay9CnNntwsYeGVhrCysLXGZ+aoUmqSvG7TuouBvpUB/5G91k6kaxWW4XEWsdASwlth4yutqPv+TNjx3JwAW1Vi/q5WeZ6MZDnU2MlCSZHOO8pyrH+5lnBc04F+krIFKXBUnr0JOwniSYkK/s07MYdbu7EIDqf0nuhaaD1kmtUr0RLECJCsOx/D/RH48uGhbgCjIQW2+U/FRbLJFFHEVVMIeExP0ZccxHfW72zxYGSwjeIMOlo3PZNj/dsmkC0Yc/VUOUrkQ+48Z0ZGpKEVWHed7x5DxvWp2nlbrNYYlV5V7NlyO42++6opR5HFmKtuHA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
