---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDeTOV2DxQgTnT9o7d6zi2vY73O2bjSNC6QDKUiCyWib3Y5CpFFhdLujjBXFsYKOBz7k1mF/icsslPfoSTzoJVY1E/hD/qPqIWAm08m1Ihx0KxMVsImiiY6xGXNnmsWV7iyjjfhzOFINr+OvqmfqckziNo65M8HbJISPrY7djssQ9GnEHybugkp43RYElskuLxeS4eNGwQrKx8p/F4NZTL+ahFPYaFnfgfxMpkvY9sN1WcKpM2U3MOU85L7ciGLl/dorBpBG67q6aCbn8/Dqpm69BnpcqWTR13ZUO7Jw/IXIwb9HBijTZRTnyGV3JYQJcss1kVUt0aQNMTvGiHjIRLlCIjOc0mN+u5wtDjkwOzdAkyYkJaj0WC0YxB3BhTfi4i/XSSzzaCXI3bNzKzsXb30lafO042T9/VrWt1dw2KlqY+vvlCcl0jMxAkI4cw4tdbYS1Duhz1GlctKR0ZrqF0YixVCbXSeumAKpG/AkD/jIxarjQpwvust7vQNzBQ5xBPECzuywfSHWAL7XJxIhndci0yYVd/HSq7YNDNm1RTJg8Fu2FlL6oQyV2KgPo9t07ksjBmwTz+FVwvXgHfkEZYJfXHvUOlSixxk0vWpeAt6uw/m2w+S0rF+MW8XPa/v5PwgIiyipgPAU7FYoniKjP21r7ihrCSsG0MUxY1OxjFD7S7SWatjfGzC5zkEVJP/P6FVHcD342RwteruUWfTCW3iQhQienyxgXCDzehyiz9fPt3q7RmQGNvX50QJ7MrQlyg8N5hpbFuYtbYR2u7+CoWoBEhHs9RfKaRjFtMBCaZFrfaBuGP2+eMOdn5h3pAoJBrtwT0Khr3ZUjKd1FCAN8dpsJPU+SskyMM1BP+ZPlxFjGyKaO7gbI2UonOZRfEOv9MD5iDzBogcOpGfhObc24KD4A==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
