---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAeKmBIVHPPUrpxtzZ9e28S1YQaEqMqbVGUf5i6beDFXpkf74hliidfJW7Q/6xV00AhwYDrFySJ5bSXvq93pLMW9nYnSmda+vDF3QhZcrsEqVgbqrydzTYBbXqOIrWEF4TNiOrKxzRest3kjZ40u+er73sF/w8BFyGx9fjU9CHTOdAlg4IvnGkeSawrWUy3EXjl8+k+TSdkjKzw+KlVePFWMUWASt6feUT19pkDy7v/GJx4kr1kv0w+mrCruuCOCh8b1oywDUKUXMY9G3UHP23C9blgGkvxW4AB396g3RBOYPvEU2R13uzWFS4fX0Ih/jeqI0kQqLbjg7g+l5oNC17EoJ3Y+VbLLI5DcxavxgPxjM3uV1DSz4VD3sTiK34h+dk9eNZDqn8wNoJ9Tyt5EQ9J8SxZJ1CKerjWseTsYYWp4CD9XUigCa44edsjG+qlv+Vb/xJJr3PBE8L3D51vI5Az6X+QKwtMFwPYhttJITFo9yQijrZ+1TOYDRmwnSGpfHKc3k1RkOLvNVAmTLKB8zImQD71wvoFLuhWbpPEm//xP/8S7xpHNkJqWlWhm52UpN7YkfUCl21X6KTObfCCqYaZNBNj7/f/5JpDbng3HVGkTr2kHZ6xAL/8HwlgD45GmyoR8sKmgSOrKVJJkhnjVi3z0JnYhgPdndoo5rLhsvvn7YHoTf5Aeq7zSFKA8qb6VslcSjLo0KFiFDMF2tTH/umK12fhTt6aXSb7FVmtyRHicU4fDsGWqmynk0Mf3yjiIsSmStdclrSFS1gBdkWTSge+wRD0pgxwpHDiRy+o2uInOBmNCgOgp+VKUcDt3vAXUV6RjIrTDt9Jxl0HDbCPXEbctllQKpS7EZLOx0W6L22iuKJ7gxneA4sGuHC6AteerolS5fYyrzyaJGoVaqRF5xLhsA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
