---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCLE+GM5UxRY1zXlHhOVkph0JKXhbhpkjU+IAbNNpEoInyYUthCFb+oOxVMQltF1dFT6GVwACI5EwtcNINu5wSAWdpiqoyVpTAxK65EvEsDiihFd/YF5ML3ULCekmVUQRrm+1yCcNOp2dlXY3Agnei1QIY7GhiPkGtRDU81kx4fptnjXuk/+KltXfKWmDmuvdo+XxuDAzvFIW7O7iBYsLpCT5npxF5gqrcBPGPdmUVeADDD1/xfw7LOfL3pDASVCyp/7K9/8BoA9BzhmmHKQ0Y3WZ+KVmyO8X+qzJcJ4vmJmBVy6GA6rmkKix3f3sT7uIt2PfX0//pnt+YG9YLBdAQ11s4XCbqSf5N3UBMT/VQR4LtxGq9I1r0ezTfdZtwLFj51x/WCcOdPBN8FRaWNFZleQimh1QakxchlvQdl5KMH/7bSjiMpNPkAzzgleZo5kLF9oNf9xfACKGm93DSLvl2D7X0KnA/zrN6rFHhAhzIN0maTeLZ5wrk01AhqGz0eP9nMFv6TEG5ckYmTArsHc+V6ue6HUrP7Pr3A/X03LwQDGtgZLJWctd1RJOr4YBxBL5UsuWji22pw56ncnpD5lXfv3/b0ue3/3mPd87A/pXf3T5DQ/w8JL5VKiiTrcCYz5UF6T3/y+/XlvdHGChZ5eXMGyH91GqNiW3tH9Sw7WrVK+DB/Ga4pqW8LrDZTEHpcg7FllkAh6vgoci+mP2qVEipA6YZB+MXJMFSn8tLcDLXh5V7jl1MENcdlwrOiCY9nz8GsuKEcvf1mdMJ0subLjS3cumf3K/YFpvvnO/fcij9WtlbWFm+Xqtenr1YxSWNhem9guuU+9shS3+m1wPW/utnoGMroyMGEzStO7HshtRX1mUzFtPHwRud3JNqY6KqYt4slbvFOVTD0GD1sDZ0DNQp3Ig==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
