---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgAT1WgrcnJbZhwTI53kUYk3CyTcnhVsqAw85EXXBcKEO+4xDHpn78veqxMTqTgsl8y7Un2u5VkQ0FSJNtx9fA1yotoFgtr0w5ki1cw7hCqKPkVwAqZqPvV/hn0DG57dJbIf7T3iNBmEzil0UCqY7i5rd/n1AvLU9zdPt2v/dNB90k0FW8o95bR+XqMbdbn7DqeTjh9khSSBQouNecoHiryD/9XhPHSC1Xu4wM8Wov0LufrUcXpRpoP18+rHBA0Xk7x+sj1s2bS2KQW74OMo3cTDpTfJRay8vjUCX5D0INnX68/JnipQce76inGF05D1LFtCttCWi+3bYGC3IUlgEnfK8VnBm65KR2ryst/q/Ss5L1WXg4a/xJMPj6e779IEU9dw0T7agqT05x/nbf4/h979caKb/c6WetZHnoq2nFNYcdSVQxbesdmQ4UNp5atKCM0aDW+Q/1GaRs/YcOVT2TqEvRVcRh/RpcsRmZPnMqrk8Y/qt8w2/VlTlb2oKCxkqG4fblxY6ewkLxw22+607CX9Vuibdh5pPUuthw/iHVwVpANirV7uUiQW/+YKZONGbzOFlzLcvOs+QSWg/Kz6LbUh1FIZcGbr+t/dLKChStkUNVxeFzc5GStWkTRDVLcCxsHg3J+0EbLtiKIhFchG1NP1ppW9wSjbkBZYznhrf9T35Qmu2Q1gvi0syaQlgXT+LrQJ4XeVgCE5wnwW8JDcE5mFWeWFjkKyLNcFT7GdIaolez95Fbu5E5j/
    email: AgCWBrpdU8heBbjgA9CApEl9W/Fr0Av2y1HXtUCNSVPGeF7T2gAPpWhRqVGLhbr0ehZan+Zd1LgKFlJ8gJPY0Ifg4TwmN/P31noxnq++dJsDpZ2jsXay2LxX8lJ9U/RHLe/ASJ1i2kiKjwOf4rDOeEc7EZ0I1v4/7gU0Mg3TEQkflf6OHSqGfD0YB3ESYE+ZmvQd6HSqaKhv7zP8l2kQauoFftEGf/qCAQOFbq2YLcTp1vclcA9fNfSMSXbWCcvprvMp/8X6PlLVxPptfmo7u0W0ZPiGJzpeW1A8luFI273v46XPtjEZLtgI0cuYZMrb2XISQw04xqfur+ZZKcW0dtyK+2dUlZcqFscusqkv+GL35V3E2ekVeP4H9ZVqFrWuTmySSlPQN/8WhhB2/HWKkp5lhV0wB2d5nPMZcR9pgI5ObMTumj6iazK9bPlvN93HBfAD//J2D2YLziVr9o2a0HVkdX9flfp93leQYwATiJKfufD5TAUjZzzaF65wBRM9ab6k+BdteF5AcyDnWG1WlgnPbaBr/cFivcSRC07WJYVc0JkYVhP5i8cCMeVvqVRmj66II/hXd85m8wkKnZXYf/dvMyAF4BR5OJchex9o0zhKaYQvYZqCIpVwl4n1MioM4ptp7PINhvbk1obL7gvtipvSYGlqmi9g35FXybSNDq71lkEaz55bDVtvdfNxQEZKYg2W4GosTbQbpc7GKe5badlPa5g1ymua
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
