---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgClD7qqzzpMfmO3FagL1qdY/WY04wn9Jb7ujPR1w+cbIO9BTtDgn8x2Z0LBfM+vgzP1H5sDg+u9hHYEVwew1Bn7uOYQakwXmDbmZy0bLxPhoXcuzt876xqcyVwFSpZ4Xm2qUGXYKuEvRd6rCJcXlxzcG+udi0T2s2mqawlR4euSgO/vSwvpmRxD1HdzZASMSxUr8kjYAc5nBBGD3g9PNijV0nxZwLhrQBobZg7H0lU5wH1Q5KZZt5Oza2YIuvP3bXW+Cj3CPxXGsK4fZMgpMKEDrhEyGdavwAnCGPmy7fMB/L5K+VexMigsKaoLMFTp780kywiGbmKLrD1Q8sV9/w7jeQV1/981hvHk+j3DAV0gHvWEtaEUxdctjB/VRUmoSNi+cMw4D+ECnr52OwWDBxQo7MiUMXRY7XZ7IdgeydptI/sWh768bidFO7GfB0sSTVEHDgoA4NwuwfwEy9rSvaAN8D1gxNtb4TdSANny+PCagnGT/M3i7FXbDxbryu9EE6TKLXmKbyBhdx/Ziu+I3n+LJsHhSn8AC9CIW3bGFasVgprDc7WpdXIYGy3lQyXIdAwmlCWNCSOduEp3Rah1NfMIb94KDity/8wNSLy8GaeoMB5pO0WbOqVrn3r2XbX/rtCIKw+0b/nQA1XJcPfG08n+Dl7s8EVe45zrcB1jMGbf4Ivp9yTWY2QksxsO/IpCp9J40VBrZyGpTJnvZp/BtnHTcX0W4msaI1DIUP9f2UoeyHYNtteVW8kyzWFDlGvInY7Z8XgVEk4eYXUywoRVrAHEJdt0LOSSWKdgtk17egsR0w11EzcMoOMgXst/FzAtue/iVyIZlqfJoE/+8RTdurjIyjM+5Wtx5FndEJuAPMPnGucjafvUqPq0Z+Q2nZ0hy51M2LU24opFOYWS72W997gNRQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
