---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAqCkB1j4lREBqgEKfgTbS7l/YL9XukJsSWTYtiTgqXVD5hpLEj+M1oW19IU+1SbQaama6pGE757HyhPtQ8buOg5OuuBYIMX+HhrL2nDai/6CW9NQeHfJzq2J4ow+jD2J81S3sWXoSkxOUdZHYDa6ig08ZK7cDrk5dxTvnXFC3Yqqa5xt9Gj6tGLDRKbDbnLc3w0nYDROfL7xve8rnWVvseG3ebFn2WxUOvw63vNrqDOETShBKnrO7IhcQqhCvvjF2JqJEho2fLmhBjG+8m9X+G5J+MXfF5k/dX+/gLSK413Hsw+/XTUzxoOJjQPz1TYU/jKteFcoBXg/IktJAl3G2Xk49N0zeYabk6OScyMwdmyki6eQVebq6okuECoZxgjPgR9W1QqYvBalmgUguXJqv8iXaT80wiTzRgYg+fBQYcAfkl3W9eg5RciIYDu3qivV+GbHKemM+rY6W93LAhLf64y7HH3bZv0dphyoAM4IAYd9B1qa45T/mmoJjq/45ffs8lJQHtMGmQ4Dz+YXMHvyuGMpIrDZOWO2h9Ln5jU2XB82UbvaAa0+5V70eT7CBqDMLADRW9M3G3eRTa8uMHwak1Efw+9+jkrA6P+HWlUNaiKRM6wgmu44pQnYs0h/iFEgEyUuNpVnU9bTyxha2wmwTtBD5G7tJ4osFWBtP14JZwkyUmHLfa8wE3eHU3tHnpkxO48yQWxus7Ci2d7gvx6M5eQBguY69/MG+OQTES4q1IMvneg0WcGcNkG38l/ol8vV7nR7rCQjfFTNSIxow73LfWeI/V0vRXQTdDOE03sSfMLhzqZ3MiHmyEtC8vj1LWZ4NAq7VhOIxEF4mMVKpu0cJQ7CcrmYC+OSV9tRScvUwD1a0FJavgvZiVPoiK/EsvBp0lYziDbdUhIzZpjdP9J62RcA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
