---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgB2LO4UgTgSZePocmnRHKEWyQ325D8b3QcDX4EKasu9R8AWztl+EHORCE71AHNDILC5XKhUVfreXzcfb6pjK3dW2E0wqjzcqroBaEYPy/ObH7DNVYaUfhno4vhaU62CRsNLKA7KIntssIFD1D6uxs8T+G0+BcJZDIy5IqQHeng0ID4gDW9MxiTA8JCcpRjNnw5EUWHC9XvjEiyrIvzccxSz5e13ujnkLKGlLTlklO8iRjnJVKi0y63nwWnp9DIdKKTM7r4jnC7OJeexh3OMPvSwRSGd0CbVQadgRMYEJW7OUS0vMrg/LiIji3xQ479HdrU0+9ztRl6vJ8duzTwVhi5DKZc8JJBdSCgxi8eW2cCc4EBKNTyjfUvvVCQN+uvr7wQxlse9u+TqbdWrvqO7CfAIdYwNJtXutd1PfKHM7VpTTtYGsp7VPhCc2sVEltQY+Jvof2/lMlEJmaYq6kpjeWmeKLzTuTJYBMzrwOoZ7y6+SVHZC7qZwMD83+Z908kBXThhBefM/z1ihSZ3nPevxu/ttiUSgcvOrh6sfnvCwScWAFezusH6tCHrM/bpoKfHI/KEP/ZmVW1INMr7A24/QFbt88qCb+jFunw+a/XW4FKrCKnw/dvE++7QDJQjxjGqlKMtGiXebT8NGd97CMHUGBXeJ5KlT1SOYctAL/s/EyaWLRKZtcQJ2jqE+6zySkMVq3CGDwVLKB1icB1A8Gm4+U+19yPvGgJPD7HVatT+//shwfawyNfncyTd
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
