---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgA3y4W5RTSCg1qYodQxM6C0swTElPl+QUwbiVVr/MUMIvJoXkCFvTVoyjKIfqzzEC7mHRRwLJzLyFAx6dPIhyZ43Xgz3p1ImWnj3mXfvR7Bpss1beWXRTRsSzlBJkkjVyX3MGVElDGZ6pmbnV7hFMdSOjtD3bwOqy0s9Et82Xmd0gulPiasPnpjJyN/nGBjl9EfsyNLdvXAW9libRMEaxU8snHfaODOsYkJv/4I2eSL1BDtYkT/U3jfCyLhyd29iwkQ8XKPNsKHCsT/I5unZX6c30B7dxwPxZW4TwpLdbr4CKczLNQSCWFJqOYoYODTQCOAhCi8HvlBJK+XGhAziZkh3SfHbLp/Zy0uWwiFaslanuUm8ss05qv7fbYEDvhubb2f/aayrc3IElkNxGSlmnEYfgwt+XFqmLZezpkgj+JwZsBfPO7joBlXrndyow2K+rIkjdqXUlaFWODdem8xaTWgXpeWajuZdv7/D0Ig2xOtFGWaQzB7NOqUre+VwS6RREEvgEp/cspvke414JdXGhFIuruVaC0tNi8rUtNVMeQmaB8Hr6dCewGQ1nOrDw5VwP9n0npT525DJodY++ZNr1dShnnvov6gTsocOwR47xqaewMwep3cRr6WlX4b+0nd9YRXuP0miDZNKdJb0A5w03JRnoGFAwUn00pUzDNBAP1tvdkomDwza+QOdokI5eHLTVHNNibVhO9rR8IU8beaGLjnOe2JzW94+zDCxTc0Z1s+cXA10hIscNcM
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
