---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgALlO4pZxtTWgaWd75oPfW36xhY9z+ACGfReawyyLr9bgsTaM4Bie577lSn+w3gj6ej9TbcdL5tbK2WNiiYYpuGgXVVb+kVdNr70p0/2+v0+4yeLrJnL5QBsS5SmtYbX6EiEYbOIuZ697Iwz+XdDJiZCn1tMY3DI6g+Swum+tBtq/i1rHpU+lhe1Bsb/0hePZGwbZ+XfUkIPXoysbwEXQrzTunHGF/5/8vCg0uJJ9AT4icGK3nU+yE/scMBxweCIwoKjJW4j+kclwhGBpqnZdgHTySMCmnHzzhjawtiWDo7wuc8RIu6vkb9xC8KNglpfUgdo7B8cDrshqeNXfEntYhEnwqZ8Mf2bLwokcz8u3VeqWQf8o/8lshSgmQMYGG6JFFlBdSWGrk2tE7eJq8NXNicpRbqxOShGGUT1L6+xN1doFShsHAoc9owkn9+rxHcA/VbeF5MH0AwPNCjacdIbt8evSVkh3iM729FpPsQRUOZf841wXSPx191rXxrqMVM4ObsAhgD5L2uOB9MwPPFXGuU4/NJ3ilHEjBbKIpBqCpxbUQdv0QxbdEJCCxsbVE6I1WO7y4UiGCJR6Vq6jGRZyUjXYmZOhvvOpBzm2ASpqvSXeYklWunSGsNIjevFuyg1Jk/OwdVVSzkrdajXcllHByc3WGN/NfapKTa7G+jOhxfPX7QQ0jvQzB4kPfMkTCzz7YhHWaZ1Khbqlz/Y9xYEcdhzwE8RxCtYRI=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
