---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAkExLzw5FaatNduwc7ngjVyHG6XHTwdgaha96umoOWBnLs/n3V00y+MG44JoExb8Xw8trduRgZ2zpfshkbwLoaTNVfz88RKiHa4fNz/9DFSZe73KSC7FK0dkk/40F3TBfCe30l6A36hKDzqDPu9WocqVhaTia04gbUivJvjmJp7HVp1KdfYxYrYe3l66GejGaHh2gwcMc/2J95F0dXV41vps7ong5MNOcxry5dnFs7T3YPWJpoaQcr7ohjeQDNAsAhN3zW0NfgIkDC9DrROY5qs6XYdAPvEzB24Qx3y/UpU1meMM25vREV9jWlIDi1BmQLv/r5n71kXyXhjPVcu7mheLplHz/qJ85pvU36ioP05G98md5Pec0dKXimkWep08Nrb4qDAXfWv47lHMvRjsIY2d9r+GO5s5rEGzGOHI51XrHdppgl2OEJixxGcZhe0HeRCUxoFCpxmHlza1Bg+vyXcznrirGgSiTn32xA89YGfIM/1rA15TdXtA0N29OHUYP0v+1cd7mj9dsBi5FOKKx8OwviX3gcGS2oPUiF4ZOwmM9ibBYTK1/5/NIpBIlKJOCVQiKDIJlq+2KCPomrxwMJPXNoVHU//OBN2CE+zyur+KfbJmT6a5LcyE8b1Fny0YFWC5Tx3DhiflhPA7QQiwTdlsglPHleqt8AW932kxbWZUVSmk2Gd+b+mW65PGNgEu5cc//wi0zElnZ9xQkfM8T4hvGhjaFkRos=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
