---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-fpi
  namespace: argo-events
spec:
  encryptedData:
    token: AgBewfBeh4KZr5N9n2QAi8X21ylscOGLQ5iKtNc5M+ZkcguTguK8Dv3TvEX39qzXBmN4FOHiQSDomyWXo21J4DxucJpHlBCoTxgUcqle20XigSLZf87jq13Zvpvqu04M7/bKjGZuTGCrtQipm9AMdpCrl2hiIzaRa1DFs4EhXJHa3Rl2eIQUp+JUjy26m+BD9XPmS98JfsWsomcbXOXJJjoI1Sc7Tsg+WfpZg/oLcoTn+v3KP9QYQiMq2WOQ4dZQe/BcQVkjCq3lXrZSaLVIs7r94g7rj3FAvcRSXsBt/tYcMZNblRXh9xrwnepatpjiZrMr4VILqr9IMALKzoE0oJdQTrZ/QBBNH6WSzZcxfGZYGaKf81ZhdrmpClvovBKvHfKlyfIsrl4o8VLzGc+V/JuttqmxAA17mKLtuXaUTRd7KQiarR48MBdxbvH9BfB0wPdpI1h0RuSHfnZGMY/KACr2XffiXWplJXIjo+kgwYyfWuc4P1DQ+Ue0eKZMo9/OOUi/R0YLPaNYpXG+8y3k9fkuolCNKNLzxSvOl95hs9QzkamWXdKPose9/Cvih/Ghi7QAdzebgUEzQBpNqDByAJv25i1F/5ejopAm90TujVNc4ArPe4A/3zZa/tH0yqFDYbhZM0HejaroIY2HUgU7eu5dW7QjmUYqeKWdgbFPUeE55AJ/fYtksyYR0UoLoA/F7Bo20pDPV3s1vETUel+Mi8uNzBKktih/vXOaZOR02Xm4eKl7IIQ3UXRE
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-fpi
      namespace: argo-events
