---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-fpi
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAE8EAu1qZ3g4gNjZb94Eute5eck/lrqGaWAFj4wpJfU/qMxC2qQnOSOXYm6XMENoBel498Z3fZ3eSCgf/178wVDnweGYdMTio+rzTXKr9oZzG+8KDtG8PMy9xdHuVAmT5mi4jNOCv3jyrlU7BBNMJsb05n0Du8Be6rA0ND9fVtDVajQqHjc3SqWfnBuf1+7bc+LeWRd2lOJiEGxbhi3ZaYnRNUV7LdFDlQHXTAPo7BfZGYSFPnxs0CqqGz3vqNz8xZfw/+ex5ie668r74Hm2yMv1XQgnL7h+Q7kcwqt/nyHcA2IInzHr+ZEZJIiAY43CpAr36EKW9KplEeCLBKhNoUwg4rLN9pm1VUfyp1BHMbSFU3q3V/8QrsdCVAt+KJlMXTS5DmofJnoGtkI6kPQTYCSYokfmR1Nk1/9sxzircPOJsAzInyjvEGakyisV6Pe+OxTN9xiHDV/rdveKmBk6mlllx688TKL5HPd3IR8OzadP81LuM0us+qdQzq7FPviOFDZZNWgJlw7bfgbqGsUucJ4cui7jnzzzbInv908HJNExQl2D2oCdhqSRfRlE3aCs7fksmTpiWwnNOjZioE5+CzPLal1i/kvI6hZAHx0fftz7Sg3F49y6hdMH9wyUAa9LVDNW3ngr9EtWWhZGymVD7CpNkLkyddYb53bBw+PsOhQuTHJjzWBJxVizIqIlPUzzDqmB5k/+CqkL+N/eJkc5UupZdFmGl3WiPlvfyv4IStiLJprdC/qjSt
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-fpi
      namespace: argo-events
