---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgBjfmBx7dPYnBnR/h4dluz4PTJbveuT8PTnAPrTdSbHFTolfO/zJQJsaiDCITJfZHmmH6olaHBuxdsdtbjRj6QWDsET+Ur+jQmQmLwMg1H/Pvw5mGzcUTSWOA3DtGG+6Xw0hkPtnft/ug8hcsvYDt54CUeK0DJ8eOwcbzsQLRVh0crXnUfUyHORHxJlxHkYkzeY1JBp7ulR1ip+7X/kRc2oGVF8wXxEDNN53ku5T451JtuCDSaXZ4SQUwfFI9hfmLC+kcoZa1YCX8zY7/Wbe+m/hM6q2MdQOH9D8qHWMYF3/GtGUysPocBR+cBp8XfH4n7OAIhureGQ/7W+aWZeb7TY1mfQBpEZhjc6z0KzrvfbjkcrBWZkATkU3TteQSa9G/6iFyssulk7elnXBPG5O5IrchGbsqqHrZMLwl7+iHRYLQi8EjXyYi9m+ke5NMzyJOEXk1+q5Cla6i4FfxguJ3PM/7kv/Ziq1s1/FYk1dJNVgDgEjsh8L+y92eVp6KzkD00YS3KU4iyUqK0dGnd0bf1PuKXSQe7GQze4uKMmeR7CXNpETU24A+gZAHe7Tdh75/o5ZYRattg3GCSdxwpvGJIteugB+6KW6ZucahmBsRo6LNHRUTO6sH4BONDDIDBXYiW65fc88kKKVoMtFHrXrLQvD7XxeNX7Z5/XkW+757/pekN8oXUp5rkkdnWSpy0nK5VdJWj3GAJe1O0aACM1wX6qcvo2T1s=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
