---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-fpi
  namespace: argo-events
spec:
  encryptedData:
    secret: AgClD/y1zKA6T0vjloWNbRfXndR+gJD/OLGKRMLAvHrirKX0olqBpyS3n9Y9OmK7bUrDsK1Ijz6poXHM2S7Z1x+8TiyFoFstM2hDX8a/mDqac4950dp0ds6b2RRmaBlS9khT9e+MeMARg0zu1htGxa5HY8lXCxNaw5PhuINP3skOgN1bpI3zm9Dxgodo0YCxR05fbdoqLWk/lxCX4riEaVKGbznRYcGl8vv+nhCplRXg88HtogW/y8+CHF7QRT+EgZTxGHhBinc03JZewBZNSA/5yQOOXNQ5+JYRPrJZN4UtuB/ArEzpsfSeIhXPDM1ag/BNZMbl++VMbEwXqOxMxnrwuZtCHPIRSOrRoxT76pyQQYtVpc4VZK9HzPq+GBGu5g/pTMy9HlO7td9NJgowtmA2dROFDKKE3RpOz/eAWy9JCSjPsMd/uX0xuWgX4ak5eeAOQ+2c22XXsTpyQRttLEVz0Knyf/G08lFeKRMa0n/a/R/TAEJ0fqRr5SLUMP+vL6C8iUHXBeadGSdHlzMAbQu/pi3gNGScJGduRqt/CtnivPq4XA3b1+vSHv2J0zOmM62UnwZlBz5UjIgd+7YJYIQKFMRJlYJfONVfPzh5rTn09OAmw/TeDiZAUXOmvwz0haK7ffUxtCAUOGgAdDCs2d796XS5t7KFAH9EfDuG1fLihUResMGjtx7fFDQHX0i8z5/Uv3zixsV+Sabp0/2nxa5SazeUHR9/lHU=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-fpi
      namespace: argo-events
