---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-fpi
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAe8+MWkkY2LAbBwOidE/J2IMiPeD4FPkWoqSvxJFISW/wi8VRE9DiRd+qmZ+7+ym/p6NEyOgv8No+aev6hZZ5OgIT/IvBPmR4sbfATKbU48/MY/32HBxBurc/PZcki9ZMnt0HAD4vZvi8rPqMlxbdhJleIT5PYQX7Qt3WxJ8EgQuiPRgV0+Hjf2iSwCqKK7CNQE/3FX4fd9RcBoRFQAkV4nDrW3kBcJCsZOwv58WnJetprIzu7FH5ViRea7sqfufa3J7XEUYkZRnWc6GvcuW2cdMLOnL/NeAWkU0KQWhoFv30DRj0lRfu1yU92OQOTx7mDPQS25G4rnxLvICLBtLfMyqKXhJbw7BxzdpUORCplrLUoJdUPvlsrB8JfVy6GUCQXjxhKIFzMlq1SMgumq9MlFRVQPk9MajWV9VRuO17vYKadcwOW+UXJ7P5bShtiVnoHTpJaxAyzLEmx8RH6KAGDTZ17kXvLNnxX7fBY5QQ1n9KHCT38ScKY3F5bFp5PDHs0EcPJZGF9303tkVlazyfp/S2uAbbJRZvWiFAyqU5ijkk1P4Q55y5JY4ofTBxhPkAJncRJf6G8BR57va+VvKP/b7d1BU6Ony/yen0TiTUObzjJeQv/09ABaAMBRRUNy2asLFjtVpgyLhoHijeQad11YMeEj4vwGgLo/X9yyXWmZmZ5lsmg2tzw6Bg4JC+et9PDYSufiW8jwp0WwyumdXEn0+8VE4JrjYU=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-fpi
      namespace: argo-events
