---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-fpi
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAIKMY1u/8i1agqBsG2h2dhy1hN0KyCcVs90+cpm4avYYWgcxZet7xu2fgDbtx0ornuc/09w15RqfTt5ij96ODZIDLqzvgq6PSSUaogFw1/VV4N6+/RGgMmOtEh9YM00hsUjMBnc/rhYZ+5G0K0tV5n/ZRLn939qZO0CmcdtcPkgTD6XJDwehzJxrCrA5LgtzQDYBdOST5yWBIdOTwI/Tp4x6un3L81dbfQ6T61xOGfMIGShbWYGS0yVuJgkH+2ug62xJ3ZziAAW5vn4nPoDdMfv/XCcbftx0o5XwcHGl9Ge4tQkpaHcmT+BuxnMDST2Q0Tg4VwLYIGO6X53yDmKnw/Lq4nML7aMXjsFrytseXNPHQSsLBWJ22eQDZKpPOfgx6+PCzjLAEO2+OBvlCMVgdhrslRcIGFIOJeRNyWb2KQgC8HpKOErBuAVuiSf1gZ+dM9+31lRbA+vLiEyjgiDEyrGu4G3ppkb+SeTTuTfhpeu6XxU68f5wo1CAjHazbOe7WfTTBKE6V/Om5+BufFut1BJkNEWeF+C5PkYx2aZ5n+pCg7IGJGJ3KHUVLO0XiMyeU9xUfw620Of8t5pilqn/2XPxbPe412Hsl0aaEh/FrpH372YNiWkF+QO5qiPSBjG6Mm3cz8kbB3hS/tb3mcFLamAQprhB5iyXC2nL2A76ZRxg/bgQ8fn5mCWSIUCVQF/pqnkdiLqSV+0WMM7WtKX8XMxSKKYJfLqkE=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-fpi
      namespace: argo-events
