---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    token: AgAd/Wc/7z2S6yA1Y9MdqakPBdBvZ+uslRV9FxvHHzYxU45TpMT0IFOfy4VW/lTEwnCwjOhyonCcGzu0icohrhbBEuncGIecqDucuLcr+LfD6OB0uITspuZazzv35vNE9ZaG13UvDsBo18pgv0BZvWsEme6SU7ytFOxABsW76Vkowa90E7QkvkTS3UjCIjkPej787PtAws5pUc2U4ZPOvpJ8httjn4gVtFQE+ZnRkyR93v1XDHUWAmyO6NfSc6I8FHP92zbmHOUQcQYvlYHQFOO3d9zxYVeyHUGYyEWRekWnbnMnEyLJUYlCbwNjaDA+iILhXS/DdSTDRg7w7p915/KpAku/LZRuDN+Gj+reZgpsXFN9GOjXGuGqMgKDD3WyHVIDmVYGjhopnVMbOZXyrkjGkNghD1pL2ONH2OsfK/J6u3LBSUXG+9jG3tiHp9NvvuXGqU8MQSQ0jN+7cDw9tobLhi7iYbYd57bXZNrB97zToS0Cck8oDlN6iOIXCqSRHrGjg7EsseQAUpkSbIHyvOt1UoE9vAaW2+dLNY9PUzy2pglcMvQta2M6d7oCDlNpmFKVt8zqi3zwwAQ50vgM8VdGojQrGB4s6sUMT/4/TgsUS1Qy6ijZFCiI6t9McA8e2v9wsvHh1U/8OqqKqexRvO6+NAbnvMu2AqlKB4XwUVPyw3TumrEAJgkD2Mi0UmraZQSY1m4EoLiA74c7RaesKX+AqyeZNTQvZLHxSYIrx9QjXEu9L2tg8vWh
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
