---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-fpi
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAUMAU79JVVhQ/CJauXGgtLC25hNLX7cj/V3B6iTV3LKwSCzLuicDeO+RrrVyWLuk/gS6oRYR7Rhom78TK7BpNIcvIR2nhlsHbkAjqZ31GhgMIGPbTR0o1mCYFVwdR/SDigG+iJtHlnTuzX/agGwvbt2FKjnc7f8PnuLB2kRj9YyHUCFiwaiWdj9hcDpJOHB+vOcZc7zrExPOvAQ/KyrPZUDWagK0V2YkbGg9ZDlP4UUbRE1L+NHfYdruHoEk/yqLzuKjxrMq1+81+zhDDjbl74QaW4AVHIohmGHb3HnnGhoDn6Y52Rz5B5BD42j/YOo8xx0NhRwPaQsq2CW8QTlU2bztIjz8PgFLT5UVfBUGAESIyCyV1sxpKsH7Hus2HF2iMJXLVcKBjA6XoUVF9+snyeTsBXI02oVJHVuIYOLJb8xZbLLyGYQ/bLJBbP4+fq0xX+6/DEkmBxp6sClCBzx4LMBl+PNK//d60eMuH8ropqex4s2imzUEJW+wPQkUErAz3AMRprvJNVPGVPt68UUwVW8+JV6lzCimmKTusoPZNPG0ldXXUmJw7443TI+utUso43kYn3TRawang3HqjVhlZKvgg6OqURC5z3O4Rdl76pg8QwwQfknS80vFg4PwWF980ylJ1HvJNWWkLYS9+visi+t2UKkqUCKXNigtmsUFDDFPodn23OMuTqmiHhbny9gWcqUFrdcGIGn3XV/Gvsjs8UvLWcyRr0DKQ=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-fpi
      namespace: argo-events
