---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-fpi
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAGQIj0OjMV15NgtbdLyj4+xUH4un7JgJ0p9pJW8n+O8xgThs3XqF/5rHwc3YJQwUYzP2nUnomoq1v+lF6Yyy1MENHQrZTLxdMPGJhBz6T73z/IPxm5A3+p96upQpOCu4Zf1Deonukjyhmd7epwxlPI+0ra5GGOV7I3DIPex11MsnHb+6dEt4DIGwpg4fExhe7dHrKVIie1IgY7NMB/Rqptew38maTM4kbACJ+38pYQsgSszL8BEJiGzfuhqND7qCvwYAUDZd8VxispNCURAJ5ZRG7TrN4HHRM4Apj1idJ6tho5b1LJukj9qcvEvau3VaEEIgKKxMIFaqy4vzsd6BfDBpj5xeyajGmdFTNtdDRyGDJ4zOftZqCdBZKB2z6AGIn8p04Lx39ABRkmIfpQ+TWfHWMl+LlhHrYoLzgyQOEUPKtwDOcqO5q7ZNe58cFDQE0xOSiOs5fpMnq+aLxzYYq6DzNQ1NfQ4MML3epoC7lA9W7grWBn+nzbGWn/nOIY87JTLVH4yW/H6sVmga4s+2KmGuQTTlmj0Fvlf00vBODsCkZL6zg3diJG1QGSfikkNcqdEsFGOVfZtne27KGIft+oALVpEgNaAV+3o/gAg0IBHU4UbxpPVto6TFJ3bnZQEvlBgqR2C24cdN09zrzuskncKf3zCRddq7fKrG5bGvNQkGz5EXNDDJgjmdm0m/X2BGJJJA+T5fdX2ECjPtxbwlRRmrGGSFrX1iI=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-fpi
      namespace: argo-events
