nameOverride: argocd
fullnameOverride: argocd
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
      name: docker-io-helm-oci
      namespace: argocd
    stringData:
      url: registry-1.docker.io/bitnamicharts
      name: bitnamicharts
      type: helm
      enableOCI: "true"
configs:
  cm:
    create: true
    exec.enabled: true
    statusbadge.enabled: true
    accounts.watcher: login,apiKey
    accounts.watcher.enabled: "true"
  params:
    applicationsetcontroller.policy: sync
    applicationsetcontroller.enable.progressive.syncs: true
  rbac:
    create: true
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, *, *, *, allow
      g, admin, role:admin

      p, role:application-watcher, applications, get, */*, allow
      g, watcher, role:application-watcher
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      # labels:
      #   release: prometheus
      # selector:
      #   release: prometheus
dex:
  enabled: false
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
    selector:
      release: prometheus
server:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      labels:
        release: prometheus
      selector:
        release: prometheus
  ingress:
    enabled: true
    annotations:
      #cert-manager.io/cluster-issuer: devops-local
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/hostname: cd.devopslaboratory.org
      external-dns.alpha.kubernetes.io/target: 448c33fd-ba88-462e-a9a4-19891a1a8623
    ingressClassName: nginx
    hostname: cd.devopslaboratory.org
    path: /
    tls: false
  ingressGrpc:
    enabled: true
    ingressClassName: nginx

applicationSet:
  enabled: true
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      labels:
        release: prometheus
      selector:
        release: prometheus
notifications:
  enabled: false